### PR TITLE
www: compress Rest API responses

### PR DESCRIPTION
**Pull request by tdesveaux**
## Contributor Checklist:

* [x] I have updated the unit tests
* [x] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [x] I have updated the appropriate documentation

### CODE REVIEW

**Review by p12tic — APPROVED** [review]
In the future it makes sense to support Brotli too.

**Comment by tdesveaux** [comment]
> In the future it makes sense to support Brotli too.

It would be failry easy (zstd as well), but would require an extra dependency.
I think it's the reason Twisted only implement a GZip encoding class.

**Comment by tdesveaux** [comment]
Convert to draft, adding Brotli/zstd support is pretty trivial, so might as well do it here.

**Comment by tdesveaux** [comment]
Removed the config to control compression level. Everything uses the defaults, maybe the brotli/zstd ones should be bumped higher?

brotli and zstd are optional and can be installed with the corresponding extras when installing Buildbot.

**Review by p12tic — APPROVED** [review]
Great, thanks!

**Pull request merged**
