### PR TITLE
remove more self.master = master instances

### PR DESCRIPTION
**Pull request by tardyp**
method: 

- trial -x buildbot.unit
- fix the setMaster, by properly setting the service hierarchy.

TODO: 
- [x] 73 crashes in the unit tests

### CODE REVIEW

**Comment by jaredgrubb** [comment]
LGTM!

**Comment by tardyp** [comment]
done with fixing the 700 remaining tests.

**Comment by tardyp** [comment]
https://github.com/tardyp/cctrial helped a lot for fixing all those tests.

**Comment by yetanotherion** [comment]
:+1:

**Comment by sa2ajj** [comment]
@tardyp you are our here! :smile:

**Pull request merged**
