### PR TITLE
sort tags in DB response - Fixes #3058

### PR DESCRIPTION
**Pull request by djmitche**

### CODE REVIEW

**Comment by sa2ajj** [comment]
Very interesting: a lot of PEP8 problems not related to this PR.

**Comment by tardyp** [comment]
This usually happens when a new version of a linter is out..

1.6.0 (2015-02-06)
News:

Ian Lee <ianlee1521@gmail.com> joined the project as a maintainer.
Changes:

Report E731 for lambda assignment. (Issue #277)
Report E704 for one-liner def instead of E701. Do not report this error in the default configuration. (Issue #277)
Replace codes E111, E112 and E113 with codes E114, E115 and E116 for bad indentation of comments. (Issue #274)
Report E266 instead of E265 when the block comment starts with multiple #. (Issue #270)
Report E402 for import statements not at the top of the file. (Issue #264)
Do not enforce whitespaces around ** operator. (Issue #292)
Strip whitespace from around paths during normalization. (Issue #339 / #343)
Update --format documentation. (Issue #198 / Pull Request #310)
Add .tox/ to default excludes. (Issue #335)
Do not report E121 or E126 in the default configuration. (Issues #256 / #316)
Allow spaces around the equals sign in an annotated function. (Issue #357)
Allow trailing backslash if in an inline comment. (Issue #374)
If --config is used, only that configuration is processed. Otherwise, merge the user and local configurations are merged. (Issue #368 / #369)

**Comment by sa2ajj** [comment]
So we probably be explicit about the linter we'd like to use...

**Comment by tardyp** [comment]
:+1:

**Pull request merged**
