### PR TITLE
worker.openstack: Support novaclient 3.x

### PR DESCRIPTION
**Pull request by cmouse**
Adds client_version support, which is required for python-novaclient 3.x.

### CODE REVIEW

**Comment by tardyp** [comment]
Can you update the release notes about it?

**Comment by cmouse** [comment]
AppVeyor failure due to older python-novaclient. Should there be some support for older versions?

**Comment by tardyp** [comment]
Is newer client compatible with older openstack infra?

I am not very confident with openstack to know if its okay to drop support for old version.

Question we have to ask us is will this add regression for people, e.g. this worked for them before, and now it does not work anymore.

If the answer is no, then you can safely update the setup.py requirements to upgrade the required version of novaclient

**Comment by cmouse** [comment]
it's more about the client library not being compatible. the 3.2.0/3.4.0 supports v1.1 infrastructure (at least claims to).

**Comment by tardyp** [comment]
yes, but client library is just a pip install -U away, right?
It does not need anything else fancy installed by the distro?

**Comment by cmouse** [comment]
it would seem so, yes.

**Comment by tardyp** [comment]
Please have a look at the test:

test_worker_openstack.py

It implement a fake novaclient api, which has the 1.1 api.
So for this PR, you need to update the fake, so that it matches the 3.x novaclient api.

So remaining work is:

* [ ] update the fake to match 3.x api
* [ ] update the doc to explain that novaclient>=3.0.0 is required for this mode
* [ ] update the release note explaining that we now require updated version.

**Comment by cmouse** [comment]
Can you provide more information how to relnotes?

**Comment by tardyp** [comment]
CONTRIBUTING.rst links to http://trac.buildbot.net/wiki/SubmittingPatches
which contains all information about this

**Comment by tardyp** [comment]
please make sure flake 8 pass

* [ ] make flake8

**Comment by seankelly** [comment]
I am pretty sure this should work fine with pre-3.0 novaclient too. The `novaclient.client.Client` function exists since 2.6.1; that was released in June 2012 and its API hasn't changed since.

**Comment by cmouse** [comment]
I'll check the 2.6 API and if it looks same, I can update docs and remove mention about 3.x

**Comment by cmouse** [comment]
It seems so, so I will update docs to reflect this.

**Comment by tardyp** [comment]
👍 The coverage miss is actually normal.

You can add # pragma no cover if you want your five checks

https://github.com/coagulant/coveralls-python#tips-for-coveragerc-config

**Comment by cmouse** [comment]
I think it's better it fails so it gets fixed some day.

**Pull request merged**
