### PR TITLE
Update twisted from 24.3.0 to 24.7.0

### PR DESCRIPTION
**Pull request by pmisik**
## Contributor Checklist:

* [ ] I have updated the unit tests
* [ ] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by tdesveaux** [comment]
Note that a master with Twisted >= 24.7.0 break communication with buildbot 0.8 worker (don't ask me how I know that...) which uses Twisted 18.7.0.

Didn't take the time to look into it, simply pinned the master to use 24.3.0.
It's reasonable to drop support, but might be worth it to mention in the changelog.

The exception from the master logs:
```log
2024-08-07 10:51:55+0200 [Broker,114328,192.168.3.147] worker '{WORKERNAME}' attaching from IPv4Address(type='TCP', host='{IP}', port=53982)
2024-08-07 10:51:55+0200 [Broker,114328,192.168.3.147] Unhandled Error
        Traceback (most recent call last):
          File "/venv/lib/python3.11/site-packages/twisted/python/log.py", line 96, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/venv/lib/python3.11/site-packages/twisted/python/log.py", line 80, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/venv/lib/python3.11/site-packages/twisted/python/context.py", line 117, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/venv/lib/python3.11/site-packages/twisted/python/context.py", line 82, in callWithContext
            return func(*args, **kw)
        --- <exception caught here> ---
          File "/venv/lib/python3.11/site-packages/twisted/internet/posixbase.py", line 481, in _doReadOrWrite
            why = selectable.doRead()
          File "/venv/lib/python3.11/site-packages/twisted/internet/tcp.py", line 250, in doRead
            return self._dataReceived(data)
          File "/venv/lib/python3.11/site-packages/twisted/internet/tcp.py", line 255, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/venv/lib/python3.11/site-packages/twisted/spread/banana.py", line 260, in dataReceived
            gotItem(item)
          File "/venv/lib/python3.11/site-packages/twisted/spread/banana.py", line 176, in gotItem
            self.callExpressionReceived(item)
          File "/venv/lib/python3.11/site-packages/twisted/spread/banana.py", line 137, in callExpressionReceived
            self.expressionReceived(obj)
          File "/venv/lib/python3.11/site-packages/twisted/spread/pb.py", line 615, in expressionReceived
            method(*sexp[1:])
          File "/venv/lib/python3.11/site-packages/twisted/spread/pb.py", line 1171, in proto_error
            d.errback(self.unserialize(fail))
          File "/venv/lib/python3.11/site-packages/twisted/spread/pb.py", line 943, in unserialize
            return unjelly(sexp, self.security, None, self)
          File "/venv/lib/python3.11/site-packages/twisted/spread/jelly.py", line 1092, in unjelly
            return _Unjellier(taster, persistentLoad, invoker).unjellyFull(sexp)
          File "/venv/lib/python3.11/site-packages/twisted/spread/jelly.py", line 629, in unjellyFull
            o = self.unjelly(obj)
          File "/venv/lib/python3.11/site-packages/twisted/spread/jelly.py", line 656, in unjelly
            return self._maybePostUnjelly(method(self, obj))
          File "/venv/lib/python3.11/site-packages/twisted/spread/flavors.py", line 411, in unjellyFor
            self.setCopyableState(unjellier.unjelly(jellyList[1]))
          File "/venv/lib/python3.11/site-packages/twisted/spread/pb.py", line 489, in setCopyableState
            state["_parents"] = state.pop("parents")
        builtins.KeyError: 'parents'
```

**Comment by pmisik** [comment]
@tdesveaux 

I've added news fragment based on your buildbot-contributor feedback.
I did not verify your feedback as all our workers are at 3.x.
We are anticipating soon upgrade to 4.x release due to improvement in https://github.com/buildbot/buildbot/pull/7912.

**Comment by pmisik** [comment]
It is worth to review #7980 first (I did not known `twisted.internet.defer.returnValue` is Python2 only related).
If it gets merged, I can remove the warning suppression
```
warnings.filterwarnings(
    "ignore",
    r"twisted.internet.defer.returnValue was deprecated in Twisted 24.7.0; "
    r"please use standard return statement instead",
    category=DeprecationWarning,
)
```

**Comment by pmisik** [comment]
As you have merged #7980 I've rebased this PR.

**Comment by pmisik** [comment]
Closed in favor of #7995

**Pull request closed without merging**
