### PR TITLE
Fixed an issue with the P4 step not handling whitespace in the viewspec.

### PR DESCRIPTION
**Pull request by gtmacdonald**
Viewspec lines need to be quoted if they contain whitespace.

### CODE REVIEW

**Comment by sa2ajj** [comment]
Thanks for the fix!

```
pep8 --config=common/pep8rc master/buildbot slave/buildslave www/*/buildbot_*/ www/*/setup.py
master/buildbot/steps/source/p4.py:308:1: W293 blank line contains whitespace

^
master/buildbot/steps/source/p4.py:312:1: W293 blank line contains whitespace

^
master/buildbot/steps/source/p4.py:315:1: W293 blank line contains whitespace

^
master/buildbot/steps/source/p4.py:317:1: W293 blank line contains whitespace

^
master/buildbot/steps/source/p4.py:320:1: W293 blank line contains whitespace

^
master/buildbot/steps/source/p4.py:325:1: W293 blank line contains whitespace

^
6       W293 blank line contains whitespace
6
make: *** [pep8] Error 1
```

**Comment by gtmacdonald** [comment]
You're welcome! Let me know if you need any changes.

**Comment by sa2ajj** [comment]
@gtmacdonald could you please fix the issues listed above by `pep8` tool?

**Comment by gtmacdonald** [comment]
Do I repeat the pull request steps? If I do, should I repeat the commit message? Sorry, my first patch on github.

**Comment by sa2ajj** [comment]
No you do not need to repeat those steps.

Update your commit (`git rebase -i` would help you) and then push it (`git push -f`)

**Comment by gtmacdonald** [comment]
Done, thx!

**Comment by sa2ajj** [comment]
Thanks!

**Comment by gtmacdonald** [comment]
So I've found a small bug. I didn't see that p4branch could be None, so if it's not set it will throw an exception.

I just need to change the has_whitespace function to account for the None:
~~~
    def has_whitespace(*args):
            return any([re.search(r'\s', i) for i in args if i is not None])
~~~

So what should I do? Can I rebase like before, or should I create a new ticket and fork on github?

**Comment by sa2ajj** [comment]
Please submit a new PR.

**Pull request merged**
