### PR TITLE
.github: Add configuration for running tests on Windows with Python 3.10 and 3.11

### LINKED ISSUE #6693: Consider running CI builds with python 3.10 and 3.11
It looks like you run buildbot CI builds with Python 3.7, 3.8, 3.9.
Python 3.10 and 3.11 are released for some time.
https://devguide.python.org/versions/

If possible, could you consider running the CI builds of Buildbot master and worker with Python 3.10 and 3.11 as well?

### PR DESCRIPTION
**Pull request by pmisik**
Fixes #6693

## Contributor Checklist:

* [ ] I have updated the unit tests
* [x] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by p12tic** [comment]
@pmisik Thanks. I see that tests are failing due to older hardcoded package versions in requirements-*.txt files. @mokibit is has a lot of work in progress in this area, so I don't think you should do it too. Just leave this PR and @mokibit will take over it.

**Comment by pmisik** [comment]
@p12tic Thank you and I appreciate your comments.

I'm aware @mokibit is actively contributing recent weeks with updating dependencies - 👍. 
Actually, I could not find any `requirements-*.txt` file explicitly mentioning `pywin32` inside https://github.com/buildbot/buildbot.git repository.
Based on github action log entry `Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]` I think it runs with compatible python version (x64) on Windows with pywin32 on github azure.

1. Have you any idea where pywin32 can be/is freezed to version 227?
2. Is it ok for you, if I keep my PR open and rebase it when you merge any dependency update change?

**Comment by pmisik** [comment]
I've figured out to fix build of this PR it is necessary to update:
- lz4 to 4.3.2 - already present in https://github.com/buildbot/buildbot/pull/6978 
- docker to 6.1.2 for Python 3.7+
- psutil to 5.9.5

As docker and psutil update is not present any open PR I created PR to fix this issue in https://github.com/buildbot/buildbot/pull/6990

**Comment by p12tic** [comment]
Thanks, this PR can now be rebased on master and could be merged

**Comment by pmisik** [comment]
Rebased

**Pull request merged**
