### PR TITLE
Add a Python 3.4 builder

### PR DESCRIPTION
**Pull request by rodrigc**

### CODE REVIEW

**Comment by rodrigc** [comment]
@tardyp can you add Python 3.4 to the list of Python versions on the buildbots?
There are still some Linux distributions which have Python 3.4 by default.

**Comment by tardyp** [comment]
updated the dockerfile: https://github.com/buildbot/metabbotcfg/pull/86

**Comment by seankelly** [comment]
3.4 builder still failing because of missing Python 3.4. Is there some way to indicate when the Docker image was built to see if it at least happened after the other PR?

**Comment by tardyp** [comment]
dammit. the new docker image now has python 3.4, but it pulled a new version of chrome which is not compatible with our version of selenium :-(

**Comment by rodrigc** [comment]
@tardyp Looks like you've upgraded protractor/selenium, so I think this works now.

**Pull request merged**
