### PR TITLE
Twisted 16.1.0 and no python2.6

### PR DESCRIPTION
**Pull request by rodrigc**
ClientService was introduced in Twisted 16.1.0: https://github.com/twisted/twisted/commit/8edae5d4ead787e15eb9ece026052f5cdf95b529

and as an additional note, Twisted 15.4.0 was the last to support Python 2.6:

https://github.com/twisted/twisted/commit/04c9ab20daeb386788341222dfa2ba46fe911ce0

As an effort to move towards supporting Twisted endpoints in https://github.com/buildbot/buildbot/pull/2387 , this will make things easier.

### CODE REVIEW

**Comment by tardyp** [comment]
+1 on this.  Lets discuss this in next meeting though, as it is a big drop of backward compat support.

**Comment by hugovk** [comment]
Here's the pip installs for buildbot from PyPI for the last month -- very low 2.6 numbers:
```
$ pypinfo --percent --pip buildbot pyversion
python_version percent download_count
-------------- ------- --------------
2.7              82.1%          2,443
3.5               9.7%            290
3.6               6.0%            180
3.4               1.4%             43
2.6               0.6%             19
3.7               0.0%              1

```

**Comment by seankelly** [comment]
Worker with somewhat higher usage:
```
python_version percent download_count 
-------------- ------- -------------- 
2.7              95.0%         17,969 
2.6               2.7%            517 
3.5               1.2%            219 
3.6               0.9%            164 
3.4               0.3%             50 
```

**Comment by seankelly** [comment]
Figured out some more options for `pypinfo` and a lot of the 2.6 installs for buildbot_worker are for an old version, 0.9.3. Using the past two release, 0.9.12 and 0.9.11, account for 0.095% of the 18,519 installs in the past month.
```
python_version version     percent download_count 
-------------- ----------- ------- -------------- 
2.7            0.9.7         65.7%         12,434 
2.7            0.9.5          8.0%          1,507 
2.7            0.9.3          6.8%          1,291 
2.7            0.9.12         6.6%          1,240 
2.7            0.9.0.post1    4.3%            806 
2.7            0.9.11         2.6%            492 
2.6            0.9.3          2.5%            478 
2.7            0.9.8          0.8%            142 
3.5            0.9.12         0.7%            135 
3.6            0.9.12         0.5%             86 
3.5            0.9.11         0.4%             84 
3.6            0.9.11         0.4%             78 
3.4            0.9.12         0.2%             34 
2.7            0.9.6          0.1%             18 
2.6            0.9.12         0.1%             18 
2.6            0.9.7          0.1%             17 
2.7            0.9.9          0.1%             16 
3.4            0.9.11         0.1%             15 
2.7            0.9.1          0.1%             13 
2.7            0.9.10         0.0%              7 
2.6            0.9.11         0.0%              2 
2.6            0.9.0.post1    0.0%              2 
2.7            0.9.2          0.0%              1 
2.7            0.9.4          0.0%              1 
2.7            0.9.0b9        0.0%              1 
3.4            0.9.7          0.0%              1 
```

I would think many of the 2.6 installs would instead by for 0.8, but that's even less true.
```
python_version percent download_count 
-------------- ------- -------------- 
2.7              98.9%          1,344 
3.5               0.5%              7 
2.6               0.3%              4 
3.6               0.2%              3 
3.4               0.1%              1 
```

**Comment by rodrigc** [comment]
This was discussed in the meeting: https://supybot.buildbot.net/meetings/buildbot/2017/buildbot.2017-10-31-17.00.html

No objection was raised to proceeding with this.

**Pull request merged**
