### PR TITLE
enginestrategy: retry on MySQL/InnoDB deadlock

### PR DESCRIPTION
**Pull request by yetanotherion**
Retry when observing the following Error

sqlalchemy.exc.OperationalError: (OperationalError)
(1213, 'Deadlock found when trying to get lock;
        try restarting transaction')

### CODE REVIEW

**Comment by rutsky** [comment]
@yetanotherion cay you give more details when this error occurs?

**Comment by yetanotherion** [comment]
It's an ETL (extract transform load) use case, on an old-style step.
It don't have more information to reproduce. Note however, that: 
- it seems coherent with the already existing (retry on deadlock error) strategy
https://github.com/buildbot/buildbot/blob/master/master/buildbot/db/enginestrategy.py#L55, and that
- the innodb manual seems to support that strategy
http://dev.mysql.com/doc/refman/5.7/en/innodb-error-handling.html
"Both deadlocks and lock wait timeouts are normal on busy servers and it is necessary for applications to  be aware that they may happen and handle them by retrying"

**Comment by yetanotherion** [comment]
I don't undertsand where the travis failure is, some tests became flaky ?

**Comment by yetanotherion** [comment]
Don't know who did it, but thanks for the rebuild :)

**Comment by tardyp** [comment]
looks good!

**Pull request merged**
