### PR TITLE
Support auth token _get_commit_msg

### PR DESCRIPTION
**Pull request by anish**
https://github.com/buildbot/buildbot/pull/3443 introduced the `_get_commit_msg` function, that interacts with the github api. This breaks the use of github event hook on any GitHub instances that enforce authentication. Add support for auth token

### CODE REVIEW

**Comment by tardyp** [comment]
looks good. need to fix unit tests.

**Comment by anish** [comment]
@tardyp working on it, I'm seeing 50 odd unrelated failures locally, need to fix the venv first

**Comment by anish** [comment]
@tardyp all done

**Comment by tardyp** [comment]
great job! thanks!

**Pull request merged**
