### PR TITLE
Ticket3321

### PR DESCRIPTION
**Pull request by ewongbb**
This is a Work in progress and this PR exists only for Feedback/review.  Not for Merging (at least, not now).  This is against Eight.

### CODE REVIEW

**Comment by tardyp** [comment]
I think this is good cleanup, but certainly must go nine first.

**Comment by sa2ajj** [comment]
And tests fail...

**Comment by ewongbb** [comment]
the tests were expected to fail..  I haven't finished the patch :)

**Comment by djmitche** [comment]
I don't think this is worth doing against the eight branch.  If you want to continue this work, please do so against the nine branch in a new PR.  Thanks Edmund!

**Pull request closed without merging**
