### PR TITLE
Add support for specifying private SSH keys for GitPoller

### PR DESCRIPTION
**Pull request by p12tic**
Currently there's no way to poll ssh:// git repositories if public key authentication is needed. E.g. Gitlab (at least the self-hosted instances) don't allow cloning via user+password combo. The workaround is to put the private key into the worker along with appropriate ssh config, which is inconvenient when many workers are involved and keys need to be changed or introduced.

Git allows specification of the private SSH key via the following approaches:
 - Git 2.10 and newer support specifying private SSH key via the `-c core.sshCommand=ssh -i "{path_to_key}"` command line option
 - Git 2.3 and newer support specifying private SSH key via the `GIT_SSH_COMMAND=ssh -i "{path_to_key}"`environment variable
 - Git 1.0 supports pointing `GIT_SSH` to a wrapper script and specifying SSH options there.

This PR implements the first two approaches and supports git 2.3 and newer. The GitPoller source step will upload the private SSH key when needed, use appropriate `core.sshCommand` config or environment option to specify the key, and delete the key file when done. This way keys can be updated by just changing the secret in the secret provider without changing anything on the master.

A similar approach has been implemented for Git step. See https://github.com/buildbot/buildbot/pull/4160 and https://github.com/buildbot/buildbot/pull/4173.

The private keys are exposed as sshPrivateKey parameter to GitPoller step. The value may be either secret or just a string.

## Contributor Checklist:

* [x] I have updated the unit tests
* [x] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [x] I have updated the appropriate documentation

### CODE REVIEW

**Comment by seankelly** [comment]
I haven't looked through all of the code, but it looks similar to what's in the Git step. I'm fine merging with it duplicated but seems like it would be good to later have a "gitutil" (and probably similar items for Mercurial) that the step and poller can use.

**Comment by p12tic** [comment]
Yeah, I agree wrt. duplication. The reason why I haven't done that yet is that in the Git step everything happens in the worker and in the GitPoller step everything happens on master. So various details are different even though the structure is the same. Deduplicating the "structure" part may make everything much more complex.

**Comment by tardyp** [comment]
the windows tests fail with:

```
[ERROR]
Traceback (most recent call last):
Failure: exceptions.OSError: (2, 'CreateProcess', 'The system cannot find the file specified.')
buildbot.test.integration.test_worker_transition.RunMaster.test_config_0_9_0b5
buildbot.test.integration.test_worker_transition.RunMaster.test_config_0_9_0b5_api_renamed
-------------------------------------------------------------------------------
Ran 5534 tests in 146.685s
FAILED (skips=60, errors=2, successes=5472)
```
does that test use GitPoller?

**Comment by tardyp** [comment]
The test passes on mainline: https://ci.appveyor.com/project/djmitche/buildbot/build/1.0.6592

**Comment by p12tic** [comment]
Turns out the test failure was caused by doing git feature checks in `activate()` function of gitpoller. `activate()` started depending on `git` being installed and this broke the tests that fully start and shutdown the master. I've moved the checks to `poll()` instead and the test should now pass. Bonus is that GitPoller will now pick up newly installed or upgraded git instead of needing a master restart.

**Pull request merged**
