### PR TITLE
Implement missing worker email in the email reporter

### PR DESCRIPTION
**Pull request by tardyp**
This is done via creating a custom event message
which the mail reporter can listen to
note that an irc reporter could also listen to the message and alert accordingly

### CODE REVIEW

**Comment by tardyp** [comment]
@benallard see this fix for the worker missing notification stuff.

Its WIP. I'd like your stuff to land before starting to refactor the code

**Comment by benallard** [comment]
I'd rather have you make another instance of MessageFormatter than make it being able to cope with two different body contents ... But that's probably what you already meant with 'WIP' ...

**Comment by tardyp** [comment]
@benallard please have a look at the updated code

**Comment by sa2ajj** [comment]
:+1:

**Comment by benallard** [comment]
looks good to me.

**Pull request merged**
