### PR TITLE
PY3: paths should be str not bytes (equality)

### PR DESCRIPTION
**Pull request by nazarewk**
Twisted reads paths as bytes (and rightly so), but buildbot codebase
(at least matchers) expect them to be unicode strings and equality
doesn't work between bytes and str

### CODE REVIEW

**Comment by tardyp** [comment]
py3 test fail I am not sure why..

**Comment by nazarewk** [comment]
I'm gonna check it after holidays around 12th-13th, errors are quite cryptic.

**Comment by tardyp** [comment]
would be nice to have this fixed for the next release I want to do next week

**Comment by tardyp** [comment]
I fixed the unit test in your branch and added a relnote

**Pull request merged**
