### PR TITLE
Add support for configuring worker password for DockerLatentWorker via secrets management

### PR DESCRIPTION
**Pull request by anish**
* [X] I have updated the unit tests
* [X] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)
* [X] I have updated the appropriate documentation

### CODE REVIEW

**Comment by anish** [comment]
@p12tic circleci has been stuck on this pr for a few days, any way to rekick it ?

**Comment by p12tic** [comment]
I've updated the PR to support secrets on any kind of worker.

**Comment by p12tic** [comment]
Test failure is an unrelated instability, we can ignore that.

**Comment by p12tic** [comment]
Test failure worked around in https://github.com/buildbot/buildbot/pull/6143.

**Pull request merged**
