### PR TITLE
Do not build universal wheels since python 2 is unsupported.

### LINKED ISSUE #4593: buildbot 2.0.0 wheel is installed in python 2
buildbot 2.0.0 does not support python 2, but it is installed when using python 2. The wheel appears to declare support for py2: `buildbot-2.0.0-py2.py3-none-any.whl`. But the installed code is incompatible with python 2.

```sh-session
[aw@jello server] $ virtualenv /tmp/env
New python executable in /tmp/env/bin/python
Installing setuptools, pip, wheel...
done.
[aw@jello server] $ /tmp/env/bin/pip install buildbot
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting buildbot
  Downloading https://files.pythonhosted.org/packages/36/b7/47a8f7f6dacd3580bc51c04e608a1c85e80e1e3e53141c8c804924065de8/buildbot-2.0.0-py2.py3-none-any.whl (779kB)
    100% |████████████████████████████████| 788kB 6.6MB/s
Collecting txaio>=2.2.2 (from buildbot)
  Using cached https://files.pythonhosted.org/packages/e9/6d/e1a6f7835cde86728e5bb1f577be9b2d7d273fdb33c286e70b087d418ded/txaio-18.8.1-py2.py3-none-any.whl
Collecting Twisted>=17.9.0 (from buildbot)
Collecting autobahn>=0.16.0 (from buildbot)
  Downloading https://files.pythonhosted.org/packages/3d/d9/28aa58047558351eea29dafb8ff813af72e39ac35ade686394ca856914a7/autobahn-19.1.1-py2.py3-none-any.whl (302kB)
    100% |████████████████████████████████| 307kB 8.1MB/s
Collecting future (from buildbot)
Collecting pyyaml (from buildbot)
Collecting PyJWT (from buildbot)
  Using cached https://files.pythonhosted.org/packages/87/8b/6a9f14b5f781697e51259d81657e6048fd31a113229cf346880bb7545565/PyJWT-1.7.1-py2.py3-none-any.whl
Collecting zope.interface>=4.1.1 (from buildbot)
  Using cached https://files.pythonhosted.org/packages/28/39/0b5a168621fadd822810e8f3e2b9502b279aca07d6911ad06495ac9dff97/zope.interface-4.6.0-cp27-cp27m-macosx_10_6_intel.whl
Requirement already satisfied: setuptools>=8.0 in /private/tmp/env/lib/python2.7/site-packages (from buildbot) (40.8.0)
Collecting python-dateutil>=1.5 (from buildbot)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    100% |████████████████████████████████| 235kB 9.8MB/s
Collecting Jinja2>=2.1 (from buildbot)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting sqlalchemy-migrate>=0.9 (from buildbot)
  Downloading https://files.pythonhosted.org/packages/b5/99/92c4c90d5a22aac19554effd04789b78b5549c62fefbda1f42cc549b31b1/sqlalchemy_migrate-0.12.0-py2.py3-none-any.whl (108kB)
    100% |████████████████████████████████| 112kB 11.1MB/s
Collecting sqlalchemy>=1.1.0 (from buildbot)
  Downloading https://files.pythonhosted.org/packages/c6/52/73d1c92944cd294a5b165097038418abb6a235f5956d43d06f97254f73bf/SQLAlchemy-1.2.17.tar.gz (5.7MB)
    100% |████████████████████████████████| 5.7MB 1.4MB/s
Collecting six (from txaio>=2.2.2->buildbot)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting attrs>=17.4.0 (from Twisted>=17.9.0->buildbot)
  Using cached https://files.pythonhosted.org/packages/3a/e1/5f9023cc983f1a628a8c2fd051ad19e76ff7b142a0faf329336f9a62a514/attrs-18.2.0-py2.py3-none-any.whl
Collecting constantly>=15.1 (from Twisted>=17.9.0->buildbot)
  Using cached https://files.pythonhosted.org/packages/b9/65/48c1909d0c0aeae6c10213340ce682db01b48ea900a7d9fce7a7910ff318/constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from Twisted>=17.9.0->buildbot)
  Using cached https://files.pythonhosted.org/packages/f5/1d/c98a587dc06e107115cf4a58b49de20b19222c83d75335a192052af4c4b7/incremental-17.5.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from Twisted>=17.9.0->buildbot)
  Using cached https://files.pythonhosted.org/packages/a7/b6/84d0c863ff81e8e7de87cff3bd8fd8f1054c227ce09af1b679a8b17a9274/hyperlink-18.0.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from Twisted>=17.9.0->buildbot)
  Using cached https://files.pythonhosted.org/packages/a3/86/14c16bb98a5a3542ed8fed5d74fb064a902de3bdd98d6584b34553353c45/Automat-0.7.0-py2.py3-none-any.whl
Collecting PyHamcrest>=1.9.0 (from Twisted>=17.9.0->buildbot)
  Using cached https://files.pythonhosted.org/packages/9a/d5/d37fd731b7d0e91afcc84577edeccf4638b4f9b82f5ffe2f8b62e2ddc609/PyHamcrest-1.9.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.1->buildbot)
  Using cached https://files.pythonhosted.org/packages/cd/52/927263d9cf66a12e05c5caef43ee203bd92355e9a321552d2b8c4aee5f1e/MarkupSafe-1.1.0-cp27-cp27m-macosx_10_6_intel.whl
Collecting pbr>=1.8 (from sqlalchemy-migrate>=0.9->buildbot)
  Downloading https://files.pythonhosted.org/packages/8c/7f/fed53b379500fd889707d1f6e61c2a35e12f2de87396894aff89b017d1d6/pbr-5.1.2-py2.py3-none-any.whl (107kB)
    100% |████████████████████████████████| 112kB 9.6MB/s
Collecting sqlparse (from sqlalchemy-migrate>=0.9->buildbot)
  Using cached https://files.pythonhosted.org/packages/65/85/20bdd72f4537cf2c4d5d005368d502b2f464ede22982e724a82c86268eda/sqlparse-0.2.4-py2.py3-none-any.whl
Collecting Tempita>=0.4 (from sqlalchemy-migrate>=0.9->buildbot)
Collecting decorator (from sqlalchemy-migrate>=0.9->buildbot)
  Downloading https://files.pythonhosted.org/packages/f1/cd/7c8240007e9716b14679bc217a1baefa4432aa30394f7e2ec40a52b1a708/decorator-4.3.2-py2.py3-none-any.whl
Collecting idna>=2.5 (from hyperlink>=17.1.1->Twisted>=17.9.0->buildbot)
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
    100% |████████████████████████████████| 61kB 7.5MB/s
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py) ... done
  Stored in directory: /Users/aw/Library/Caches/pip/wheels/b3/94/e4/e556159f8d26575bfa3cf64cff277b9112f1ad8a50cc438bbb
Successfully built sqlalchemy
Installing collected packages: six, txaio, attrs, constantly, incremental, idna, hyperlink, Automat, zope.interface, PyHamcrest, Twisted, autobahn, future, pyyaml, PyJWT, python-dateutil, MarkupSafe, Jinja2, sqlalchemy, pbr, sqlparse, Tempita, decorator, sqlalchemy-migrate, buildbot
Successfully installed Automat-0.7.0 Jinja2-2.10 MarkupSafe-1.1.0 PyHamcrest-1.9.0 PyJWT-1.7.1 Tempita-0.5.2 Twisted-18.9.0 attrs-18.2.0 autobahn-19.1.1 buildbot-2.0.0 constantly-15.1.0 decorator-4.3.2 future-0.17.1 hyperlink-18.0.0 idna-2.8 incremental-17.5.0 pbr-5.1.2 python-dateutil-2.8.0 pyyaml-3.13 six-1.12.0 sqlalchemy-1.2.17 sqlalchemy-migrate-0.12.0 sqlparse-0.2.4 txaio-18.8.1 zope.interface-4.6.0

[aw@jello server] $ /tmp/env/bin/buildbot
Traceback (most recent call last):
  File "/tmp/env/bin/buildbot", line 6, in <module>
    from buildbot.scripts.runner import run
  File "/tmp/env/lib/python2.7/site-packages/buildbot/scripts/runner.py", line 31, in <module>
    from buildbot.scripts import base
  File "/tmp/env/lib/python2.7/site-packages/buildbot/scripts/base.py", line 37
    return 1
SyntaxError: 'return' with argument inside generator
```

### PR DESCRIPTION
**Pull request by rectalogic**
Fixes #4593

## Contributor Checklist:

* [x] I have updated the unit tests
* [x] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [x] I have updated the appropriate documentation

### CODE REVIEW

**Comment by tardyp** [comment]
thanks! I have that fix too in #4594

**Comment by rectalogic** [comment]
> thanks! I have that fix too in #4594

@tardyp Hmm, but since the broken wheels have already been published to PyPI - will the existing 2.0.0 wheels be replaced or will this be a 2.0.1 version?

And if 2.0.1, then won't python2 "pip install buildbot" still grab the latest supported release which would be the broken 2.0.0?

**Comment by tardyp** [comment]
Indeed, I will remove release 2.0.0 from pypi once 2.0.1 is released

**Comment by tardyp** [comment]
rebased your branch to still keep relevent hunks of your patch

**Pull request merged**
