### PR TITLE
Allow self.master to be set so it can be used before service setup.

### PR DESCRIPTION
**Pull request by djmitche**
This also addresses a few testing issues, caches the master property,
and invalidates the cache on disownServiceParent.  Fixes #3329.

### CODE REVIEW

**Comment by yetanotherion** [comment]
unit tests seem to fail, :+1: besides that

**Comment by djmitche** [comment]
Actually it looks like that's a problem with Autobahn and Twisted-{11,12}?
```
Traceback (most recent call last):

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/twisted/trial/runner.py", line 556, in loadPackage

    module = modinfo.load()

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/twisted/python/modules.py", line 383, in load

    return self.pathEntry.pythonPath.moduleLoader(self.name)

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/twisted/python/reflect.py", line 506, in namedAny

    topLevelPackage = _importAndCheckStack(trialname)

  File "/home/travis/build/buildbot/buildbot/master/buildbot/test/integration/test_www.py", line 25, in <module>

    from buildbot.www import service as wwwservice

  File "/home/travis/build/buildbot/buildbot/master/buildbot/www/service.py", line 26, in <module>

    from buildbot.www import ws

  File "/home/travis/build/buildbot/buildbot/master/buildbot/www/ws.py", line 21, in <module>

    from autobahn.twisted.resource import WebSocketResource

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/autobahn/twisted/resource.py", line 37, in <module>

    from twisted.python.compat import _PY3

exceptions.ImportError: cannot import name _PY3
```
@jvlomax have you seen this in your travels?

**Comment by tardyp** [comment]
I think it is better for long term to go for what I'm doing in #1807

Having the unit tests properly setup the service hierarchy looks saner to me.
Obviously its much more painful.

**Comment by tardyp** [comment]
I am not against merging it though to unblock the situation

**Comment by jvlomax** [comment]
@djmitche I have not come across that before. The only way I can see that error happening is if it uses an old version of twisted, because ```from twisted.python.compat import _PY3``` is [definitely there](https://github.com/twisted/twisted/blob/trunk/twisted/python/compat.py#L37) and has been for a little while now

**Comment by tardyp** [comment]
@jvlomax @djmitche Tavendo guys have fixed the issues, and will probably issue a fix release soon.

**Comment by djmitche** [comment]
(Tavendo writes Autobah, for the record).  I've added a version requirement for Autobahn, although #1807 seems to have passed Travis without any trouble, so maybe that's no longer required?

If #1807 is done and functional, it's the better solution.  My attempts to do so failed, since lots of things seemed to want `self.master` set during the constructor run.  I'll leave it to someone else to pick a solution :)

We should really stop hacking while on vacation!

**Comment by tardyp** [comment]
closing, as obsoleted by #1807

**Pull request closed without merging**
