### PR TITLE
Fix Robocopy 'verbose' option and add tests

### PR DESCRIPTION
**Pull request by shoelzer**

### CODE REVIEW

**Comment by shoelzer** [comment]
I don't know why this failed or how to make it pass. Help?

**Comment by noc0lour** [comment]
Looks like this is a bug in codecov or something?

**Comment by tardyp** [comment]
The verbose option is not unit tested. hence 0% of diff hit (this patch is only changing the verbose option)

please add a test here
https://github.com/buildbot/buildbot/blob/master/master/buildbot/test/unit/test_steps_mswin.py#L67

**Comment by shoelzer** [comment]
@tardyp Thanks! Passing now.

**Comment by tardyp** [comment]
cool! Can you add a release note?
https://github.com/buildbot/buildbot/blob/master/master/buildbot/newsfragments/README.txt#L1

**Comment by shoelzer** [comment]
@tardyp Now has a release note. Anything else?

**Comment by tardyp** [comment]
thanks @shoelzer

**Pull request merged**
