### PR TITLE
Declared class parameter "master" in StatusPush to prevent exception

### PR DESCRIPTION
**Pull request by cato-**

### CODE REVIEW

**Comment by tardyp** [comment]
what is the exception? self.master is automatically set now, so we should not set it in the code.

**Comment by cato-** [comment]
```
2015-09-22 18:13:20+0200 [-] while starting BuildMaster
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1155, in gotResult
            _inlineCallbacks(r, g, deferred)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/buildbot/util/service.py", line 45, in reconfigServiceWithBuildbotConfig
            yield svc.reconfigServiceWithBuildbotConfig(new_config)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1237, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/lib/python2.7/dist-packages/buildbot/status/master.py", line 88, in reconfigServiceWithBuildbotConfig
            sr.master = self.master
        exceptions.AttributeError: can't set attribute
```
Installed version (although this parts did not differ):
```
buildbot@build:~$ buildbot --version
Buildbot version: 0.9.0b2
Twisted version: 14.0.2
```

**Comment by sa2ajj** [comment]
Then this fix is wrong, sorry: it must be fixed where the assignment takes place.

**Comment by djmitche** [comment]
I believe this has been fixed in the latest versions.  Can you verify?

**Pull request closed without merging**
