### PR TITLE
doc: import reporter

### PR DESCRIPTION
**Pull request by gracinet**
noticed by someone on the IRC channel

### CODE REVIEW

**Comment by rutsky** [comment]
LGTM.

@gracinet can you please include fix for this line too?
https://github.com/buildbot/buildbot/blame/master/master/docs/manual/installation/nine-upgrade.rst#L118
```
* :bb:reporter:`MailNotifier` argument ``messageFormatter`` should now be a :py:class:`buildbot.reporter.message.MessageFormatter`, due to the removal of the status classes (see above), such formatters must be re-implemented using the Data API.
```

**Comment by gracinet** [comment]
@rutsky damn, you have a wider grep than me !
done (and I squashed the commits)

**Comment by rutsky** [comment]
Speaking of grep:

```
$ git grep 'reporter\.'
master/buildbot/process/build.py:        # FIXME: kill this. This belongs to reporter.utils
master/buildbot/steps/python_twisted.py:        # the bwverbose reporter.
master/buildbot/test/unit/test_test_util_gpo.py:        result = reporter.TestResult()
master/contrib/SimpleConfig.py:from buildbot.reporter.mail import MailNotifier
```

first and last entires should be fixed :)

**Comment by rutsky** [comment]
@sa2ajj, have you addressed my last comment before merging this PR?

**Comment by sa2ajj** [comment]
@rutsky oops, i did not :(  sorry

**Comment by gracinet** [comment]
aww gosh, I saw @rutsky comment and repushed before I saw the merge
btw SimpleConfig should be updated to use plugins imports

**Pull request merged**
