### PR TITLE
Initial creation of logentries status plugin

### PR DESCRIPTION
**Pull request by jcftang**
This is a first attempt at creating a logentries status plugin.

This takes the build started and finished events and just sends them to logentries.

### CODE REVIEW

**Comment by rutsky** [comment]
If you use Buildbot >= 0.8.11 you can convert your module to proper Python package and use it as an actual Buildbot plugin. See http://docs.buildbot.net/0.8.12/manual/plugins.html.

Your status receiver service is blocking, so your master will be blocked until all data is sent to the logentries server, which may break other Buildbot async services.
You need to use Twisted async API for network I/O to send data.

**Comment by jcftang** [comment]
Ok, that sounds like I should packing it up as a python package for easier use/distribution.

I currently don't have any experience with twisted's API, so I won't likely be reworking any time soon. The blocking behaviour works for me as the volume of builds that I have is relatively low.

I'll close this PR for now.

**Comment by jcftang** [comment]
Just for the record -- https://pypi.python.org/pypi/buildbot_status_logentries

I ended up making a python package and it now is a bit more twisted friendly in the way that it works

**Comment by rutsky** [comment]
Thanks @jcftang!

I think your plugin may be added to the list of Buildbot plugins.
@djmitche do we have list of Buildbot plugins? :)
Perhaps create page in the Trac Wiki with list of them?
(I don't think including dynamically changed list in the Buildbot docs is a good idea.)

**Comment by djmitche** [comment]
That's great!  Yes, let's add a wiki page, and point to it from the documentation.

**Comment by djmitche** [comment]
http://trac.buildbot.net/ticket/3406

**Comment by jcftang** [comment]
I've yet to split out the plugin into its own little repo, I'll probably split it out later today and put it somewhere on github.

**Comment by djmitche** [comment]
http://trac.buildbot.net/wiki/Plugins

**Pull request closed without merging**
