### PR TITLE
hooks: accept unicode in PR comments

### PR DESCRIPTION
**Pull request by noc0lour**
convert string in format to unicode so unicode characters in PR comments are handled properly and don't generate a silent error

### CODE REVIEW

**Comment by seankelly** [comment]
Reminds me of #3144.

**Comment by noc0lour** [comment]
From what I've read having a unicode string and doing format with an ASCII string on it is ok. The other way around it will throw an error.

**Comment by seankelly** [comment]
@noc0lour Yep. #3078 was opened about that issue, but for the author. Are there any other strings that are formatted?

**Comment by noc0lour** [comment]
I thought about changing all strings who use format to unicode but this might bring harm in other places.  No idea why the unit test fails @rodrigc . There was some thing about lz4 in another issue though.

**Comment by tardyp** [comment]
lz4 issue is due to the new lz4 package I am working on it with #3200

**Comment by rodrigc** [comment]
@noc0lour in future, as long as you can get things to work, I think it is OK to try to convert all strings  to unicode.  This will give consistent behavior between Python 2 and 3, since by default on Python 3 strings are unicode.

For my initial Python 3 work, I only converted enough strings to unicode to get the unit tests to pass.  That's not to say that more can be done.

**Comment by noc0lour** [comment]
K, I'll look for strings with format and try to convert them to unicode mostly... Most important are strings with user input.

**Comment by rodrigc** [comment]
@noc0lour Take a look at https://mail.python.org/pipermail/python-dev/2017-May/147949.html for interesting reading about this.

I think converting all instances of:

```
"foobar {}".format(whatever)
```

to:

```
u"foobar {}".format(whatever)
```

Is the best way to go.

**Comment by noc0lour** [comment]
I agree. Yesterday I just was too lazy to come up with a regex which will safely match all cases ;)

**Comment by tardyp** [comment]
actually, we need this PR to be merged in order to have pyup working..
pyup puts smileys in its PRs, so they wont be accepted by nine.bb.net :-)

**Comment by noc0lour** [comment]
If you want you can already merge this small change, and I come up with a way to change other strings. I already use this commit in https://ci.gnuradio.org/buildbot/

**Pull request merged**
