### PR TITLE
Work-around exception

### LINKED ISSUE #5190: Gerrit Change Event Monitor: assertion error: codebase cannot be None
I am getting this stacktrace in the log, with Buildbot 2.6.0 . I do not see this problem with Buildbot 2.5.1 .

2020-02-05 09:11:59-0500 [-] Unhandled Error
        Traceback (most recent call last):
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/buildbot/changes/gerritchangesource.py", line 180, in addChange
            self.master.db.sourcestamps.findOrCreateId(**stampdict))
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
            return _cancellableInlineCallbacks(gen)
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
            _inlineCallbacks(None, g, status)
        --- <exception caught here> ---
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/buildbot/changes/gerritchangesource.py", line 343, in outReceived
            yield self.change_source.lineReceived(line)
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/buildbot/changes/gerritchangesource.py", line 253, in addChangeFromEvent
            'properties': properties})
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/buildbot/changes/gerritchangesource.py", line 180, in addChange
            self.master.db.sourcestamps.findOrCreateId(**stampdict))
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
            result = g.send(result)
          File "/home/buildbot/build-venv/lib/python3.6/site-packages/buildbot/db/sourcestamps.py", line 58, in findOrCreateId
            assert codebase is not None, "codebase cannot be None"
        builtins.AssertionError: codebase cannot be None

### PR DESCRIPTION
**Pull request by 0x8000-0000**
This fixes #5190

### CODE REVIEW

**Comment by tardyp** [comment]
Thanks for working on it.
We usually ask contributors to send a unit test that reproduce the problem they are trying to fix.
Can you please work on it?

Also we need a release note.

I am fine with simple fix to hardcode the codebase, if somebody needs to support multicodebase with gerrit, they will have to implement a followup patch (this will probably require a bit more work)

**Comment by 0x8000-0000** [comment]
> Thanks for working on it.
> We usually ask contributors to send a unit test that reproduce the problem they are trying to fix.
> Can you please work on it?
> 
> Also we need a release note.
> 
> I am fine with simple fix to hardcode the codebase, if somebody needs to support multicodebase with gerrit, they will have to implement a followup patch (this will probably require a bit more work)

Hi Pierre,

Thanks for taking a look at this. I could add a test case, but this fix should be pushed in the caller somewhere, because the documentation clearly states that a codebase is optional, and if one is not specified then '' is used. If the code is defaulting to None and then asserting it got something other than None, then the call site(s) should be fixed. I have a configuration with works with 2.3.1 -> 2.5.0 and then fails with 2.6.0 and 2.7.0 .

I must confess I have tried to follow this code but I am wholly unfamiliar with the reactive/threaded implementation pattern of many callbacks all yielding and sending small bits of data around so I don't want to make more of a mess.

This tiny change is a big, fat, ugly bandaid - it should not be committed as such. It is more of a cry for help.

**Comment by tardyp** [comment]
Hi,
Can you point me where you find in the doc that codebase is optional?
This might be true in the config, but not in the internal apis.

**Comment by 0x8000-0000** [comment]
> Hi,
> Can you point me where you find in the doc that codebase is optional?
> This might be true in the config, but not in the internal apis.

This is what I find relevant, there might be more:

master/docs/manual/configuration/schedulers.rst:140:``codebases`` (optional)

master/docs/manual/configuration/buildsteps.rst:276:    The default codebase value is ``''``.
master/docs/manual/configuration/buildsteps.rst:278:    If there is no codebaseGenerator defined in the master then codebase doesn't need to be set, the default value will then match all changes.

master/docs/manual/configuration/changesources.rst:1513:By default the codebase is ''; this value is used automatically for single-codebase configurations.


Also, the default values for codebase parameters seem to be equally split between '' and None:

$ ag -c "codebase=''" master
master/buildbot/changes/changes.py:1
master/buildbot/db/changes.py:1
master/buildbot/process/build.py:1
master/buildbot/process/properties.py:1
master/buildbot/schedulers/trysched.py:2
master/buildbot/steps/source/base.py:1
master/buildbot/test/fake/fakedb.py:3
master/buildbot/schedulers/forcesched.py:2
master/buildbot/test/unit/test_data_changes.py:3
master/buildbot/test/unit/test_db_changes.py:4
master/buildbot/test/unit/test_schedulers_forcesched.py:2
master/buildbot/test/unit/test_schedulers_trysched.py:5
master/buildbot/test/unit/test_steps_trigger.py:8
master/docs/manual/configuration/schedulers.rst:1
$ ag -c "codebase=None" master
master/buildbot/changes/filter.py:1
master/buildbot/clients/sendchange.py:1
master/buildbot/data/changes.py:1
master/buildbot/db/sourcestamps.py:2
master/buildbot/spec/types/change.raml:1
master/buildbot/steps/source/repo.py:1
master/buildbot/test/fake/fakedata.py:1
master/buildbot/test/fake/fakedb.py:2
master/buildbot/test/unit/test_data_changes.py:1
master/buildbot/test/unit/test_data_connector.py:1
master/buildbot/test/unit/test_db_sourcestamps.py:1
master/buildbot/test/unit/test_steps_source_git.py:1
master/buildbot/test/unit/test_www_hooks_gitlab.py:3
master/buildbot/www/hooks/gitlab.py:2
master/buildbot/www/hooks/github.py:1

There is a single definition for default codebase in 

master/buildbot/schedulers/base.py:32:    DEFAULT_CODEBASES = {'': {}}

But everybody else just hardcodes ''.

**Comment by tardyp** [comment]
So indeed, this is at user api level (not internal api)
So this is up to the user layer to make the default. We verify in the middleware that the job is correctly done, so this make sense.

Whether it is a good design, indeed I am not sure, it would also make sense to default at the lower layer.
This design as the benefit to let us know that gerrit changesource is not prepared for codebase, and there is no way to actually specify it or calculate it from the event's project url.

So I'd say your solution is fine.

**Comment by 0x8000-0000** [comment]
> This design as the benefit to let us know that gerrit changesource is not prepared for codebase, and there is no way to actually specify it or calculate it from the event's project url.
> 
> So I'd say your solution is fine.

This probably explains why I could not get Gerrit change source to work even when going through my whole config and annotating it with codebase. ForceScheduler respected the codebase, but AnyBranchScheduler with GerritChangeFilter would not react to any new commits in Gerrit.

OK - In this case I will add release notes and reword the commit message. But I am still unsure how to think about a test case for this. In theory the current set of test cases should have failed already.

**Comment by 0x8000-0000** [comment]
This is still needed. I don't know how to add tests - it crashes in my environment without this fix.

**Comment by flokli** [comment]
@tardyp I can also confirm that Buildbot with Gerrit Event Log Poller crashes when trying to process events:

```
Jun 11 20:56:30 localhost twistd[1326]: 	Traceback (most recent call last):
Jun 11 20:56:30 localhost twistd[1326]: 	  File "/nix/store/5ka22fgqf7lf2bnfk63cvblmi9g4mri1-python3-3.7.7-env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Jun 11 20:56:30 localhost twistd[1326]: 	    result = g.send(result)
Jun 11 20:56:30 localhost twistd[1326]: 	  File "/nix/store/5ka22fgqf7lf2bnfk63cvblmi9g4mri1-python3-3.7.7-env/lib/python3.7/site-packages/buildbot/changes/gerritchangesource.py", line 177, in addChange
Jun 11 20:56:30 localhost twistd[1326]: 	    self.master.db.sourcestamps.findOrCreateId(**stampdict))
Jun 11 20:56:30 localhost twistd[1326]: 	  File "/nix/store/5ka22fgqf7lf2bnfk63cvblmi9g4mri1-python3-3.7.7-env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
Jun 11 20:56:30 localhost twistd[1326]: 	    return _cancellableInlineCallbacks(gen)
Jun 11 20:56:30 localhost twistd[1326]: 	  File "/nix/store/5ka22fgqf7lf2bnfk63cvblmi9g4mri1-python3-3.7.7-env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
Jun 11 20:56:30 localhost twistd[1326]: 	    _inlineCallbacks(None, g, status)
Jun 11 20:56:30 localhost twistd[1326]: 	--- <exception caught here> ---
Jun 11 20:56:30 localhost twistd[1326]: 	  File "/nix/store/5ka22fgqf7lf2bnfk63cvblmi9g4mri1-python3-3.7.7-env/lib/python3.7/site-packages/buildbot/changes/gerritchangesource.py", line 496, in poll
Jun 11 20:56:30 localhost twistd[1326]: 	    yield self.lineReceived(line)
Jun 11 20:56:30 localhost twistd[1326]: 	  File "/nix/store/5ka22fgqf7lf2bnfk63cvblmi9g4mri1-python3-3.7.7-env/lib/python3.7/site-packages/buildbot/changes/gerritchangesource.py", line 500, in eventReceived
Jun 11 20:56:30 localhost twistd[1326]: 	    res = yield super().eventReceived(event)
Jun 11 20:56:30 localhost twistd[1326]: 	  File "/nix/store/5ka22fgqf7lf2bnfk63cvblmi9g4mri1-python3-3.7.7-env/lib/python3.7/site-packages/buildbot/changes/gerritchangesource.py", line 177, in addChange
Jun 11 20:56:30 localhost twistd[1326]: 	    self.master.db.sourcestamps.findOrCreateId(**stampdict))
Jun 11 20:56:30 localhost twistd[1326]: 	  File "/nix/store/5ka22fgqf7lf2bnfk63cvblmi9g4mri1-python3-3.7.7-env/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Jun 11 20:56:30 localhost twistd[1326]: 	    result = g.send(result)
Jun 11 20:56:30 localhost twistd[1326]: 	  File "/nix/store/5ka22fgqf7lf2bnfk63cvblmi9g4mri1-python3-3.7.7-env/lib/python3.7/site-packages/buildbot/db/sourcestamps.py", line 58, in findOrCreateId
Jun 11 20:56:30 localhost twistd[1326]: 	    assert codebase is not None, "codebase cannot be None"
Jun 11 20:56:30 localhost twistd[1326]: 	builtins.AssertionError: codebase cannot be None
```

Adding this patch fixes it for me - and according to [the issue](https://github.com/buildbot/buildbot/issues/5190#issuecomment-636199124), for @meffie as well.

What's needed for this to get merged?

**Comment by flokli** [comment]
This is still relevant. @tardyp, what's needed on this?

**Comment by p12tic** [comment]
@0x8000-0000 @flokli Thanks for pinging again. This looks good. 

To make sure unit tests cover this I've copied the asserts that we use in real DB component to the fake one.

**Pull request merged**
