### PR TITLE
remove deferredGenerators

### PR DESCRIPTION
**Pull request by tardyp**
twisted 15 is giving annoying deprecated messages on those

fix some pylint issues on that file too.

### CODE REVIEW

**Comment by sa2ajj** [comment]
LGTM

**Comment by jaredgrubb** [comment]
LGTM!

**Comment by djmitche** [comment]
This means that the slave is no longer Python-2.4 compatible.  That's fine -- in fact, we've made some other changes that have dropped that support (see [the logs](http://buildbot.buildbot.net/builders/py24-tw0810-slave/builds/36/steps/virtualenv%20setup/logs/stdio)).

**Comment by djmitche** [comment]
I do see that at least Twisted-9.0.0 supports inlineCallbacks.  8.2.0's not on pypi anymore so I'm not sure there.

**Pull request merged**
