### PR TITLE
bitbucket_build_status_reporter: adding basic authentication to Bitbu…

### PR DESCRIPTION
**Pull request by sjalloq**
…cket reporter

 - the BitbucketStatusPush class only had support for OAuth authentication with the
   Bitbucket API server.  This change adds support for App Passwords using the
   (username,password) tuple.

## Contributor Checklist:

* [x] I have updated the unit tests
* [ ] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by sjalloq** [comment]
I've not updated any tests for this PR yet but wanted to get some feedback.  I'm not sure if this is the right way to add support for a secondary auth method.  Let me know what you think.

**Comment by sjalloq** [comment]
@p12tic Do you have any input on this?  I'm not sure of the cleanest way to add multiple auth options.

**Comment by p12tic** [comment]
@sjalloq: I'm sorry for not getting back to you. I somehow thought this depended on my httpclientservice changes and it turned out that this PR is for completely different functionality.

I think the approach makes sense. In the future it would make sense to make oauth arguments optional, but for this is out of scope of this PR.

**Comment by p12tic** [comment]
I think we can leave it without test.

**Comment by sjalloq** [comment]
@p12tic OK, I've merged the latest master into my branch but it looks like the CI tests are still expecting the old bitbucket URL.  Is that something that is fixed when you merge the change to using httpclientservice?

**Comment by sjalloq** [comment]
@p12tic Seems like the `unit.reporters.test_bitbucket` tests were failing due to the `auth` field being passed to the `self._http` method.  Think I've fixed all issues now.

**Comment by sjalloq** [comment]
@p12tic Anything else I need to do to get this ready to merge?

**Comment by p12tic** [comment]
@sjalloq Sorry about forgetting this PR. I'll merge it today.

**Comment by p12tic** [comment]
Rebased on top of latest master, added documentation and slightly improved API of `BitbucketStatusPush`: oauth_key and  oauth_secret now become keyword arguments with default values of `None`.

**Comment by shareefj** [comment]
@p12tic Thanks for all this. No worries on the delay. :-)

**Pull request merged**
