### PR TITLE
Replace xrange() with range() for Python 3 compatibility

### PR DESCRIPTION
**Pull request by rodrigc**
xrange() is gone in Python 3.
In Python 3, range() returns a view, not a list,
so in a few places where we really need a list, we
need to wrap it with list().

See:
http://python3porting.com/differences.html#range-and-xrange

### CODE REVIEW

**Comment by tardyp** [comment]
but xrange is an iterator in py2 so we need to make sure the code where xrange is used does not use a list in place (and use huge memory for nothing)

I think future as something to deal with that. (we are using future as a compat library)

**Comment by rodrigc** [comment]
@tardyp I reworked this.

**Comment by tardyp** [comment]
it needs rebase after merge of the other branch :-}

**Comment by rodrigc** [comment]
OK, I rebased.

**Pull request merged**
