### PR TITLE
Use buildbot-worker for local worker

### PR DESCRIPTION
**Pull request by rutsky**

### CODE REVIEW

**Comment by tomprince** [comment]
https://github.com/buildbot/buildbot/pull/2174 introduces a new referrer.

**Comment by tardyp** [comment]
as #2174 was first, I'll land it first

**Comment by tardyp** [comment]
I merged #2174 please rebase

**Comment by rutsky** [comment]
Rebased.

**Comment by tomprince** [comment]
`master/buildbot/test/integration/test_latent.py` still refers to the slave.

**Comment by rutsky** [comment]
@tomprince where?

I added test configuration that runs tests in env without `buildbot-slave` and it works.
Plus I don't see use of local worker in `master/buildbot/test/integration/test_latent.py`.

**Pull request merged**
