### PR TITLE
EC2 latent slave bug fixes

### PR DESCRIPTION
**Pull request by apilloud**
Few improvements to the EC2 latent slave code. Will backport 2-4 to eight once this is merged.

1. Fix EC2 latent slaves, which are broken on master due to missing imports.
2. Plumb through the instance_profile_arn parameter, which allows the slave instance to be delegated AWS credentials.
3. Handle AWS eventual consistency. EC2 may return not found for a short period of time after a resource is created.
4. Add tags to spot instances, tag resources as soon as possible, and do so in an eventual consistency safe manner.

### CODE REVIEW

**Comment by tardyp** [comment]
I would appreciate some unit tests that makes us more confident to detect  future missing import breakage.

**Comment by apilloud** [comment]
I've made some changes that should have the existing tests working on travis. Unfortunately the mock API fixes the import problem, so that makes it difficult to test without testing against the real APIs.

```
>>> import boto
>>> boto.ec2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'ec2'
>>> import moto
>>> boto.ec2
<module 'boto.ec2' from '/usr/local/lib/python2.7/dist-packages/boto/ec2/__init__.pyc'>
```

**Comment by tardyp** [comment]
@apilloud will you have time to finish this? Please note that there is a mozilla bounty for enhancing latent slave support

**Pull request closed without merging**
