### PR TITLE
forcescheduler: add parameter tooltip to every field

### PR DESCRIPTION
**Pull request by mifo123**
Added parameter, if set, is visibile next to fields of forcescheduler with questionmark icon (on hover).

## Contributor Checklist:
* [x] I have updated the unit tests
* [x] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [x] I have updated the appropriate documentation

### CODE REVIEW

**Review by p12tic — APPROVED** [review]
Looks great, thanks!

**Comment by p12tic** [comment]
@mifo123 Could you add a screenshot how the tooltip looks like?

**Comment by mifo123** [comment]
> @mifo123 Could you add a screenshot how the tooltip looks like?

image

**Comment by p12tic** [comment]
Thanks

**Pull request merged**
