### PR TITLE
Cascade stop

### PR DESCRIPTION
**Pull request by tardyp**
A long running request from users, when having a process heavily using
Trigger steps, is to be able to cascade stopping the builds

There are 2 cases here:
- Either the buildrequest is pending:
  then we simply cancel the buildrequest
- Or the builds are already started,
  then, we cancel the builds if possible (i.e on the same master)

This stuff definitively would need unit tests.

Doing early pull request to get first feedback on whether I'm doing something sane.

### CODE REVIEW

**Comment by gtmacdonald** [comment]
For those like myself that need to have this implemented and can't wait for Nine; I was able to drop in this code into 0.8.12, without too much trouble. Mind the return in stopTriggeredBuilds; it needs to be out a few scopes or only one triggered build will stop. And if the properties stuff gets hairy with your version (like it did for me) you can always set the two properties needed directly. The db code worked as is for me.

Thx @tardyp this would've taken me much longer to get going. :)

**Comment by jaredgrubb** [comment]
Could you possibly offer the patch as a pull request? I'd love to see it :)

**Comment by sa2ajj** [comment]
Interesting, I also implemented stop/cancel builds in eight :)  (GH-1686)  What's missing in that?

**Comment by tardyp** [comment]
@sa2ajj What you implemented is different from what is needed here.

Here this is more about the trigger step which shall interrupt the triggered buildrequest when it is itself interrupted.

**Pull request closed without merging**
