### PR TITLE
Select distinct buildermasterid's to save duplication

### LINKED ISSUE #3472: tried to complete 1 buildrequests, but only completed 0
This happens when **3** changes comes at a time. The first one got handled perfectly. Problem is the 2nd and 3rd change when the 2nd change was merged to 3rd and a `NotClaimedError` was raised. I use Perforce as CVS.
and log is:
```
2017-07-26 11:39:39+0800 [-] added change with revision 98 to database
2017-07-26 11:39:59+0800 [-] added buildset 324 to database
2017-07-26 11:39:59+0800 [-] added change with revision 99 to database
2017-07-26 11:40:19+0800 [-] starting build <Build runtests number:None results:success> using worker <WorkerForBuilder builder=u'runtests' worker=u'example-worker' state=AVAILABLE>
2017-07-26 11:40:19+0800 [-] <Build runtests number:None results:success>.startBuild
2017-07-26 11:40:21+0800 [-] added buildset 325 to database
2017-07-26 11:40:22+0800 [-] acquireLocks(worker <Worker u'example-worker'>, locks [])
2017-07-26 11:40:22+0800 [-] starting build <Build runtests number:295 results:success>.. pinging the worker <WorkerForBuilder builder=u'runtests' worker=u'example-worker' state=BUILDING>
2017-07-26 11:40:22+0800 [-] sending ping
2017-07-26 11:40:22+0800 [Broker,0,127.0.0.1] ping finished: success
// Blabla...OMIT a lot P4 sync command
2017-07-26 11:40:28+0800 [-]  step 'p4' complete: success (None)
2017-07-26 11:40:28+0800 [-]  <Build runtests number:295 results:success>: build finished
2017-07-26 11:40:28+0800 [-] releaseLocks(<Worker u'example-worker'>): []
2017-07-26 11:40:29+0800 [-] tried to complete 1 buildrequests, but only completed 0
2017-07-26 11:40:29+0800 [-] Got fatal Exception on DB
	Traceback (most recent call last):
	Failure: buildbot.db.buildrequests.NotClaimedError: 
```

### PR DESCRIPTION
**Pull request by djmitche**
Fixes #3472.

### CODE REVIEW

**Comment by tardyp** [comment]
I am trying to reproduce with your unit test, but even if I set range (10000), the test executes fine without the fix

**Comment by tardyp** [comment]
For me the fix is not enough for this class of bug. see this commit with a new test:

https://github.com/tardyp/buildbot/commit/d99ec667150b893f922c7e4577531985c33814ce

I think we should make a similar fix as
http://trac.buildbot.net/ticket/2299

I got to run now, I can do it later, or you can finish it as you wish :)

**Comment by djmitche** [comment]
I see: my fix addressed one bulk delete, but there's another one :)

**Comment by djmitche** [comment]
OK, pulled your change and added batching..

**Comment by tardyp** [comment]
👍

**Comment by tardyp** [comment]
I think we should document this class of bug, and add some utils to resolve it the same way. buildrequests resolves it with itertool, you do with explicit split, and there is this thousand hardcoded

**Comment by tardyp** [comment]
merging, to fix it in another PR

**Comment by tardyp** [comment]
but.. the tests fail on pg..

**Comment by tardyp** [comment]
I'll close via #2024

**Pull request closed without merging**
