### PR TITLE
fix all remaining type errors except in unit tests [part 8]

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by Mic92** [comment]
If the rest of the CI also goes green, I believe this is ready for review: @p12tic

**Comment by p12tic** [comment]
@Mic92 Thanks a lot!

**Comment by p12tic** [comment]
Oh, I noticed that this PR changes the worker. I think let's hold off from that because worker should support old Python versions as well. This wasn't tested in tests and is currently broken unfortunately.

**Comment by p12tic** [comment]
Looks like worker works on old python as well, great.

**Comment by Mic92** [comment]
To avoid regressions, we should have a different pyproject.toml with a different minimum python version.

**Comment by p12tic** [comment]
> To avoid regressions, we should have a different pyproject.toml with a different minimum python version for the worker code.

Good idea, thanks.

**Comment by p12tic** [comment]
I will delay this PR a bit until I release 4.1.0 today or tomorrow.

**Comment by p12tic** [comment]
I removed the `ruff: enable flake8-future-annotations (FA) rules` commit because I think we should attribute it to @tdesveaux and merge his PR instead. I will make sure the merged PR contains combination of whatever I removed and what's in #8117.

**Pull request merged**
