### PR TITLE
Configure AppVeyor CI to run Buildbot tests on Windows

### PR DESCRIPTION
**Pull request by rutsky**
In general tests are working on Windows: only few tests fails, looks like due to "slash vs backslash" issues on Windows: https://ci.appveyor.com/project/rutsky/buildbot/build/1.0.10

### CODE REVIEW

**Comment by tardyp** [comment]
:+1:

**Comment by rutsky** [comment]
@djmitche can you enable AppVeyor for GitHub? More, more CI! :)

**Comment by djmitche** [comment]
Done

**Comment by tardyp** [comment]
looks like there are still some tests that fail

**Comment by rutsky** [comment]
@tardyp Yes, its WIP. At this moment five tests fails: https://ci.appveyor.com/project/rutsky/buildbot/build/1.0.27

```
=============================================================================== 
[ERROR] 
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "c:\projects\buildbot\master\buildbot\test\unit\test_scripts_cleanupdb.py", line 128, in test_cleanup
    res = yield cleanupdb._cleanupDatabase(mkconfig(basedir='basedir'))
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "c:\projects\buildbot\master\buildbot\scripts\cleanupdb.py", line 96, in _cleanupDatabase
    yield doCleanupDatabase(config, master_cfg)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "c:\projects\buildbot\master\buildbot\scripts\cleanupdb.py", line 40, in doCleanupDatabase
    res = yield db.logs.getLogs()
  File "C:\Python27\lib\site-packages\twisted\python\threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "C:\Python27\lib\site-packages\twisted\python\threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\python\context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "c:\projects\buildbot\master\buildbot\db\pool.py", line 186, in __thd
    arg = self.engine.contextual_connect()
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\threadlocal.py", line 64, in contextual_connect
    self.pool.connect, connection),
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "C:\Python27\lib\site-packages\sqlalchemy\pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Python27\lib\site-packages\sqlalchemy\pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Python27\lib\site-packages\sqlalchemy\pool.py", line 480, in checkout
    rec = pool._do_get()
  File "C:\Python27\lib\site-packages\sqlalchemy\pool.py", line 1151, in _do_get
    return self._create_connection()
  File "C:\Python27\lib\site-packages\sqlalchemy\pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Python27\lib\site-packages\sqlalchemy\pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "C:\Python27\lib\site-packages\sqlalchemy\pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Python27\lib\site-packages\sqlalchemy\engine\default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
 
buildbot.test.unit.test_scripts_cleanupdb.TestCleanupDb.test_cleanup 
=============================================================================== 
[ERROR] 
Traceback (most recent call last):
Failure: buildslave.exceptions.AbandonChain: -1
 
buildslave.test.unit.test_runprocess.TestRunProcess.testMultiWordStringCommand 
buildslave.test.unit.test_runprocess.TestRunProcess.testMultiWordStringCommandQuotes 
buildslave.test.unit.test_runprocess.TestRunProcess.testPipeString 
buildslave.test.unit.test_runprocess.TestRunProcess.testStringCommand 
------------------------------------------------------------------------------- 
Ran 4808 tests in 226.187s 
 
FAILED (skips=282, errors=5, successes=4521)
```

**Comment by rutsky** [comment]
Main tests set on Windows is passing (additional packages like `txgithub` are not installed).
Lets merge this one and later install additional packages and run in different Python versions (e.g. Python 2.6 and 64-bit versions of environments).

**Comment by tardyp** [comment]
Yeah! Good work!

Le lun. 29 févr. 2016 12:23, Vladimir Rutsky <notifications@github.com> a
écrit :

**Pull request merged**
