### PR TITLE
Add a GerritChangeSource that does not produce unrelated changes

### PR DESCRIPTION
**Pull request by sa2ajj**

### CODE REVIEW

**Comment by tardyp** [comment]
This means that of you have n projects, you need n ssh connections. I'm not sure that we want to keep this API for long term

**Comment by sa2ajj** [comment]
I have a slightly different use case: one buildmaster looks for a particular branch of a particular project.

**Comment by tardyp** [comment]
Yes, I understand, but the case 1 filter is just a particularization of the case n filters.
The api you are proposing may not be enhanced easily to the case n filters.

I don't think the version in buildbot_travis is suitable either: https://github.com/tardyp/buildbot_travis/blob/master/buildbot_travis/vcs/gerrit.py

This is why I did not upstream it. I think we should find a way to have a simple configuration *and* share the ssh process in case of multiproject master.

**Comment by sa2ajj** [comment]
I am not sure what you mean by "share", however I agree about the API.

**Comment by sa2ajj** [comment]
Let's do it for master first.

**Pull request closed without merging**
