### PR TITLE
Add /redirect path to redirect to latest build

### PR DESCRIPTION
**Pull request by sa2ajj**
Trying to resubmit GH-1089

### CODE REVIEW

**Comment by sa2ajj** [comment]
@kviktor do you think you could provide an update for release notes?

**Comment by jaredgrubb** [comment]
Any update on this one?

**Comment by djmitche** [comment]
@sa2ajj do you still want to merge this to eight, at this point, or should we close?

**Comment by kviktor** [comment]
#1745 is the updated version, there is no point of this PR anymore.

**Pull request closed without merging**
