### PR TITLE
Use print() function everywhere as specified in PEP3105.

### PR DESCRIPTION
**Pull request by rodrigc**
This works on Python 2.6 and higher.  This is mandatory on Python 3.

### CODE REVIEW

**Comment by tardyp** [comment]
LGTM.

what is the command you used to do that?
Couldn't we had an automated test to make sure print are not reintroduced by mistake?

like we do for isort:

  - "[ $TESTS != lint ] || isort --check -df `git ls-files |grep '.py$'`"

**Comment by rodrigc** [comment]
I used this command in the top-level directory:

```
2to3 -f print .
```

I am not sure how to implement a check to prevent re-introducing this.
Hopefully we can get to the point where we can add a Python 3 build to CI, since
that is the easiest way to verify it.  It's too early for a Python 3 CI build at this point.

**Comment by tardyp** [comment]
what you can do is to run the command, and then look at git diff to see if some file were modified.

This is what I did with isort until I realized there were a check option

**Comment by rodrigc** [comment]
I'm not too handy with those kinds of checks and am scared I may break something,
for example if there is a legitimate use of "print " somewhere like in a string.
I'll leave that for a subsequent PR.

**Comment by tardyp** [comment]
You did break isort actually.
please run make isort on root dir to fix it.

**Comment by tardyp** [comment]
this needs rebase now I merged the other PR.. :-/

**Comment by rodrigc** [comment]
@tardyp I rebased this

**Comment by djmitche** [comment]
:+1: to the idea of checking these things to prevent backsliding.  At one point we had replaced all print with print(), I think, but clearly we lost some!

**Comment by tardyp** [comment]
Indeed. And I plaid mostly culprit of that prints

Le sam. 27 août 2016 15:34, Dustin J. Mitchell <notifications@github.com> a
écrit :

**Comment by Stibbons** [comment]
you can check "from __future__ import print_function" appears in every python files

**Pull request merged**
