### PR TITLE
RFC: shell.py: Also match on errors from stdio

### PR DESCRIPTION
**Pull request by krf**
This is a almost 1:1 copy from the patch attached to the bug report.
Applied onto current code base.

Partly fixes #339

TODO: Rename class?

### CODE REVIEW

**Comment by jaredgrubb** [comment]
Looks ok to me! It would be nice if there were tests for the new error stuff.

**Comment by tardyp** [comment]
Looks good. I think we could abstract the concept a little bit more, and create PatternCountingShellCommand(patterns=dict(errors="Error:?.+", warnings="warning:?.*")

you would have to rename the class, and create a WarningCountingShellCommand as a preconfigured subclass (to keep compatibility)

**Comment by sa2ajj** [comment]
This does not seem to cleanly apply to nine.  Maybe it's better to first submit it to nine and then backport to eight?

(@sa2ajj looks at the current set of changes in eight and is a bit concerned...)

**Comment by yetanotherion** [comment]
:+1:

**Comment by sa2ajj** [comment]
@yetanotherion I agree, but I'd like to see it in master first.

**Comment by jaredgrubb** [comment]
Are we just waiting on a nine pull-reqeuest to satisfy this?

**Comment by djmitche** [comment]
Yes, otherwise we'll be adding functionality to eight that's not available in nine.

**Comment by krf** [comment]
Note: Just checked. Simply cherry-picking this to nine isn't possible; code has changed to much in the meanwhile. I won't have time to port this to Nine (no way to test either, as we don't use Nine yet).

**Comment by djmitche** [comment]
OK, I'm going to close this up per http://trac.buildbot.net/wiki/StalePullRequestPolicy.  Of course, the code is still here if someone wants to forward-port to nine.  And this can be cherry-picked into an eight installation.

**Pull request closed without merging**
