### PR TITLE
install boto, moto and txgithub to get some tests running on Travis

### PR DESCRIPTION
**Pull request by rutsky**

### CODE REVIEW

**Comment by rutsky** [comment]
Looks like on Python 2.6 on Travis we will always get warnings:

```
Traceback (most recent call last):

  File "/home/travis/build/buildbot/buildbot/master/buildbot/test/unit/test_scripts_start.py", line 88, in cb

    self.assertEquals(res, ('', '', 0))

  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/twisted/trial/unittest.py", line 271, in assertEqual

    % (msg, pformat(first), pformat(second)))

twisted.trial.unittest.FailTest: not equal:

a = ('',

 '/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6\n  DeprecationWarning\n',

 0)

b = ('', '', 0)
```

**Comment by djmitche** [comment]
Might be best to just skip that test on 2.6?

**Comment by rutsky** [comment]
@djmitche, rebased, added check for Python 2.6 (that two tests are skipped on 2.6). Please take a look.

**Comment by djmitche** [comment]
Very nice :)

**Pull request merged**
