### PR TITLE
Backport plugins

### PR DESCRIPTION
**Pull request by sa2ajj**

### CODE REVIEW

**Comment by sa2ajj** [comment]
Documentation in nine needs to be reviewed: way too many things were changed during this backport.

**Comment by djmitche** [comment]
In nine? or in eight?

**Comment by sa2ajj** [comment]
This is for eight.

But after this is complete, I'll need to review the docs in nine: it looks like I missed some things...  (A different PR for sure :))

**Comment by djmitche** [comment]
Without looking deeply to see how this differs from nine, :+1:

**Pull request merged**
