### PR TITLE
MD: Settings page

### PR DESCRIPTION
**Pull request by shanzi**
Here is the settings page. Based on a similar style to about page, this page does not need much coding.

settings-preview

settings-preview-thin

**NOTE**: As other pages that providing settings have not been written yet, so I added a testing settings group to preview the effect. If merge with this testing group is acceptable? Please review and give your advices.

### CODE REVIEW

**Comment by shanzi** [comment]
live demo updated

**Comment by tardyp** [comment]
pretty cool!
waiting for @tothandras +1

**Comment by jaredgrubb** [comment]
Definitely cool :)

**Comment by tothandras** [comment]
Really nice! :)
I would keep the styles used by the view in the same folder, and when other view starts to use it then move to the shared folder.

**Comment by shanzi** [comment]
@tothandras you mean put the `setting-` related styles in a separated file under `/settings` folder?
These styles seems to be to little to be put in standalone file. Hmmmm....

**Comment by tothandras** [comment]
I think it's not about the size. If I would like to modify the styles related to settings, the card.less will be the last where I would look for it.

**Comment by shanzi** [comment]
@tothandras OK.

Which do you think is better? Put them in `/app/settings/settings.less` or `/styles/settings.less`?

**Comment by tothandras** [comment]
I prefer /app/settings/settings.less

**Comment by tardyp** [comment]
Le sam. 2 mai 2015 à 13:11, András Tóth <notifications@github.com> a écrit :

> I prefer /app/settings/settings.less
>

Agreed. We should document this in coffee-style.rst


>

**Comment by tardyp** [comment]
actually, card.less is already shared, and make sense. I'll merge this tomorrow, if no other blockers

**Comment by shanzi** [comment]
I think his pr is ready to be merged :)

**Comment by sa2ajj** [comment]
Thanks!

**Pull request merged**
