### PR TITLE
Issues should be opened on GitHub, not trac.

### PR DESCRIPTION
**Pull request by rodrigc**

### CODE REVIEW

**Comment by rodrigc** [comment]
@blag how does this look?  If you like it, can you Review it through the GitHub review interface?

**Comment by blag** [comment]
LGTM. 👍 

Thanks for taking care of this!

**Comment by rodrigc** [comment]
@blag can you click the *Review Changes* button at: https://github.com/buildbot/buildbot/pull/3318/files

**Comment by blag** [comment]
Done.

**Comment by rodrigc** [comment]
@blag thanks I'll merge this once the builders are done.

**Pull request merged**
