### PR TITLE
add --wait option for `buildbot stop`

### PR DESCRIPTION
**Pull request by rutsky**

### CODE REVIEW

**Comment by tardyp** [comment]
👍

**Comment by Stibbons** [comment]
we actually made it the default behavior. We could have a "--no-wait" as an option

**Comment by rutsky** [comment]
I like you idea @Stibbons, thanks!

Any objections on making `--wait` default behaviour and adding `--no-wait` instead?

**Comment by rutsky** [comment]
@tardyp, @Stibbons I pushed `--no-wait` version, please take a look.

**Comment by Stibbons** [comment]
I like :)

**Comment by tardyp** [comment]
thx

**Pull request merged**
