### PR TITLE
Git._fetch: move to defer.inlineCallbacks

### PR DESCRIPTION
**Pull request by jaredgrubb**
A non-functional change to add 'inlineCallbacks'.

### CODE REVIEW

**Comment by tardyp** [comment]
:+1:

**Comment by sa2ajj** [comment]
```
[ERROR]
Traceback (most recent call last):
Failure: twisted.internet.defer.TimeoutError: <buildbot.test.integration.test_stop_trigger.TriggeringMaster testMethod=testTriggerRunsForever> (testTriggerRunsForever) still running at 120.0 secs

buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 1039, in _inlineCallbacks
    result = g.send(result)
  File "/home/travis/build/buildbot/buildbot/master/buildbot/test/util/integration.py", line 128, in tearDown
    raise self.failureException(dump.getvalue())
twisted.trial.unittest.FailTest: FAILED! dumping build db for debug
*** BUILD 1 *** ==> starting (Invalid status)
    *** STEP trigger *** ==> triggered trigsched (Invalid status)
       url:trigsched #2 (http://localhost:8080/#buildrequests/2)
*** BUILD 2 *** ==> starting (Invalid status)
    *** STEP shell *** ==> 'while : ...' (Invalid status)
        log:stdio (213)
        *********** LOG: stdio *********
        ********************************
        log:cancelled (1)
        *********** LOG: cancelled *********
('control', 'builds', '2', 'stop')

        ********************************


buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/travis/build/buildbot/buildbot/master/buildbot/mq/base.py", line 41, in invoke
    x = self.callback(routing_key, data)
  File "/home/travis/build/buildbot/buildbot/master/buildbot/process/build.py", line 501, in stopBuild
    self.currentStep.interrupt(reason)
  File "/home/travis/build/buildbot/buildbot/master/buildbot/process/buildstep.py", line 929, in interrupt
    d = self.cmd.interrupt(reason)
  File "/home/travis/build/buildbot/buildbot/master/buildbot/process/remotecommand.py", line 161, in interrupt
    d = self.conn.remoteInterruptCommand(self.commandID, str(why))
  File "/home/travis/build/buildbot/buildbot/master/buildbot/buildslave/protocols/null.py", line 91, in remoteInterruptCommand
    return defer.maybeDeferred(self.buildslave.bot.remote_interruptCommand, commandId, why)
exceptions.AttributeError: BotBase instance has no attribute 'remote_interruptCommand'

buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 1095, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 1085, in _inlineCallbacks
    deferred.errback()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 391, in errback
    self._startRunCallbacks(fail)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py", line 451, in _startRunCallbacks
    raise AlreadyCalledError
twisted.internet.defer.AlreadyCalledError: 

buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
```

**Comment by tardyp** [comment]
It's a flaky test from @yetanotherion

Le mar. 19 mai 2015 05:58, Mikhail Sobolev <notifications@github.com> a
écrit :

**Comment by yetanotherion** [comment]
Well, even if I cannot objective on that :), I think these
buildbot.test.integration.test_stop_trigger tests reveal race conditions
that should be corrected.
i.e. rather than test, the code may be the flaky one :). Nonetheless
I start working on a fix on the related code right now. I'll keep you
updated

2015-05-19 6:03 GMT+02:00 Pierre Tardy <notifications@github.com>:

> It's a flaky test from @yetanotherion
>
> Le mar. 19 mai 2015 05:58, Mikhail Sobolev <notifications@github.com> a
> écrit :
>
>
> > [ERROR]
> > Traceback (most recent call last):
> > Failure: twisted.internet.defer.TimeoutError:
> <buildbot.test.integration.test_stop_trigger.TriggeringMaster
> testMethod=testTriggerRunsForever> (testTriggerRunsForever) still running
> at 120.0 secs
> >
> >
> buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
> >
> ===============================================================================
> > [ERROR]
> > Traceback (most recent call last):
> > File
> "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py",
> line 1039, in _inlineCallbacks
> > result = g.send(result)
> > File
> "/home/travis/build/buildbot/buildbot/master/buildbot/test/util/integration.py",
> line 128, in tearDown
> > raise self.failureException(dump.getvalue())
> > twisted.trial.unittest.FailTest: FAILED! dumping build db for debug
> > *** BUILD 1 *** ==> starting (Invalid status)
> > *** STEP trigger *** ==> triggered trigsched (Invalid status)
> > url:trigsched #2 (http://localhost:8080/#buildrequests/2)
> > *** BUILD 2 *** ==> starting (Invalid status)
> > *** STEP shell *** ==> 'while : ...' (Invalid status)
> > log:stdio (213)
> > *********** LOG: stdio *********
> > ********************************
> > log:cancelled (1)
> > *********** LOG: cancelled *********
> > ('control', 'builds', '2', 'stop')
> >
> > ********************************
> >
> >
> >
> buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
> >
> ===============================================================================
> > [ERROR]
> > Traceback (most recent call last):
> > File "/home/travis/build/buildbot/buildbot/master/buildbot/mq/base.py",
> line 41, in invoke
> > x = self.callback(routing_key, data)
> > File
> "/home/travis/build/buildbot/buildbot/master/buildbot/process/build.py",
> line 501, in stopBuild
> > self.currentStep.interrupt(reason)
> > File
> "/home/travis/build/buildbot/buildbot/master/buildbot/process/buildstep.py",
> line 929, in interrupt
> > d = self.cmd.interrupt(reason)
> > File
> "/home/travis/build/buildbot/buildbot/master/buildbot/process/remotecommand.py",
> line 161, in interrupt
> > d = self.conn.remoteInterruptCommand(self.commandID, str(why))
> > File
> "/home/travis/build/buildbot/buildbot/master/buildbot/buildslave/protocols/null.py",
> line 91, in remoteInterruptCommand
> > return defer.maybeDeferred(self.buildslave.bot.remote_interruptCommand,
> commandId, why)
> > exceptions.AttributeError: BotBase instance has no attribute
> 'remote_interruptCommand'
> >
> >
> buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
> >
> ===============================================================================
> > [ERROR]
> > Traceback (most recent call last):
> > File
> "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py",
> line 1095, in gotResult
> > _inlineCallbacks(r, g, deferred)
> > File
> "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py",
> line 1085, in _inlineCallbacks
> > deferred.errback()
> > File
> "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py",
> line 391, in errback
> > self._startRunCallbacks(fail)
> > File
> "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py",
> line 451, in _startRunCallbacks
> > raise AlreadyCalledError
> > twisted.internet.defer.AlreadyCalledError:
> >
> >
> buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/buildbot/buildbot/pull/1674#issuecomment-103325095>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/buildbot/buildbot/pull/1674#issuecomment-103326172>.
>



-- 
Ion

**Comment by yetanotherion** [comment]
I dig into the issue with the following test.
https://github.com/buildbot/buildbot/pull/1678/files

A proposal of both root cause and solution are depicted in that commit
https://github.com/yetanotherion/buildbot/commit/7a1465733c0033a5a7cc930d27f47800bf9a2ae3

I'd like to have your opinion before implementing it.
Waiting for feedbacks :)









2015-05-19 9:11 GMT+02:00 Ion Alberdi <nolaridebi@gmail.com>:

> Well, even if I cannot objective on that :), I think these
> buildbot.test.integration.test_stop_trigger tests reveal race conditions
> that should be corrected.
> i.e. rather than test, the code may be the flaky one :). Nonetheless
> I start working on a fix on the related code right now. I'll keep you
> updated
>
> 2015-05-19 6:03 GMT+02:00 Pierre Tardy <notifications@github.com>:
>
>> It's a flaky test from @yetanotherion
>>
>> Le mar. 19 mai 2015 05:58, Mikhail Sobolev <notifications@github.com> a
>> écrit :
>>
>>
>> > [ERROR]
>> > Traceback (most recent call last):
>> > Failure: twisted.internet.defer.TimeoutError:
>> <buildbot.test.integration.test_stop_trigger.TriggeringMaster
>> testMethod=testTriggerRunsForever> (testTriggerRunsForever) still running
>> at 120.0 secs
>> >
>> >
>> buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
>> >
>> ===============================================================================
>> > [ERROR]
>> > Traceback (most recent call last):
>> > File
>> "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py",
>> line 1039, in _inlineCallbacks
>> > result = g.send(result)
>> > File
>> "/home/travis/build/buildbot/buildbot/master/buildbot/test/util/integration.py",
>> line 128, in tearDown
>> > raise self.failureException(dump.getvalue())
>> > twisted.trial.unittest.FailTest: FAILED! dumping build db for debug
>> > *** BUILD 1 *** ==> starting (Invalid status)
>> > *** STEP trigger *** ==> triggered trigsched (Invalid status)
>> > url:trigsched #2 (http://localhost:8080/#buildrequests/2)
>> > *** BUILD 2 *** ==> starting (Invalid status)
>> > *** STEP shell *** ==> 'while : ...' (Invalid status)
>> > log:stdio (213)
>> > *********** LOG: stdio *********
>> > ********************************
>> > log:cancelled (1)
>> > *********** LOG: cancelled *********
>> > ('control', 'builds', '2', 'stop')
>> >
>> > ********************************
>> >
>> >
>> >
>> buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
>> >
>> ===============================================================================
>> > [ERROR]
>> > Traceback (most recent call last):
>> > File "/home/travis/build/buildbot/buildbot/master/buildbot/mq/base.py",
>> line 41, in invoke
>> > x = self.callback(routing_key, data)
>> > File
>> "/home/travis/build/buildbot/buildbot/master/buildbot/process/build.py",
>> line 501, in stopBuild
>> > self.currentStep.interrupt(reason)
>> > File
>> "/home/travis/build/buildbot/buildbot/master/buildbot/process/buildstep.py",
>> line 929, in interrupt
>> > d = self.cmd.interrupt(reason)
>> > File
>> "/home/travis/build/buildbot/buildbot/master/buildbot/process/remotecommand.py",
>> line 161, in interrupt
>> > d = self.conn.remoteInterruptCommand(self.commandID, str(why))
>> > File
>> "/home/travis/build/buildbot/buildbot/master/buildbot/buildslave/protocols/null.py",
>> line 91, in remoteInterruptCommand
>> > return defer.maybeDeferred(self.buildslave.bot.remote_interruptCommand,
>> commandId, why)
>> > exceptions.AttributeError: BotBase instance has no attribute
>> 'remote_interruptCommand'
>> >
>> >
>> buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
>> >
>> ===============================================================================
>> > [ERROR]
>> > Traceback (most recent call last):
>> > File
>> "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py",
>> line 1095, in gotResult
>> > _inlineCallbacks(r, g, deferred)
>> > File
>> "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py",
>> line 1085, in _inlineCallbacks
>> > deferred.errback()
>> > File
>> "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py",
>> line 391, in errback
>> > self._startRunCallbacks(fail)
>> > File
>> "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/twisted/internet/defer.py",
>> line 451, in _startRunCallbacks
>> > raise AlreadyCalledError
>> > twisted.internet.defer.AlreadyCalledError:
>> >
>> >
>> buildbot.test.integration.test_stop_trigger.TriggeringMaster.testTriggerRunsForever
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/buildbot/buildbot/pull/1674#issuecomment-103325095
>> >.
>>
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/buildbot/buildbot/pull/1674#issuecomment-103326172>.
>>
>
>
>
> --
> Ion
>



-- 
Ion

**Comment by jaredgrubb** [comment]
Are we still waiting on anything here? The failing tests above are not related to this patch.

**Comment by yetanotherion** [comment]
Hello Jared, two bugs that appear on race conditions were identified for
now,
thus resulting in non reliable PR validation tests
- https://github.com/buildbot/buildbot/pull/1678/: fixed and merged
- https://github.com/buildbot/buildbot/pull/1688: in review

Let's hope that after merging the second PR, we don't end up in another
racy bug.

:+1:

2015-05-24 21:07 GMT+02:00 Jared Grubb <notifications@github.com>:

> Are we still waiting on anything here? The failing tests above are not
> related to this patch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/buildbot/buildbot/pull/1674#issuecomment-105048471>.
>



-- 
Ion

**Comment by tardyp** [comment]
merged after running validate.sh thanks

**Pull request merged**
