### PR TITLE
Fix LibVirtWorker disconnect error

### PR DESCRIPTION
**Pull request by Akrog**
When insubstantiating a libvirt worker the disconnection will raise an
excepcion complaining that:

  builtins.TypeError: super(type, obj): obj must be an instance or subtype
  of type

This is because super() cannot find the right method to call.

This patch replaces super().disconnect() with self.disconnect() which
will call the right disconnect method, the one in the
AbstractLatentWorker.

## Contributor Checklist:

* [x] I have updated the unit tests
* [x] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)
* [-] I have updated the appropriate documentation

### CODE REVIEW

**Comment by Akrog** [comment]
Job `bb/pylint/3.7/tw:latest/sqla:latest/db:sqlite://` is complaining about a wrong spelling in a comment:

```
buildbot/worker/libvirt.py:302 Wrong spelling of a word 'AbstractLatentWorker' in a comment:
# super(AbstractLatentWorker, self).disconnect will result in a
        ^^^^^^^^^^^^^^^^^^^^
Did you mean: ''Abstractedness' or 'Abstracter' or 'Indestructibleness' or 'Restructurability''? [wrong-spelling-in-comment]
```

I will change the comment and reference it as "the parent class" instead of saying the parent actual class name, but not being able to reference class names in comments seems a little weird.

Error on `bb/trial/3.6/tw:latest/sqla:latest/db:sqlite://` seems unrelated to this PR:

```
FAILED (skips=28, errors=1, successes=5668)
Exception ignored in: <_io.FileIO name='/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/moto/ec2/resources/instance_types.json' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/moto/ec2/resources/instance_types.json' mode='r' encoding='UTF-8'>
Exception ignored in: <_io.FileIO name='/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/moto/ec2/resources/amis.json' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/buildbot/buildbot-job/build/sandbox/lib/python3.6/site-packages/moto/ec2/resources/amis.json' mode='r' encoding='UTF-8'>
Exception ignored in: <generator object run at 0x7fe134252f68>
RuntimeError: generator ignored GeneratorExit
Exception ignored in: <generator object run at 0x7fe114438780>
RuntimeError: generator ignored GeneratorExit
Exception ignored in: <generator object run at 0x7fe114438ba0>
RuntimeError: generator ignored GeneratorExit
Exception ignored in: <socket.socket fd=7, family=AddressFamily.AF_INET, type=2050, proto=0, laddr=('0.0.0.0', 0)>
ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_INET, type=2050, proto=0, laddr=('0.0.0.0', 0)>
Exception ignored in: <_io.FileIO name='/dev/null' mode='rb' closefd=True>
ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='r' encoding='UTF-8'>
```

**Comment by Akrog** [comment]
Looks like this patch won't work, as new Buildrequests will not be scheduled since the worker is disconnected and it won't recover until we restart due to this call `self.botmaster.workerLost(self)` made in `AbstractLatentWorker`.

I believe we need to refactor the whole `stop_instance` method in `LibVirtWorker` and stop calling `disconnect`.

**Comment by p12tic** [comment]
>  is complaining about a wrong spelling in a comment:

The word whitelist for the spellchecker can be updated in such cases, it's located in the common/code_spelling_ignore_words.txt file.

**Comment by Akrog** [comment]
> > is complaining about a wrong spelling in a comment:
> 
> The word whitelist for the spellchecker can be updated in such cases, it's located in the common/code_spelling_ignore_words.txt file.

Good to know, thanks!

**Pull request merged**
