### PR TITLE
Display build times with d3

### PR DESCRIPTION
**Pull request by tardyp**
This shows the perf regression we had:
toto

### CODE REVIEW

**Comment by p12tic** [comment]
I was wondering how much server-side resources does this graph use on larger installations. Could it be that large number of users overwhelm the master?

**Comment by p12tic** [comment]
Yet at the same time my own PR did completely stupid things in wrt. performance :-)

**Comment by tardyp** [comment]
The graph is purely generated on the browser, with the data that it already downloaded for the build table. So no additional load for server.

**Comment by tardyp** [comment]
You can see the result on metabuildbot: https://nine.buildbot.net/#/builders/68
(and the increase of pylint run time from 10 to 17 minutes)

**Comment by p12tic** [comment]
Thanks for explanation. If we're only using the data we download anyway, then my comment does not apply. Good to know.

**Pull request merged**
