### PR TITLE
Configure webpack to load images.

### PR DESCRIPTION
**Pull request by rajdeepbharati**
Import img files in `app.module.js` and configure webpack.

Fixes https://github.com/buildbot/buildbot/issues/4880

### CODE REVIEW

**Comment by p12tic** [comment]
Thanks for figuring this issue out. I think that instead of requiring the images from javascript side, we should do that where the image is actually used, i.e. the jade templates. E.g. pug loader docs have this example: `img(src=require("./my/image.png"))`

**Comment by tardyp** [comment]
advantage of .jade require is that the file name can be changed to <sha>.png so that cache is ignored on change.
This is arguably barely the case for our usage, but this he a thing to know for a young developer

**Comment by rajdeepbharati** [comment]
I'm not able to use `require` inside my .jade files. I looked up issues on pug-loader and file-loader on their repos and SO but none of the fixes seem to work for me. 😢

**Comment by p12tic** [comment]
Indeed, looks like this does not work. See https://github.com/pugjs/pug/issues/2604.

**Pull request merged**
