### PR TITLE
Wait for self.assertFailure() return value

### LINKED ISSUE #4253: self.assertFailure return value should be waited for
as per https://twistedmatrix.com/trac/ticket/9505

self.assertFailure returns a deferred, that should be waited for in the test.

```
git grep -E '^ +self.assertFailure'
master/buildbot/test/unit/test_changes_github.py:        self.assertFailure(d, KeyError)
master/buildbot/test/unit/test_changes_p4poller.py:        self.assertFailure(d, P4PollerError)
master/buildbot/test/unit/test_db_buildsets.py:        self.assertFailure(d, AssertionError)
master/buildbot/test/unit/test_db_changesources.py:        self.assertFailure(d, changesources.ChangeSourceAlreadyClaimedError)
master/buildbot/test/unit/test_db_changesources.py:        self.assertFailure(d, changesources.ChangeSourceAlreadyClaimedError)
master/buildbot/test/unit/test_db_schedulers.py:        self.assertFailure(d, schedulers.SchedulerAlreadyClaimedError)
master/buildbot/test/unit/test_db_schedulers.py:        self.assertFailure(d, schedulers.SchedulerAlreadyClaimedError)
master/buildbot/test/unit/test_db_steps.py:        self.assertFailure(d, RuntimeError)
master/buildbot/test/unit/test_interpolate_secrets.py:        self.assertFailure(self.build.render(command), defer.FirstError)
master/buildbot/test/unit/test_interpolate_secrets.py:        self.assertFailure(self.build.render(command), defer.FirstError)
master/buildbot/test/unit/test_process_properties.py:        self.assertFailure(d, TypeError)
master/buildbot/test/unit/test_process_properties.py:        self.assertFailure(d, RuntimeError)
master/buildbot/test/unit/test_stats_service.py:        self.assertFailure(cap.consume(self.routingKey, self.get_dict(build)),
master/buildbot/test/unit/test_stats_service.py:        self.assertFailure(cap.consume(self.routingKey, self.get_dict(build)),
master/buildbot/test/unit/test_stats_service.py:        self.assertFailure(cap.consume(self.routingKey, self.get_dict(build)),
master/buildbot/test/unit/test_stats_service.py:        self.assertFailure(cap.consume(self.routingKey, self.get_dict(build)),
master/buildbot/test/unit/test_stats_service.py:        self.assertFailure(cap.consume(routingKey, msg), CaptureCallbackError)
master/buildbot/test/unit/test_util_codebase.py:        self.assertFailure(d, KeyError)
master/buildbot/test/unit/test_util_lru.py:            self.assertFailure(d, RuntimeError)
master/buildbot/test/unit/test_util_misc.py:        self.assertFailure(d, RuntimeError)
master/buildbot/test/unit/test_util_misc.py:        self.assertFailure(d, defer.CancelledError)
master/buildbot/test/unit/test_util_misc.py:        self.assertFailure(d, defer.CancelledError)
master/buildbot/test/unit/test_worker_openstack.py:        self.assertFailure(bs.start_instance(self.build), ValueError)
master/buildbot/test/unit/test_www_auth.py:        self.assertFailure(defer_bad, UnauthorizedLogin)
worker/buildbot_worker/test/unit/test_commands_transfer.py:        self.assertFailure(d, RuntimeError)
worker/buildbot_worker/test/unit/test_commands_transfer.py:        self.assertFailure(d, RuntimeError)
```

### PR DESCRIPTION
**Pull request by mokibit**
Fixes #4253.

### CODE REVIEW

**Comment by yan12125** [comment]
Could you remove the workaround for the original issue? https://github.com/buildbot/buildbot/commit/7fa7259698cc4d917686b02ac0e10e9d6350e392

**Comment by yan12125** [comment]
Looks like test failures are caused by registry.yarnpkg.com unstability. A fix can be found at #4291

**Comment by yan12125** [comment]
The original bug surfaced again after the workaround reverted. I know little about twisted internals, but this comment might be useful: https://twistedmatrix.com/trac/ticket/9505#comment:1

**Comment by mokibit** [comment]
I think reverting the commit should be in a separate PR.

**Comment by tardyp** [comment]
actually 7fa7259 was not a commit against unwaited assertFailure.

It happens that Jean Paul pointed out that we should wait for assertFailures, which is good remark, but unrelated to that bug.

The root cause of the instability is really how much we force the garbage collector before flushLoggedError, which is implemented by the workaround.

**Pull request merged**
