### PR TITLE
interfaces: isRenderable

### PR DESCRIPTION
**Pull request by yetanotherion**
Method to compute whether an object
is renderable.

### CODE REVIEW

**Comment by sa2ajj** [comment]
Do we already have users for this method?

**Comment by jaredgrubb** [comment]
Looks good, but a unit test or two could be good.

**Comment by tardyp** [comment]
after digging, it looks like this patch is needed by workdir renderable patch we have on our old buildbot eight. After discussing with the devs, I believe that the isRenderable is not really needed. @yetanotherion  if you agree, please close

**Comment by yetanotherion** [comment]
closed, good we to all !

**Pull request closed without merging**
