### PR TITLE
Do the hustle (3)

### PR DESCRIPTION
**Pull request by ravench**
Fresh fork, clean coding, passing tests. (hopefully, anyway)
Someone in #qutebrowser suggested that buildbot should learn to do the hustle.. Here it is.

### CODE REVIEW

**Comment by ravench** [comment]
Seems like build 3495.9 errored due to a connection timeout..
```
Download error on https://pypi.python.org/simple/markupsafe/: [Errno 110] Connection timed out -- Some packages may not be found!
Couldn't find index page for 'markupsafe' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for markupsafe
error: Could not find suitable distribution for Requirement.parse('markupsafe')
```

**Comment by tardyp** [comment]
Your really were serious about that?
I am not sure  we should create more easter egg in the IRC bot.

Not strongly opposed though

**Comment by ravench** [comment]
I was. Well, as serious as you can be when it comes to EE's anyway.
Hmm.. Personally, I love Easter Eggs....

**Comment by djmitche** [comment]
It's getting a little silly, yes, but it doesn't hurt anything!

**Pull request merged**
