### PR TITLE
Improved P4 support

### PR DESCRIPTION
**Pull request by casastorta**
Master branch

### CODE REVIEW

**Comment by sa2ajj** [comment]
Do you think you could re-work your branch without merges?

**Comment by casastorta** [comment]
Sure thing, will squash changes into one meaningful commit.

**Comment by rutsky** [comment]
Is P4 stuff tested? Is it hard to add unit test on these changes?

**Comment by casastorta** [comment]
On Sat, Feb 6, 2016 at 6:33 PM, Vladimir Rutsky
<notifications@github.com> wrote:
> Is P4 stuff tested?

Yes, it's live on our internal CI system.

> Is it hard to add unit test on these changes?

I would lie if I say it didn't cross my mind. Answer is so-so.

Except unit testing for the outcome of assembling the client spec
(basically a text format input passed to P4 binary), which is
definitely possible I don't see anything else doable. I can do this
one, since I think I didn't see any coverage for this one.

But on more functional level... It's impossible to test it
functionally without Perforce infrastructure (and I'm not aware of any
P4 service publicly available which we could hook into) and a local p4
command line binary. Mocking all this seems unreasonably hard.


V.

-- 
  Pozdrav/Greetings,
  Vedran Krivokuća
  Disclaimer: This message may contain information.

**Comment by rutsky** [comment]
At least test that generated client spec is expected would be nice.
Otherwise other developers have no chance to check on any level that their future changes doesn't break your feature.

**Comment by casastorta** [comment]
I fully agree. It might take me some days, up to few weeks, to implement
the promised changes (in between daily job and a small kid back at home).
But I'll be on this!

On Sun, Feb 7, 2016 at 12:15 PM, Vladimir Rutsky <notifications@github.com>
wrote:

> At least test that generated client spec is expected would be nice.
> Otherwise other developers have no chance to check on any level that their
> future changes doesn't break your feature.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/buildbot/buildbot/pull/1975#issuecomment-180997126>.
>



-- 
<https://www.linkedin.com/in/casastorta>  <https://github.com/casastorta>
Pozdrav/Greetings,
<https://twitter.com/casastorta/>
<https://plus.google.com/115558490731481521000> Vedran Krivokuća
<http://krivokuca.net/>  <http://www.last.fm/user/vkrivokuca> Disclaimer:
This message may contain information.

**Comment by sa2ajj** [comment]
@casastorta thank you for spending your time on improving the contribution: merges make history really "hairy", so we'd like to avoid this at an extra cost [from contributors].

**Comment by tardyp** [comment]
Hi @casastorta, we would really like to see this finished!

**Comment by casastorta** [comment]
I realize that, sorry. :-) Branch has been cleared of merges and I yet have to do unit tests (which will probably be easier than I imagined, since there is already a set of those for P4 functionality) but right now no time for it. Will do my best soon.

**Comment by sa2ajj** [comment]
> This branch has conflicts that must be resolved
Looks like it needs a bit more polishing :(  Sorry.

**Comment by mlabbe** [comment]
Ack, I really need stream support!  @sa2ajj Can you be more specific about what polishing it needs?

**Comment by seankelly** [comment]
Needs some tests. Perforce isn't something many people have access to it and the recent Perforce encoding issue on Python 3 underscores the need for thorough tests.

**Pull request closed without merging**
