### PR TITLE
[WIP] Add callback function for GitHubCommentPush

### PR DESCRIPTION
**Pull request by anish**
TODO : 
* Add unit tests
* Figure out if function definition for callback is correct

### CODE REVIEW

**Comment by tardyp** [comment]
We prefer to use the renderable mechanism in order to implement such hooks, instead of cb.

startDescription and endDescription are already renderable, so you should be able to already customize your description

**Comment by anish** [comment]
@tardyp so would I, but specifically for comment push, the original goal was to access build logs to be able to comment, and a renderable does not let me access anything beyond properties. (Unless I'm missing some way to get this info via properties ?)

**Comment by anish** [comment]
@tardyp repeating comments from irc : 
```
10:16 < anish> tardyp: I tried using props.master.get.data() as recommended, however props does not seem to have access to the master at all :
2017-03-23 06:34:15+0000 [-] while invoking <bound method GitHubCommentPush.buildFinished of <buildbot.reporters.github.GitHubCommentPush object at 0x7eff7ab87350>>
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/buildbot/reporters/github.py", line 115, in send
	    description = yield props.render(self.endDescription)
	  File "/usr/lib/python2.7/site-packages/buildbot/process/properties.py", line 163, in render
	    return defer.maybeDeferred(renderable.getRenderingFor, self)
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "/usr/lib/python2.7/site-packages/buildbot/process/properties.py", line 782, in getRenderingFor
	    d = defer.maybeDeferred(self.fn, props)
	--- <exception caught here> ---
	  File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "/var/lib/buildbot/master.cfg", line 395, in getDesc
	    print props.master.data.get()
	exceptions.AttributeError: 'Properties' object has no attribute 'master'
10:18 < anish> I also enabled all the want* for the reporter, but looking at this code bit I don't think any of that will help a renderer as it gets thrown away 
               https://github.com/buildbot/buildbot/blob/master/master/buildbot/reporters/github.py#L103 & https://github.com/buildbot/buildbot/blob/master/master/buildbot/reporters/github.py#L115
```

since the renderer is only called as build['properties'].render(foo), I don't actual get access to anything, and  neither props.master nor props.build are available to reference. At the very least this seems like it needs a change to how wantProperties populates properties.

**Comment by tardyp** [comment]
you may try props.getBuild().master.data.get()

**Comment by anish** [comment]
@tardyp 
sadly no go : 
```
2017-03-23 23:07:33+0000 [-] while invoking <bound method GitHubCommentPush.buildFinished of <buildbot.reporters.github.GitHubCommentPush object at 0x7fb1d8737310>>
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/buildbot/reporters/github.py", line 115, in send
            description = yield props.render(self.endDescription)
          File "/usr/lib/python2.7/site-packages/buildbot/process/properties.py", line 163, in render
            return defer.maybeDeferred(renderable.getRenderingFor, self)
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/usr/lib/python2.7/site-packages/buildbot/process/properties.py", line 782, in getRenderingFor
            d = defer.maybeDeferred(self.fn, props)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/var/lib/buildbot/master.cfg", line 395, in getDesc
            print props.getBuild().master.data.get()
        exceptions.AttributeError: 'NoneType' object has no attribute 'master'
```
when using ```wantProperties=True, wantSteps=True, wantLogs=True```

**Pull request closed without merging**
