### PR TITLE
Fix missing VS2015 entry_points

### PR DESCRIPTION
**Pull request by LiqSolar**
Fix missing VS2015 entry_points in 'buildbot.steps'

### CODE REVIEW

**Comment by sa2ajj** [comment]
Thank you.

Once check complete, I'll merge based on the status :)

**Comment by LiqSolar** [comment]
Thank you sa2ajj

**Comment by sa2ajj** [comment]
Thanks again for the contribution

**Comment by tardyp** [comment]
I guess this is candidate for rc1 backport, right?

**Comment by LiqSolar** [comment]
Yes, rc1 has the same problem
(sorry for my grammar error in English ^^)

**Pull request merged**
