### PR TITLE
Allow user to specify custom ssh port

### PR DESCRIPTION
**Pull request by tenuki**
Allow user to specify custom ssh port when running a try command..

### CODE REVIEW

**Comment by jaredgrubb** [comment]
Looks good.

**Comment by tardyp** [comment]
looks good. please fix the lint issues.

make pep8
make pylint

https://travis-ci.org/buildbot/buildbot/jobs/100478196

**Comment by tenuki** [comment]
It should be ready! Thanks!!

**Comment by tenuki** [comment]
It is just one error reported twice (once by pylint and once by pep8), right?

**Comment by tardyp** [comment]
thank you!

**Pull request merged**
