### PR TITLE
fix python3 incompatibilities in KubeInClusterConfigLoader

### PR DESCRIPTION
**Pull request by doudou**
* [x] I have updated the unit tests
* [x] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [x] I have updated the appropriate documentation

### CODE REVIEW

**Comment by MartinDe85** [comment]
I think  so

**Comment by doudou** [comment]
> Looks good, but unit tests need updating.

You mean, actually having a test for this code path ?

**Comment by rodrigc** [comment]
Look here: https://github.com/buildbot/buildbot/pull/4661

In the section *Some checks have failed*.  Some of those tests failed due to your change.  Take a look at the logs for some of those failed tests, and see if you can update your patch so they pass.

**Comment by MartinDe85** [comment]
Sorry  today I don't  check  nothing

**Comment by doudou** [comment]
Updated. Only appveyor is failing now, and it's because of some network issues.

**Pull request merged**
