### PR TITLE
[nine] Triggerable: should allow reason to be set

### PR DESCRIPTION
**Pull request by jaredgrubb**
This is a patch we merged to eight ... simple port to nine.

### CODE REVIEW

**Comment by sa2ajj** [comment]
@jaredgrubb could you please rebase it against master so we see what tests show? :)

**Comment by jaredgrubb** [comment]
It is rebased on master now. Not sure if I did that after or before your request.

**Comment by yetanotherion** [comment]
:+1: besides the unit tests fail

**Comment by jaredgrubb** [comment]
I dont think the failing tests are from my patch. Many bots are passing.

**Pull request merged**
