### PR TITLE
Setup Docker Latent Worker to autopull image based on config

### LINKED ISSUE #3071: DockerLatentWorker: pull specified image if it is not yet on the system
This is merely an enhancement, but it would be nice if the specified image is pulled from dockerhub if it is not on yet on the host system. 
This should be pretty easy to accomplish using docker-py, but I don't know if this a desired feature.

### PR DESCRIPTION
**Pull request by btaidm**
Added automatic pulling of docker images by setting require config.
The setting is `autopull` and is set to false by default, keeping the original workflow.

Closes #3071.
Starts #3572 

## Contributor Checklist:

* [x] I have updated the unit tests
* [x] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [x] I have updated the appropriate documentation

### CODE REVIEW

**Comment by tardyp** [comment]
looks good! thanks, this was a long awaited feature!

We require to have test updated, though, so please add a unit test for this feature.

https://github.com/buildbot/buildbot/blob/master/master/buildbot/test/unit/test_worker_docker.py#L1
http://docs.buildbot.net/latest/developer/tests.html

**Comment by btaidm** [comment]
@tardyp 
Added Unit Test and update Fake Docker to include a pull function

**Comment by tardyp** [comment]
great work!

**Comment by chrwen-omicron** [comment]
An option to pull the latest could also be interesting, or should autopull simply pull every time even if the image exists to get changes?

**Pull request merged**
