### PR TITLE
Make sample.cfg more declarative

### PR DESCRIPTION
**Pull request by jml**
This patch changes the sample.cfg to just define a dictionary, rather than building one up piecemeal over several instructions.

It's partly a matter of personal taste, but I think this style makes the structure more clear. In particular, it makes it very obvious that none of the keys bare any relationship to the others. It also shifts it closer to the 'data' end of the spectrum than the 'code' end of the spectrum, which makes it simpler.

I've taken care not to reflow lines or make any other changes.

### CODE REVIEW

**Comment by djmitche** [comment]
The `c['..']` is how we recommend config files be structured, and how the config entries are referred to in the docs.  Also, in many cases the config is generated programmatically -- it really *isn't* data in any reasonably sophisticated configuration.  See https://github.com/buildbot/metabbotcfg for example.  Fitting that into a dictionary literal can end up being pretty ugly.

So I'm inclined to say "no" here, but I'll certainly let others chime in.

**Comment by tomprince** [comment]
Looking at https://github.com/buildbot/metabbotcfg/blob/master/master.cfg it could be turned into
```python
BuildmasterConfig = {
    'slaves': slaves,
    'schedulers': schedulers,
    'builders': builders,
    'status': status,
    'slavePortnum': 9989,
    'projectName': "Buildbot",
    'projectURL': "http://buildbot.net/",
    'buildbotURL': "http://buildbot.buildbot.net/",
    'changeHorizon': 200,
    'buildHorizon': 100,
    'logHorizon': 100,
    'eventHorizon': 10,
    'buildCacheSize': 300,
}
```
without any difficulty.

I think this would be a good change, but would require changing all the documentation to match this style.

**Comment by jml** [comment]
I'm not going to update all the docs, I'm afraid. Thanks for taking the time to consider the PR though!

**Comment by tardyp** [comment]
I note that this is the second similar PR in a few months.
https://github.com/buildbot/buildbot/pull/2051

While we agree for very simple config, this proposed form looks more pythonic, the current form makes it much easier to document snippets that people can just copy paste inside their config.

We encourage people to embrace the api, and use python as they like in order to implement their own config.

**Pull request closed without merging**
