### PR TITLE
db: add primary keys in tables lacking them

### LINKED ISSUE #3841: Missing primary keys in some database tables
Some tables from migrate_utils.py and model.py don't have a primary
key. Because of that some RDBMS complain when executing...

```
buildbot upgrade-master /path/to/master/directory/
```

### PR DESCRIPTION
**Pull request by rjarry**
This is based on work done by @vincent-olivert-riera in #3432. I added unit tests and reworked the migration script.

Fixes #3841 

## Contributor Checklist:

* [x] I have updated the unit tests
* [x] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)

### CODE REVIEW

**Comment by tardyp** [comment]
> got unexpected index buildset_properties_pkey on table buildset_properties: {'unique': 1, 'name': u'buildset_properties_pkey', 'column_names': [u'buildsetid', u'property_name']}

mysql automatically creates indices. Maybe sqlite also does that.

**Comment by tardyp** [comment]
will you have time to finish this before 1st of Jan? I'd like to make the release on that day.
This would be the last release before 1.0, and I would like to avoid 1.0 to be a upgrade database release..

**Comment by rjarry** [comment]
If I have some time to work on that it is tomorrow afternoon. I'll see if I
can get it working. If not, maybe we can give this up.

**Comment by rjarry** [comment]
I don't see any easy way to work around the duplicate indexes problem.

Maybe we should put this aside for now...

**Pull request closed without merging**
