### PR TITLE
Issue3562

### LINKED ISSUE #3562: Replace client.getPage() with
twisted.web.client.getPage was deprecated in Twisted 16.7.0.

http://docs.buildbot.net/current/developer/utils.html#buildbot.util.service.HTTPClientService
should be used instead

### PR DESCRIPTION
**Pull request by paidhi**
- Fix TypeError with HgPoller() if usetimestamps=False (fixes #3562)
- Test HgPoller() without parsing revision commit timestamp (refs #3562)

### CODE REVIEW

**Comment by tardyp** [comment]
looks good! thanks

**Comment by rutsky** [comment]
@paidhi LGTM, thanks! Can you add short record in [changelog](https://github.com/buildbot/buildbot/blob/master/master/docs/relnotes/index.rst) with fixed issue description and reference to 3562 ticket?

**Comment by paidhi** [comment]
I'm not sure what my last commit (8a37eafacd727556f1487faa672e6778f4511cf4) could have done to break the [build step](https://travis-ci.org/buildbot/buildbot/jobs/137158665).
Can you have a look?

**Comment by tardyp** [comment]
paidhi. its a problem with last version of sphinx
you can cherry-pick this, which is in my current PR

https://github.com/buildbot/buildbot/pull/2273/commits/2c7ca929a010fb9f3ab412c26ca093107d67a5ba

**Comment by tardyp** [comment]
looks good

**Pull request merged**
