### PR TITLE
the change-abandoned event handler added

### PR DESCRIPTION
**Pull request by kyellow**
When the change-abandoned event is raised, stop the builds of the relevant change.

## Contributor Checklist:

* [ ] I have updated the unit tests
* [ ] I have created a file in the master/buildbot/newsfragment directory (and read the README.txt in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by tardyp** [comment]
Hi @kyellow,
looks like a good feature.
This implementation only works if the build is ran by the same master as the master running the stream event. This should rather use the data api in order to support multimaster

**Comment by kyellow** [comment]
Hi @tardyp, I'm starting to perform what you said

**Comment by tardyp** [comment]
@kyellow any news? do you need help?

**Comment by kyellow** [comment]
@tardyp I was able to prepare my test environment. I hope to finish the changes by this weekend.

**Pull request closed without merging**
