### PR TITLE
fix logic for performing login for CVS build step

### PR DESCRIPTION
**Pull request by sa2ajj**

### CODE REVIEW

**Comment by holsta** [comment]
For what it's worth: I tested this against a local OpenBSD CVS repo and with login=None set in the factory, I can now do a full checkout and build.

**Comment by tardyp** [comment]
Step 6 of debugging: How did that ever work?

**Comment by tardyp** [comment]
:+1:

**Comment by sa2ajj** [comment]
@tardyp I think this problem was introduced while re-write...

**Comment by sa2ajj** [comment]
Tests fail, so it's time to fix them.

**Comment by sa2ajj** [comment]
Right, after some investigation I found that:

* functionality was lost -- `login` parameter is expected to have password for login, it's never passed to the remote side
* the tests were "fixed" to work by setting `login` to `True`

I'll need to:
- [ ] re-implement passing of password
- [x] fix test cases (actually, almost done -- I need to check that password is really passed over to the slave side)

**Comment by sa2ajj** [comment]
ok, it looks like I implemented the logging in again, fixed test cases and update the docs.

**Pull request merged**
