### PR TITLE
test_process_buildstep: unit test to validate run catches exceptions

### PR DESCRIPTION
**Pull request by yetanotherion**
A unit test to ensure the exceptions raised by the run
method are correctly handled.

### CODE REVIEW

**Comment by tardyp** [comment]
looks good. Please remove your gerrit-repo hook that adds the change-ids.

**Comment by yetanotherion** [comment]
@ŧardyp done, do you want that I make a push -f to clean this PR ?

**Comment by tardyp** [comment]
I think that would be better, please

Le mar. 17 mai 2016 14:06, yetanotherion <notifications@github.com> a
écrit :

**Comment by yetanotherion** [comment]
@tardyp done

**Comment by yetanotherion** [comment]
the computations in codecov seem not to be very reliable (as a unit tests only PR can decrease the coverage)

**Pull request merged**
