### PR TITLE
make it possible to filter Gerrit events before they land in the database

### PR DESCRIPTION
**Pull request by sa2ajj**

### CODE REVIEW

**Comment by tardyp** [comment]
I like the api better. I think you should put this optional parameter in
the base class without the need for a new class.

Also don't override init and rather use checkConfig/reconfigService.
See my last pr about gerrit change source.

Le sam. 26 sept. 2015 11:07, Mikhail Sobolev <notifications@github.com> a
écrit :

**Comment by sa2ajj** [comment]
I've been thinking about adding `filter` parameter to the `GerritChangeSource` that would basically do the same thing as `filter` in all those schedulers.  The only difference would be that those changes that are filtered here are not added to the database and, as a result, would not "clutter" console view.

**Comment by sa2ajj** [comment]
(and I'll check the PR you mentioned, GH-1852, right?)

**Comment by tardyp** [comment]
Humm, you are using changeFilter API.. I didn't though about that. Good idea!

I think it makes a lot of sense to have a filter at the source, and then a routing filter (that's what scheduler's changefilter are meant for)

I like a lot how it turns out!

**Comment by sa2ajj** [comment]
Hmm... Looks my changes touch quite a few other bits :(  I'll need (for sure) to re-arrange commits and make them to be more sensible (a difficult part)

**Comment by sa2ajj** [comment]
I really want to complete this, it's just a matter of time.

**Comment by djmitche** [comment]
Closed per http://trac.buildbot.net/wiki/StalePullRequestPolicy -- this can always be re-opened or a new PR opened!

**Pull request closed without merging**
