### PR TITLE
Fix link to installation page

### PR DESCRIPTION
**Pull request by seankelly**

### CODE REVIEW

**Comment by Lekensteyn** [comment]
Maybe change http -> https while at it?

CSS also needs a change, there is a mixed content warning due to hard-coded http scheme for the font.

**Comment by sa2ajj** [comment]
:+1: for `https`

**Comment by seankelly** [comment]
This requires buildbot/buildbot-website#26 to be merged to fix mixed content warnings for buildbot.net.

**Comment by sa2ajj** [comment]
looks like all failures are due to the network issues :(

**Pull request merged**
