### PR TITLE
Get all builds corresponding to a change

### PR DESCRIPTION
**Pull request by rajdeepbharati**
Closes https://github.com/buildbot/buildbot/issues/3927
This will enable getting all builds corresponding to a change.

## Contributor Checklist:

* [x] I have updated the unit tests
* [ ] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)
* [x] I have updated the appropriate documentation

### CODE REVIEW

**Comment by uglycoyote** [comment]
I cannot comment on the code changes, but I would be excited to see this query functionality being handled in the python side rather than having to piece to together on the JS side by requests to builds, buildsets, buildrequests, etc.

**Comment by rajdeepbharati** [comment]
Done @tardyp

**Comment by uglycoyote** [comment]
I was interested in experimenting with this new endpoint but we are not in a position upgrade our buildbot server at the moment.  I tried using this on `nine.buildbot.net`  but it did not seem to work there.  Maybe that server hasn't been restarted to take these changes into effect?   

e.g. the following URL navigates to a change:

https://nine.buildbot.net/api/v2/changes/9788

and so I was expecting to be able to do do:

https://nine.buildbot.net/api/v2/changes/9788/builds

but this URL is currently giving me `{"error": "Invalid path: changes/9788/builds"}`

**Comment by rajdeepbharati** [comment]
@uglycoyote This can be fixed by applying https://github.com/buildbot/buildbot/pull/4904

**Pull request merged**
