### PR TITLE
Use @defer.inlineCallbacks where possible (part 2)

### PR DESCRIPTION
**Pull request by mokibit**
This PR continues work by @p12tic (https://github.com/buildbot/buildbot/pull/4174). The `d.addCallback()` or `@d.addCallback()` style is replaced by @defer.inlineCallbacks decorator. The work is coordinated with @p12tic so there's no duplication of effort. The changes have been split into several PRs for easier reviewing.

### CODE REVIEW

**Comment by tardyp** [comment]
this one has isort issues.

**Comment by mokibit** [comment]
Fixed the issue.

**Comment by sa2ajj** [comment]
> This branch is out-of-date with the base branch

I believe a rebase is due...  Otherwise, LGTM

**Comment by mokibit** [comment]
I believe we can ignore the "branch is out of date" message, because it was caused by my other pull request which is independent.

**Comment by tardyp** [comment]
right. I enabled it only to enable the update branch button, but I usually force the merge

**Pull request merged**
