### PR TITLE
test that Cicle CI fails for fork PR

### PR DESCRIPTION
**Pull request by vrutsky**

### CODE REVIEW

**Comment by rutsky** [comment]
Luckily Circle CI provides SSH access to build VMs, so I was able to poke interactively what happens there.

It's not clear to me what exactly happens there, but this is what I see:

CircleCI have two installations of Python 2.7.11: one in `/home/ubuntu/virtualenvs/venv-2.7.11` and another one in `/home/ubuntu/.pyenv/versions/2.7.11`.

Build fails with:

```
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-2.7.11/bin/pip", line 7, in <module>
    from pip import main
  File "/home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/site-packages/pip/__init__.py", line 4, in <module>
    import logging
  File "/home/ubuntu/.pyenv/versions/2.7.11/lib/python2.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, cStringIO, traceback, warnings, weakref, collections
  File "/home/ubuntu/.pyenv/versions/2.7.11/lib/python2.7/collections.py", line 9, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
ImportError: /home/ubuntu/virtualenvs/venv-2.7.11/lib/python2.7/lib-dynload/operator.so: undefined symbol: _PyUnicodeUCS4_AsDefaultEncodedString
```

Notice that both Python installations are used.

I checked symbols in `python` binary in both installations and noticed, that one installation compiled with `UCS2` strings and other with `UCS4` strings: looks like `python` binary was used from build with `UCS4` strings, and virtualenv paths pointed to build with modules built for `UCS2` strings, which caused that failure.

Circle CI caches `virtualenv` directory to improve build times, and looks like at some point it cached `virtualenv` directory with invalid (or old?) version of `python` binary.

Conclusion: "rebuild without cache" in CircleCI UI fixes this issue.

/cc @anish

**Comment by anish** [comment]
Thanks for debugging this @rutsky  !

**Comment by tardyp** [comment]
Looks like a bug in circle CI...

**Comment by rutsky** [comment]
I reported this issue to Circle CI discussion board: https://discuss.circleci.com/t/cache-issues-with-python-virtualenvs/2676

**Pull request closed without merging**
