### PR TITLE
Fix the documentation about the HttpStatusPush

### PR DESCRIPTION
**Pull request by benallard**
user and password are actually mandatory parameters.

As shortly said in IRC, I think it would make more sense to have an 'auth' parameter there, that would allow us to offer other types of authentication tham simply BasicAuth, and that would allow us to set the default to None.

### CODE REVIEW

**Comment by tardyp** [comment]
I think we should rather fix the code to not mandate it.

**Comment by benallard** [comment]
I agree with you that it would make more sense. Unfortunately, requests is not documenting the behavior of an ``auth`` tuple with ``None`` values. I fear that behavior might change unnoticed ... Which would really weight in favor of using an ``auth`` parameter directly ...

**Comment by tardyp** [comment]
For me HttpStatusPush is more meant as a very simple example of a class that is meant t be copy pasted and customized as per the user needs

See the code, its 18loc:
https://github.com/tardyp/buildbot/blob/master/master/buildbot/reporters/http.py#L97
The fix to make auth optional is pretty obvious.

So for me the real API is HttpStatusPushBase

I am working on this code right now so that reporters can optionally use treq instead of txrequests
see #2446 . I will fix this bug as part of this task.

Also this bug was reported yesterday http://trac.buildbot.net/ticket/3625

**Comment by benallard** [comment]
Alright, I'm closing this PR then.

**Pull request closed without merging**
