### PR TITLE
Fixes #2676 Be consitent with addXxx or newXxx

### PR DESCRIPTION
**Pull request by jvlomax**

### CODE REVIEW

**Comment by tardyp** [comment]
looks good. Lets wait for tests

**Comment by jvlomax** [comment]
Any way of having travis test the PR again now that the master branch isn't failing?

**Comment by sa2ajj** [comment]
@jvlomax the only way is for you to rebase your branch against master

**Comment by jvlomax** [comment]
Fixed the errors, should be good for merging now(?)

**Comment by sa2ajj** [comment]
@jvlomax I have to ask you to rebase the branch: we do not accept merge commits in topics.

They make life very difficult when you try to traverse the history and, should a change be good enough to be ported to another branch, these merges are just pain.

**Comment by jvlomax** [comment]
I'm not sure if i have done it correctly, I'm new to rebasing in this manner. Made an attempt though :)

**Comment by sa2ajj** [comment]
The way to do a rebase is something like this:

```
git fetch origin
git checkout <mybranch>
git rebase origin/master
```

Since GitHub indicates that it can't be merged, I suspect that you rebased not against the latest master.

**Comment by sa2ajj** [comment]
@jvlomax I am afraid you again added a merge commit.

**Comment by jvlomax** [comment]
I am aware of it. I'm just trying to clean up the mess I have made

**Comment by jvlomax** [comment]
Now I have finally cleaned up my git mess. Hopefully the pull request is good now :)

**Comment by sa2ajj** [comment]
LGTM

**Comment by sa2ajj** [comment]
Thank you, @jvlomax

**Comment by djmitche** [comment]
Nice work, thanks!

**Comment by jvlomax** [comment]
My pleasure :)

**Pull request merged**
