### PR TITLE
fixes for Webui

### PR DESCRIPTION
**Pull request by tardyp**
289d5b7 enhance the build page
d61b3bf remove verbose messages
0c0aed2 fix publicfields filter
4f891e3 build page: display slave without rawdata
4eb0860 builders page: order builds in reverse

### CODE REVIEW

**Comment by tothandras** [comment]
I like the verbose messages, but only in development. We could use [$logProvider.debugEnabled](https://docs.angularjs.org/api/ng/provider/$logProvider) option.

**Comment by tardyp** [comment]
@tothandras those logs are really information that is available in the network tab (either rest and ws are easily debugable via the dev tools)

**Comment by tothandras** [comment]
good point :)

**Comment by tardyp** [comment]
if no objection, I merge this.

**Pull request merged**
