### PR TITLE
comment out copyright notice for the template in use

### PR DESCRIPTION
**Pull request by sa2ajj**
I still want to keep it in the sourcre, while it does not have to go the resulting HTML.

### CODE REVIEW

**Comment by tardyp** [comment]
Why not remove? + add a note about original author of template

**Comment by sa2ajj** [comment]
That sounds good: add a note where?

**Comment by tardyp** [comment]
I think a README inside qtile them would be enough

**Comment by sa2ajj** [comment]
Good suggestion.  Updated the PR.

**Comment by tardyp** [comment]
:+1:

**Pull request merged**
