### PR TITLE
Change compare_attrs to use tuples instead of lists

### PR DESCRIPTION
**Pull request by ewongbb**
Based on Nine (master)

### CODE REVIEW

**Comment by ewongbb** [comment]
did I mention it's a WIP?

**Comment by ewongbb** [comment]
review ping

**Comment by rutsky** [comment]
Changes LGTM.

Is lists changes to tuples in all places? How did you checked that?

@sa2ajj suggested adding explicit check (to ComparableMixing?) that forces use of tuples.
While I don't think this is good for third party code (if this is part of public interface, which I'm unsure), explicit check can be used to see if anything is missed.

**Comment by rutsky** [comment]
Is this PR still WIP?

**Comment by ewongbb** [comment]
No. Not a WIP.

**Pull request merged**
