### PR TITLE
Previous fix for github issues was incomplete

### PR DESCRIPTION
**Pull request by anish**
Previous fix in #2724 only partially fixed the issue

### CODE REVIEW

**Comment by rodrigc** [comment]
Can you add a testcase that exercises the code paths in your new patch?

**Comment by anish** [comment]
@rodrigc Plan to do just that, unfortunately the source stamps are hard coded into the test case helpers, looking for a simpler way.

**Comment by anish** [comment]
Unit tests added as part of larger changes under #2729

**Comment by anish** [comment]
@tardyp Slight modification to #2724 , test coverage coming in #2729

**Comment by tardyp** [comment]
lets merge this one first as it is obviously better than previous

**Pull request merged**
