### PR TITLE
Add context field to GitHubStatus updates

### PR DESCRIPTION
**Pull request by edgemaster**
Adds support for 'contexts' for the GitHub status API.
The default context string is 'continuous-integration/buildbot/'
followed by the builder name.
The context can be configured by passing it to the constructor.
(refs [#2876](http://trac.buildbot.net/ticket/2876))

### CODE REVIEW

**Comment by sa2ajj** [comment]
Please update the release notes as well (`master/docs/relnotes/index.rst`)

**Comment by sa2ajj** [comment]
:+1:

**Comment by sa2ajj** [comment]
@edgemaster Thank you.  Let's wait for Travis.

**Comment by edgemaster** [comment]
Once this goes onto master, should I open a second PR for the backport onto eight?

**Comment by sa2ajj** [comment]
I'd appreciate that.

**Comment by sa2ajj** [comment]
@edgemaster thank you for both, the feature and the backport :)

**Pull request merged**
