### PR TITLE
Fix Appveyor build

### PR DESCRIPTION
**Pull request by rutsky**
* Disable LZ4 on Windows, since it fails to build on Windows: https://github.com/steeve/python-lz4/issues/27

### CODE REVIEW

**Comment by rutsky** [comment]
Huh, disabling `lz4` on Windows was enough.

**Comment by tardyp** [comment]
❤️

**Comment by tardyp** [comment]
@rutsky can you configure appveyor so that it outputs a Build status rather than sending a message?

**Comment by rutsky** [comment]
@tardyp I don't have "buildbot" in AppVeyor configuration at all. I think it's @djmitche who configured comments (and disabled them now, according to his messages in IRC).

@djmitche I think we need to do steps similar to these: http://help.appveyor.com/discussions/problems/3155-cant-see-any-projects-under-organization

**Pull request merged**
