### PR TITLE
"Stop" build button alignment with "Start" one

### PR DESCRIPTION
**Pull request by bastien31**
- Rename it to "Stop Build" (opposite to "Start Build")
- Apply the same style then "Start Build"

Signed-off-by: Sebastien Fusilier <sebastien.fusilier@intel.com>

### CODE REVIEW

**Comment by bastien31** [comment]
Friday patch, small and easy one :)

**Comment by yetanotherion** [comment]
:+1:  even though I still prefer the red color for stop

**Comment by bastien31** [comment]
A matter of tastes and sensitivity, that's why I put the suggestion in one patch only, w/o anything else.
"Red" VS "Blue": discussion is open!

**Comment by tardyp** [comment]
@bastien31 can you paste before and after pictures, and let the community vote?

**Comment by bastien31** [comment]
before_and_proposal

**Comment by Stibbons** [comment]
i prefer red :)

**Comment by bastien31** [comment]
Ok keep the red one.

**Pull request closed without merging**
