### PR TITLE
Gerritreporter

### PR DESCRIPTION
**Pull request by tardyp**
Reporter api port for gerrit.

### CODE REVIEW

**Comment by tardyp** [comment]
todo:
- [ ] test start callback

**Comment by sa2ajj** [comment]
:+1:

**Comment by tardyp** [comment]
funny codecov and coverage disagree on the percents. Shall we decrease the codecov threshold?

**Comment by tardyp** [comment]
I'd like to merge this for 0.9.0b1
any more reviews?

**Comment by sa2ajj** [comment]
It was available for a day, I'll merge it now.

**Pull request merged**
