### PR TITLE
improve log cleaning performance

### PR DESCRIPTION
**Pull request by angeloudy**
Fixing issue #4926

### CODE REVIEW

**Comment by tardyp** [comment]
looks like your approach does not work with sqlite.
Please see error in the CI:
```
builtins.NotImplementedError: This backend does not support multiple-table criteria within DELETE
```

**Comment by p12tic** [comment]
@angeloudy Could you check if `self.db._engine.dialect.name == 'sqlite'` holds and use the old code path in that case?

**Comment by angeloudy** [comment]
@p12tic 
That would be a bit ugly. I am sure there's a way to write the query that works for both.

**Comment by angeloudy** [comment]
I was wrong. Looks like SQLite doesn't support join delete at all.

**Comment by p12tic** [comment]
The unit tests still fail. You can run them locally, the Buildbot documentation has information on how to do that http://docs.buildbot.net/latest/developer/quickstart.html.

**Comment by angeloudy** [comment]
The error looks unrelated to my change. https://buildbot.buildbot.net/#/builders/5/builds/2258

**Comment by p12tic** [comment]
Interesting, I will look into this. Most of the time failures like that turn out to be unexpected side effect of the PR.

**Comment by angeloudy** [comment]
@p12tic  I've reverted my previous change to reveal the original error.
After adding "if self.db._engine.dialect.name == 'sqlite'" as you suggested, I got this error
```
builtins.AttributeError: 'FakeDBConnector' object has no attribute '_engine'
```

**Comment by p12tic** [comment]
@angeloudy Turns out it was a different `FakeDBConnector` that needed modification. Thanks for your PR, the tests now pass.

**Pull request merged**
