### PR TITLE
fix the URL

### PR DESCRIPTION
**Pull request by sa2ajj**

### CODE REVIEW

**Comment by tardyp** [comment]
Ouch that's old! 👍

Le ven. 5 juin 2015 17:32, Mikhail Sobolev <notifications@github.com> a
écrit :

**Comment by sa2ajj** [comment]
And I am using it, that's how I noticed it :)

**Comment by jaredgrubb** [comment]
Nice

**Comment by jaredgrubb** [comment]
LGTM!

**Pull request merged**
