### PR TITLE
Docs: remove invisible unicode characters

### PR DESCRIPTION
**Pull request by ffdybuster**
I noticed that in the first "Note" in https://docs.buildbot.net/latest/developer/pull-request.html#how-to-create-a-pull-request, the link is broken. When trying to fix it, I noticed that this is caused by some invisible Unicode character before the first backtick. I removed it, and then found some more of these and removed them as well. (I also checked the other buildbot and worker docs, but couldn't find it anywhere else.)

### CODE REVIEW

**Comment by tardyp** [comment]
Sounds scary that you can fit in invisible characters. I can't even review them!

**Comment by tardyp** [comment]
Looks like this is http://unicode.scarfboy.com/?s=E2808B

**Comment by tardyp** [comment]
There are also instances of http://unicode.scarfboy.com/?s=E2809D in this file..

**Comment by tardyp** [comment]
Looks like git blame shows them.

image

and @p12tic is the culprit :)

**Comment by tardyp** [comment]
vim and less show them but not vscode, not github..

**Comment by ffdybuster** [comment]
> There are also instances of http://unicode.scarfboy.com/?s=E2809D in this file..

Yes, but these are not invisible :)

**Comment by ffdybuster** [comment]
> Sounds scary that you can fit in invisible characters. I can't even review them!

Probably the best way is to inspect the patch with a hex editor or some other program which shows such special characters.

**Comment by tardyp** [comment]
> Probably the best way is to inspect the patch with a hex editor or some other program which shows such special characters.

That's what I did, but I can't do that for every patch!

**Comment by ffdybuster** [comment]
@tardyp thanks for reviewing and merging!

For avoiding such problems in the future: how about adding a step to the CI which checks the doc files for unwanted characters (like Zero-Width Space) and fails if they are found?

**Comment by p12tic** [comment]
I copied the original content from the BuildBot wiki on trac. So it's likely that the invisible characters come from there.

**Pull request merged**
