### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by pmisik**
## Contributor Checklist:

* [ ] I have updated the unit tests
* [ ] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by p12tic** [comment]
@pmisik Looks great, thank you very much!

Could you check one more thing? Could you compare `pip freeze` output after installing requirements-ci.txt before and after the PR? I want to make sure no additional dependencies are accidentally introduced by package updates.

**Comment by pmisik** [comment]
>Could you check one more thing? Could you compare pip freeze output after installing requirements-ci.txt before and after the PR? I want to make sure no additional dependencies are accidentally introduced by package updates.

 It is valid requirement.
However it is quite complex task to provide independently verifiable data considering multiple OS, platforms, python versions and time.
I found outputs from mine environments as unverifiable, so I thought how to provide verifiable data. 
I think github logs can be used for this. It is not perfect, but usable( verifiable for some time period) - the most close to real state. 
Buildbot print `pip list` as part of github action (see:https://github.com/buildbot/buildbot/blob/master/.github/workflows/ci.yml#L122)
I created orphan branch in my fork repo (with committing filtered output of `python -m pip list`
  - First commit is output from pip list of your PR https://github.com/buildbot/buildbot/pull/7033/checks

  - Second commit is after my PR: my PR https://github.com/buildbot/buildbot/pull/7034/checks

Here is link to diff https://github.com/buildbot/buildbot/compare/v3.9.0...pmisik:buildbot:dep-update-diff-202308
It should be diff in my forked repo between 4b3e673128d3c6d6c7904af008348c97693adbeb..d17917a7ae3fa7f7c0acc77ef39e3577ffc31301
Please check if links and data match.

Disclaimer: Diff covers just Windows (3.7-3.11)
Thanks

**Comment by p12tic** [comment]
@pmisik Thanks a lot. I wasn't clear with my question - I just wanted a pair of `pip freeze` on a single combination of operating system and Python version of your choice. Sorry for making the requirement look more complex than it was, this for sure took more of your time than needed.

**Comment by pmisik** [comment]
No problem.
As requirement file changes were conditional I tried to provide independent data as I could.

**Pull request merged**
