### PR TITLE
Logs compression maintainance script

### PR DESCRIPTION
**Pull request by tardyp**
This adds a maintainance scripts which can recompress the logs from a buildbot db.

### CODE REVIEW

**Comment by djmitche** [comment]
I'd love to see this implemented -- is it worth holding open the PR, or could we just point to it from the bug?

**Comment by tardyp** [comment]
This one is easier to finish. This would be at least useful to cleanup the nine.bb.net db

**Comment by sa2ajj** [comment]
I think it's worth completing: not keeping it open nor moving to a trac ticket :)

**Comment by tardyp** [comment]
I completed the work :)

**Comment by sa2ajj** [comment]
@tardyp please share the secret: how did you manage to push own commits for an existing PR? :)

**Comment by sa2ajj** [comment]
LGTM

**Comment by tardyp** [comment]
this is my PR
seb's was merged a while ago.

**Pull request merged**
