### PR TITLE
Triggerable: should allow reason to be set

### PR DESCRIPTION
**Pull request by jaredgrubb**
Will forward-port this to nine after merge.

### CODE REVIEW

**Comment by sa2ajj** [comment]
:+1:

**Comment by tardyp** [comment]
shouldn't the reason be inherited from the parent?

**Comment by jaredgrubb** [comment]
Maybe, but it never has been. I wanted an override such that I could associate the triggered build with the parent build, but Triggerable unconditionally overwrites the reason

**Comment by tardyp** [comment]
looking at the impl, I dont think it should be complicated to implement the inherit. 
Trigger step would have to pass its reason.
Anyway, I think we can merge this like this. 

:+1:

**Pull request merged**
