### PR TITLE
Make gulp "processindex" command work under Windows

### PR DESCRIPTION
**Pull request by uglycoyote**
ProcessIndex command was using single quotes around the index.html file
path, need double quotes to work on Windows.   Tested double quotes
under Ubuntu and still worked there.

## Contributor Checklist:

* [N/A -- if someone had ever run this under windows, it would have caught the problem] I have updated the unit tests
* [ YES ] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [N/A -- was not documented to begin with] I have updated the appropriate documentation

### CODE REVIEW

**Comment by Frodox** [comment]
I think `master/buildbot/newsfragment` would be cool enough, because you fixed bug for Windows. It is important enough :)
(and it is simple enough to create this file for changelog)

**Comment by uglycoyote** [comment]
@Frodox Hmmm.. I investigated adding a news fragment, but when I saw that there were only 2 news fragments existing in that directory, I assumed that this practice was not commonly done and that my one-liner fix wasn't really newsworthy.  If there are only two files in the newsfragments folder, does that indicate that only two people have ever used that feature?

**Comment by Frodox** [comment]
Looks like you have answered your question ;)

**Comment by uglycoyote** [comment]
Closing this pull request since I don't know how to uninclude my latest changes ("working modified console view") in this pull request and they were not intended to be part of the pull request.  Will have to read the git user manual and come back later.  :(

**Pull request closed without merging**
