### PR TITLE
Remove unnecessary unicode/bytes encoding from p4 modules

### PR DESCRIPTION
**Pull request by rodrigc**
@sphet noticed in https://github.com/buildbot/buildbot/issues/3493#issuecomment-320105740 that encodeArg() in the P4 code probably doesn't belong.

I looked at it, and he was right.  It isn't necessary, because the command is encoded to bytes much later on in https://github.com/buildbot/buildbot/blob/master/worker/buildbot_worker/runprocess.py#L328

### CODE REVIEW

**Comment by rodrigc** [comment]
I tested this with Python 2.7 and Python 3.6 on OS X.
I used a real perforce repository.

I created a perforce repository by doing:
```
export P4HOST=localhost
export P4PORT=1666
mkdir /tmp/sample-p4-repo
p4d -r /tmp/sample-p4-repo
```

On client, I was able to do:

```
export P4HOST=localhost
export P4PORT=1666
p4 info
```

In master.cfg, I was able to add:

```
p4source = changes.P4Source(p4base='//depot/project/', 
                                                     p4port="localhost:1666",
                                                     pollInterval=15, pollAtLaunch=True,
                                                     split_file=lambda branchfile: branchfile.split('/',1))
c['change_source'].append(p4source)

factory.addStep(steps.P4(p4port='localhost:1666',
                         p4client=util.WithProperties('localhost'),
                         p4user='crodrigues',
                         p4base='//depot',
                         mode='incremental'))
```

On both Python 2.7 and 3.6, I was able to see the real p4 commands being executed, with the command output in the log.

**Comment by rodrigc** [comment]
@seankelly please test this on your [perforce setup](https://github.com/seankelly/buildbot-test-source). and report back

**Comment by rodrigc** [comment]
This is a follow on commit to https://github.com/buildbot/buildbot/pull/3543

**Comment by rodrigc** [comment]
@tardyp after this change, there is now no user of  `buildbot.util.encodeString()`
in the buildbot master tree.  How do we typically deal with situations like this?  Do we delete the function, or is there some sort of deprecation cycle?

**Comment by tardyp** [comment]
I would be inclined to remove it. Buildbot is not really a string encoding framework. this is not really part of our API.

**Pull request merged**
