### PR TITLE
Documenation note

### PR DESCRIPTION
**Pull request by Riziero**
about mysql 5.x and 'can't have a default value' errors.

### CODE REVIEW

**Comment by rutsky** [comment]
This is related to http://trac.buildbot.net/ticket/3451.

Is `sql_mode='MYSQL40'` this a "true way" for fixing warnings?

Why MySQL 5.* doesn't allow defaults on TEXT/BLOB columns? Is there are performance or other issues with it?
Maybe we should use another column type for it in MySQL?

**Comment by Riziero** [comment]
@rutsky I think you're right. Since I moved from sqlite to mysql (5.7 with the above param) the whole system got slow, surfing the pages is a pain.

Kinda hard to say if it's due to sql_mode being set to MYSQL40.

**Comment by tardyp** [comment]
:+1:

**Comment by Riziero** [comment]
Hmm thinking the cause of the slow down was mysql I switched to postgres. Same thing. Gonna try sqlite however at this point I think the PR is fine.

**Comment by rutsky** [comment]
This is bugreport on MySQL bugtracker for this issue: https://bugs.mysql.com/bug.php?id=21532
It dates back to 2006 and looks like it never will be fixed.

Lets just leave the note about it.

**Comment by djmitche** [comment]
Haha, every MySQL bug report I've seen has been in the "will never fix" state.

**Pull request merged**
