### PR TITLE
[docs] db - minor unification

### PR DESCRIPTION
**Pull request by Frodox**
* [x] I have updated the appropriate documentation

### CODE REVIEW

**Comment by seankelly** [comment]
Could you fix the DbConfig page too? It has:
> c['db_url'] = 'mysql://user@pass:mysqlserver/buildbot'

The `@` and `:` need to be swapped.

**Comment by Frodox** [comment]
ah, of course. Fixed

**Comment by Frodox** [comment]
Can we write about sqlite in memory case also here? `sqlite://`

@rjarry is it ready enough to use/test it?:)

**Comment by tardyp** [comment]
> Can we write about sqlite in memory case also here? sqlite://

Need to be very very clear that this is only for development, or if you like to loose your data!

**Pull request merged**
