### PR TITLE
Ticket 2944 proposed fix.

### PR DESCRIPTION
**Pull request by ewongbb**
[TRAC-2944](http://trac.buildbot.net/ticket/2944)

### CODE REVIEW

**Comment by djmitche** [comment]
Looks good so far, but needs
 * compatibility with the old name (with a warning on use) to make migration easier
   * plus a test for that compatibility
 * release note
 * docs update

**Comment by sa2ajj** [comment]
I'd say that if this PR is submitted against `eight`, we'd need all those compatibility related things and then the corresponding change to `master` would just use new parameter.

**Comment by seankelly** [comment]
Note that ticket 2944 proposes changing `SVNPoller` but this pull request changes the `SVN` step.

**Comment by ewongbb** [comment]
closing this pr.  Realized I'm barking up the wrong tree.

**Pull request closed without merging**
