### PR TITLE
www: Add build summary tooltip to build bubbles in console and grid v…

### PR DESCRIPTION
**Pull request by slim-builder**
Add feature based on request in #4733.

## Contributor Checklist:
* [x] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)

### CODE REVIEW

**Review by p12tic — APPROVED** [review]

**Comment by p12tic** [comment]
@slim-builder: Thanks a lot for the pull request. Could you also add a screenshot of how the tooltip looks like?

**Comment by senyai** [comment]
The "Builders" page should have it too. I have 76 steps and I don't like how the popup looks in the waterfall view. It shows too much info. I'd show first 3 and last 3 steps with "..." in the middle when there are more than 7 steps. Tooltips shouldn't be too serious.

**Comment by p12tic** [comment]
Thanks!

**Comment by floriandorre** [comment]
Hi,

I'm using chrome with the latest version of buildbot (2.10.0) and it seems that the tootip view is not really as it looks like on your screenshots @slim-builder.

image

**Comment by floriandorre** [comment]
It seems that I don't have the issue anymore (or I cannot reproduce it again). Thanks

**Comment by PhilippSelenium** [comment]
Can the build summary tooltip somehow be disabled (or rendered more relaxed and smoothly) because for me the box jumps like crazy (To a degree where it almost causes seizures ;)) when hovering over the build numbers.

**Comment by p12tic** [comment]
Indeed, the current implementation could still be polished.

**Comment by PhilippSelenium** [comment]
@p12tic Should we track this in an issue?

**Pull request merged**
