### PR TITLE
Upgrade print to print_function, replace some with log.msg

### PR DESCRIPTION
**Pull request by jvlomax**
Assumptions made:
* Script modules use print()
* Any print prefaced with "if not quiet:" or "if debug:" use print()
* Any print that print to a specific stream use print(""; file=stream)
* Any prints in test files use print()
* Any other prints have become log.msg()

Also manhole.py uses print(), not sure if that is the correct choice

### CODE REVIEW

**Comment by jaredgrubb** [comment]
LGTM!

**Comment by jvlomax** [comment]
I'll fix the pep8 error and resubmit.

**Comment by sa2ajj** [comment]
:+1:

**Comment by jvlomax** [comment]
Updated to pep8 standards

**Comment by sa2ajj** [comment]
Looks like it requires a rebase

**Comment by jvlomax** [comment]
Should be rebased now

**Comment by sa2ajj** [comment]
Great.  Thank you.

**Pull request merged**
