### PR TITLE
Renderable locks back ported eight

### PR DESCRIPTION
**Pull request by vlovich**
Backporting change to eight.

### CODE REVIEW

**Comment by yetanotherion** [comment]
:+1:

**Comment by tardyp** [comment]
travis is unhappy cause of test failing.

buildbot.test.unit.test_process_build.TestBuild.testStopBuildWaitingForStepLocks

**Comment by vlovich** [comment]
Any thoughts about how to fix this/what changed here between eight & master?  The master for this test was rewritten by Dustin
so I’m not sure what’s unhappy (may not have even been Dustin’s changed that fixed it in master).

I think the test is actually more likely to be broken here.  Printing self.locks before the render change in master:
self.locks =  [<buildbot.locks.LockAccess object at 0x10b7295d0>]
in eight:
 self.locks = <FakeBuildStatus name='mock.render()' id='4343552016’>

**Comment by vlovich** [comment]
Sorry before rendering it’s  LockAccess but after;
self.locks= [<buildbot.locks.LockAccess object at 0x107aefed0>]
after render self.locks= <FakeBuildStatus name='mock.render()' id='4423963792'>

**Comment by vlovich** [comment]
I think the required change is 5b05ef0f but it’s massive.  Any idea what the minimal backport fix that resolves this failure for eight is?

**Comment by vlovich** [comment]
The eight branch is currently broken because https://github.com/buildbot/buildbot/pull/1669 was merged erroneously (it was a very stale branch):

http://trac.buildbot.net/ticket/3277

**Comment by tardyp** [comment]
@vlovich if it is too much work to port to eight, then we may abandon it.

**Comment by vlovich** [comment]
It's not.  The work is done & trivial.  I just need someone to help figure out the false-positive failure in the test case as I have not.  It's literally only this 1 test.

**Pull request closed without merging**
