### PR TITLE
[doc] Numbering sections only down to 4th level

### PR DESCRIPTION
**Pull request by XonqNopp**
Regarding buildbot ticket [3468](http://trac.buildbot.net/ticket/3468), to improve (already closed) pull request #2004, changing section numbering only down to 4th level.

@rutsky OK this is a sort of personal taste... But it is possible to provide sphinx with a depth for the numbering... Let's say we want numbering down to the 4th level. If you disagree with this value feel free to choose another one ;-)

### CODE REVIEW

**Comment by rutsky** [comment]
@XonqNopp can you rebase your PR against master branch? Then we will be able to check your result as described in #2013

**Comment by XonqNopp** [comment]
@rutsky Done, tests are proceeding

**Comment by rutsky** [comment]
Here is docs built by Circle CI for this PR: https://circle-artifacts.com/gh/buildbot/buildbot/3/artifacts/0/home/ubuntu/buildbot/master/docs/_build/html/index.html

**Comment by rutsky** [comment]
Looks better IMO, thanks!
https://circle-artifacts.com/gh/buildbot/buildbot/3/artifacts/0/home/ubuntu/buildbot/master/docs/_build/html/manual/cfg-workers-docker.html

Can we disable numbering for specific chapters?
For example, I don't think numbering is necessary for release notes: https://circle-artifacts.com/gh/buildbot/buildbot/3/artifacts/0/home/ubuntu/buildbot/master/docs/_build/html/relnotes/index.html

**Comment by XonqNopp** [comment]
Without altering the structure I do not think it is possible. If you want to alter the structure, I do not remember how but I once did something to separate appendices from the main body, but they were still numbered.

**Comment by rutsky** [comment]
Let's merge this, and try to remove numbering of relnotes later.

@djmitche, @tardyp, is maximum depth of 4 is good enough?

**Pull request merged**
