### PR TITLE
Include build properties in gerrit summary callback

### PR DESCRIPTION
**Pull request by ryansydnor**
This allows a gerrit summary callback to do some more advanced filtering

### CODE REVIEW

**Comment by sa2ajj** [comment]
in 'eight' I added a more generic 'build' property exactly for tihs kind of cases: that would provide informarmation for all possible properties of a build without further extending the dictionary.

**Comment by ryansydnor** [comment]
@sa2ajj - what do you mean "in 'eight'"? v8? Is the change easily pulled forward?

A slightly broader question - why transform the build objects at all? Why not just pass a list of builds to the callback?

**Comment by sa2ajj** [comment]
in version `0.8.x`, which is maintained in branch 'eight'.  as for easily, I'm looking at it: the change itself, yes, the test -- I need to contemplate a bit.  (for your reference https://github.com/buildbot/buildbot/blob/eight/master/buildbot/status/status_gerrit.py#L303)

Answering your question: that would **require** better understanding of internals of Buildbot for those who would want to use the corresponding reporter (or, as it was previously called, status target).

**Comment by sa2ajj** [comment]
@ryansydnor please have alook at #2085

**Comment by ryansydnor** [comment]
@sa2ajj - beautiful! closing in favor of that. thanks for your help :)

**Pull request closed without merging**
