### PR TITLE
Material Design: Masters, Slaves, Schedulers and latest changes page

### PR DESCRIPTION
**Pull request by shanzi**
These four pages has been finished *except for* the tests for `change-item` directive. The list of builders which is related to slave is not showing now, I think we'd better added this after the cache is enabled by the new `dataService`. @tardyp @tothandras please review this :) 

masters
slaves
schedulers
latestchanges

### CODE REVIEW

**Comment by sa2ajj** [comment]
@shanzi what was the demo server link again?

**Comment by nam4dev** [comment]
Could you provide a test link to have a glimpse of it :) ?

**Comment by shanzi** [comment]
Live Demo: http://buildbot.apps.io-meter.com/

No slave has been connected to this master, so we can see nothing in the Latest Changes page. The changes item can be expanded like that shows in the photo below:

expand_changes


@tardyp @tothandras Tests for `change-item` is finished. Please review :)

**Comment by tothandras** [comment]
I can't see the tests you mentioned, did you push it?
It looks good otherwise.

**Comment by tardyp** [comment]
:+1:

**Comment by shanzi** [comment]
@tothandras ah.... you are right, I forget to push it. :p

**Comment by bastien31** [comment]
:+1:

**Comment by nam4dev** [comment]
:+1:

**Comment by shanzi** [comment]
Is this ready to be merged?

**Comment by tardyp** [comment]
If there are no more objection I'll merge it tonight cet

**Pull request merged**
