### PR TITLE
Upgrade ec2.py from boto2 -> boto3

### PR DESCRIPTION
**Pull request by aelsabbahy**
Tests remain as boto2 to ensure validity of the code against the older set
of mocks/expectations.

Add `session` parameter to ec2.py which allows the user to provide their
own boto3.Session object, this allows for more flexibility (ex. assumeRole)

### CODE REVIEW

**Comment by tardyp** [comment]
looks like the test fail, requiring a region

```
  File "C:\Python27\lib\site-packages\botocore\session.py", line 814, in create_client
    client_config=config, api_version=api_version)
  File "C:\Python27\lib\site-packages\botocore\client.py", line 65, in create_client
    verify, credentials, scoped_config, client_config)
  File "C:\Python27\lib\site-packages\botocore\client.py", line 174, in _get_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "C:\Python27\lib\site-packages\botocore\client.py", line 296, in resolve
    service_name, region_name)
  File "C:\Python27\lib\site-packages\botocore\regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "C:\Python27\lib\site-packages\botocore\regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
 
buildbot.test.unit.test_worker_ec2.TestEC2LatentWorkerDefaultKeyairSecurityGroup.test_no_default_security_warning_when_security_group_ids 
=============================================================================== 
```

**Comment by aelsabbahy** [comment]
Looking into it, thanks.

**Comment by aelsabbahy** [comment]
Ah, seems it was reading my laptops local config and grabbing the default region from there, so tests were passing locally.

Looks like the boto2 default was 'us-east-1'
https://github.com/boto/boto/blob/2.40.0/boto/ec2/connection.py#L76

**Comment by tardyp** [comment]
there are still some issues with lint checks, and doc checks

**Comment by aelsabbahy** [comment]
Please let me know if there's anything else needed for this PR.

**Comment by ryansydnor** [comment]
This LGTM. As per the *first* line in boto's [documentation](https://github.com/boto/boto#boto-3), upgrading to boto3 is highly recommended. 🚢  :shipit:

**Comment by aelsabbahy** [comment]
I've rebased and squashed the commit. Anything else needed?

**Comment by tardyp** [comment]
Such a change deserves a release note.

**Comment by aelsabbahy** [comment]
Added release note.

**Comment by tardyp** [comment]
please rebase against latest master (as the release note file has been reset)

**Comment by aelsabbahy** [comment]
Done

**Comment by tardyp** [comment]
thx

**Pull request merged**
