### PR TITLE
Add implementation of ReconnectingWebSocket

### PR DESCRIPTION
**Pull request by vlasov-evgeny**
## Contributor Checklist:

* [x] I have updated the unit tests
* [x] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)
* [x] I have updated the appropriate documentation

### CODE REVIEW

**Comment by tardyp** [comment]
The problem with reconnectingWebsocket is that during the time of the disconnection, any events happening in between has been lost. So the client will not be able to reconstruct the state of the master.

This will lead to strange bug reports where the user sees different thing from two different browser windows.

Another less annoying for the user way is to reload every collection transparently from the rest API, when the reconnectingwebsocket is detecting a reconnection. This will ensure that the displayed data is always up to date.

**Comment by vlasov-evgeny** [comment]
I'll take a look at how the lists should be updated in this case.

**Comment by tardyp** [comment]
@vlasov-evgeny do you need any help for this?

**Comment by p12tic** [comment]
Please reopen if/when this PR is worked on again. Thanks a lot!

**Pull request closed without merging**
