### PR TITLE
buildbot.status is not available in master any more

### PR DESCRIPTION
**Pull request by sa2ajj**
* remove unnecessary interface
* make sure reporters are exported for 'import *'

### CODE REVIEW

**Comment by bastien31** [comment]
In the commit message you mention that interface was removed, but /master/buildbot/interfaces.py still contains "IStatusReceiver".

**Comment by sa2ajj** [comment]
Good point.  I'll revise it within next couple of hours.

**Comment by sa2ajj** [comment]
After the codebase, I'd say it's too early to remove the interface description: there's old `status` code that uses it and there are test cases for that code.  I'd rather not remove the code as we want it ported to reporters API, it's just not happening now.

When the last bit is ported then it will be time to remove the interface.

**Comment by ssavrim** [comment]
:+1:

**Comment by bastien31** [comment]
So if this patch is just to remove "status"  and add "reporters" from __init__.__all__ => :+1: (maybe update the commit message accordingly)

**Pull request merged**
