### PR TITLE
Change svnurl to repourl in SVNPoller().

### PR DESCRIPTION
**Pull request by ewongbb**

### CODE REVIEW

**Comment by ewongbb** [comment]
this needs a review. thanks

**Comment by sa2ajj** [comment]
A very good catch with docs update for `SVN` step. I'd prefer to see it in a separate commit though.

Otherwise, LGTM.

**Comment by ewongbb** [comment]
ok.. will take it out and put it in a different pr.

**Comment by sa2ajj** [comment]
Two things:

* please avoid "Revert ..." in the PRs (`git rebase -i ...` is your friend)
* it seems that the current state of PR is not compatible with master, you'd need to rebase the PR against it

**Pull request closed without merging**
