### PR TITLE
Support VS2015, VC14, and MsBuild14

### PR DESCRIPTION
**Pull request by shoelzer**

### CODE REVIEW

**Comment by jaredgrubb** [comment]
LGTM

**Comment by tardyp** [comment]
There was a down time of github yesterday.
Can you ammend your last commit (with no change), and force push your branch again?
this will retrigger the CI tests

**Comment by rutsky** [comment]
LGTM.

@shoelzer can you add [release notes](https://github.com/buildbot/buildbot/blob/master/master/docs/relnotes/index.rst) for your changes?

**Comment by shoelzer** [comment]
@rutsky Release notes added.

**Comment by rutsky** [comment]
@shoelzer, thanks!

**Pull request merged**
