### PR TITLE
change terminology from slave to worker. trac 2340

### PR DESCRIPTION
**Pull request by iskradelta**
Hi,

The salves terminology really bothered me, I just wanted to play and have fun with buildbot, but instead got my mind onto slavery, whipped backs, heavy chains, stealing and raping of women as is done today in Syria and Iraq.

Just not something I want to think about when working with continuous integration. FFS. And as 'Marx' objected on the trac issue 3 years ago, its not the same, worker is always free to leave, while a slave is not, you are worker by your will, and you do have the option to live life in a different way if you please, with no master, or to just change your master. Slaves dont have that luxury.

### CODE REVIEW

**Comment by rutsky** [comment]
@iskradelta can you describe how changes in this PR were obtained or how they can be reproduced?

E.g. hardcore search and replace "slave" -> "worker", "Slaves" -> "Workers", etc; or with some manual editing?

I didn't checked changes in depth, but here is some obvious issues that I see:

1. These changes are API-breaking (e.g. `IBuildSlave` -> `IBuildWorker`), so they need to be explicitly documented and can't be released as minor-version update (maybe 0.9 release is the right time for them?)

2. These changes renames artifacts (`buildbot-slave-0.8.7.tar.gz` -> `buildbot-worker-0.8.7.tar.gz`) and subprojects (`buildslave` -> `buildworker`) which should be done very carefully with appropriate infrastructure changes (e.g. rename(?) package on PyPI, fix support scripts).

3. "Slave" wording must not be changed in release notes of previous versions.

4. "Slave" was replaced in binary file `master/docs/manual/_images/workers.ai`, it's not obvious that this change doesn't break file. BTW, in this PDF document there is still "Build Slave" text.

**Comment by tardyp** [comment]
This is an amazing job, that is difficult to review in depth.

On top of @rutsky comments, I think we should at least provide a backward compatible namespace, at least for what is available via the config api.

I propose we discuss the plan for integration of this patch in the irc weekly meeting that happens every tuesday.
http://trac.buildbot.net/wiki/Meetings

**Comment by iskradelta** [comment]
@tardyp 

Yes, agree, it would be nice with a backward compatiable namespace, for any APIs.

Would gladly attend the meeting, but have massive work on tuesday, perhaps next week I can pop in.

@rutsky 
The changes were produced with find and sed, then with grep and sed, (slave->worker, Slave->Worker, SLAVE->WORKER) and finally some manual work in the .rst files where "worker" word became longer than the symbols under it.

Since this appears to be a bigger change, with respect to PyPI and other scripts, it does make a good candidate for a major release and not just a minor note. And to catch any other bugs that may pop up here.

**Comment by tardyp** [comment]
> The changes were produced with find and sed, then with grep and sed, (slave->worker, Slave->Worker, SLAVE->WORKER) and finally some manual work in the .rst files where "worker" word became longer than the symbols under it.

Then I am impressed that the unit tests all pass!

**Comment by djmitche** [comment]
I'm so excited to see an actual PR for this!  We've had many requests, but little work on the topic.

From the project's perspective, we'd love to have this change merged, and the upcoming 0.9.0 release is the ideal time to do it.  However, as @rutsky and others have outlined above, it needs some work to ensure compatibility and correctness.

 * master/{slave,worker} compatibility is critical -- users with existing running buildslaves need to be able to interact with a new master.  If the package name changes (buildbot-slave -> buildbot-worker), then it's fine for the reverse to not work (that is, buildbot-worker need not be compatible with buildbot versions earlier 0.9.0, as those users can still install the latest (but older) buildbot-slave package)
  * this is trickier than it sounds, since the class names are a part of the PB protocol used for master/slave communication.  Another (not easy!) option is to complete the master/slave generalization and use that new protocol instead.
 * Documentation needs to be updated with some care.  As a stopgap, we've endeavored to use "buildslave" instead of "slave", but that should not turn into "buildworker".
 * required changes for users should be minimized and documented clearly in the release notes and `nine-upgrade.rst`.  For example, presumably `c['slaves']` is now `c['workers']` and is populated with `Worker` instances.  If the changes are more than a simple instruction, include compatibility and a warning rather than outright failing.
 * Developer API changes need to be documented individually in the release notes.  As above, prefer to warn and succeed rather than failing for un-upgraded code.
 * Modifications to the Data API do not require compatibility notes as there have been no Data API releases.  However, the AngularJS frontend needs to utilize the modified API correctly.
 * Include a DB migration to rename the buildslave table and any other DB names.

..maybe there's more, but that's what comes to mind.

0.9.0 is probably several weeks out - see [the milestone bugs](http://trac.buildbot.net/query?status=accepted&status=assigned&status=new&status=reopened&milestone=0.9.0&group=status&order=priority) - so time is of the essence here.  This will be a substantially more difficult change to land after that release is out.

**Comment by sa2ajj** [comment]
@iskradelta it's a great change for Buildbot (as it caused quite a few discussions).

Do you think you'd be able to take this PR to the end?

**Comment by sa2ajj** [comment]
@iskradelta do you think you'll have time to address the things above?

**Comment by iskradelta** [comment]
Hi,

Not in the next month, though I am interested in taking it further. Too bad
it has to wait for next release.

Anto Cvitić
073 574 0019
anto@bitknow.com

BitKnow Software Consulting AB

**Comment by djmitche** [comment]
Sounds good.  This is probably more than one person can manage, anyway, so if others want to chip in, that would be great.  The devel@buildbot.net mailing list would be a good place to coordinate.

**Comment by JoaoPinheiro** [comment]
> And as 'Marx' objected on the trac issue 3 years ago, its not the same, worker is always free to leave, while a slave is not, you are worker by your will, and you do have the option to live life in a different way if you please, with no master, or to just change your master. Slaves dont have that luxury.

Or you can be a different kind of slave and just use your safe word ;)

**Comment by tomaspinho** [comment]
You're kidding right? This is ridiculous.

**Comment by djmitche** [comment]
Please keep comments on-topic and adhere to the [Buildbot code of conduct](https://github.com/buildbot/botherders/blob/master/policies/conduct.md) on this (and any other) thread.

**Comment by sergioisidoro** [comment]
I'm a bit shocked by the pull requests renaming this terms all across many open source repos. If not due to self censorship, due to all the backward compatibility implications of these changes.

I agree to full extent that writing good, open source code should be a respectful comunity of constructive contributions. However, we are renaming a term that is completely correct, with standardised use across history, in an attempt of self censorship. And for something that is not directly offending to anyone. 

If the word, just by itself, in a context that is not related to slavery, triggers you anxiety, I would suggest that you seek help from professionals capable of helping you overcome such problems. You will find many situations on your life when you won't be able to just erase a word from the dictionary, because it bothers you personally.

War and Peace wouldn't be written, just because "war", in the tittle, reminds people of death, and slaughter (that's the whole point, so that people remember why not to do it again)

This is not about creating a safe space. These changes are about creating an aseptic space, carefully crafted, that does not represent reality. And this code is meant to be used in real applications, in the real world.

**Comment by tomaspinho** [comment]
Guys, you missed a spot: http://buildbot.net/#/basics

**Comment by sergioisidoro** [comment]
@tomaspinho Not to mention this

screen shot 2015-12-14 at 00 10 05

Shall we ask git to rename it's default branch from ```master``` to ```main``` ? Maybe rewrite a lot of hardware related code that has master/slave from the early days of software development? 

It just does not make sense to me. Words are dependent on context! Turkey is a country and a bird, and if you're talking about the countries of Europe, no one will think that a bird is one...

**Comment by djmitche** [comment]
This has bitrotten quite badly.  The [project itself](http://trac.buildbot.net/ticket/2340) is still quite alive (and funded by the Mozilla Open Source Support program!), but I'm going to declare this PR stale.

**Pull request closed without merging**
