### PR TITLE
switch circle-ci to 2.0

### PR DESCRIPTION
**Pull request by tardyp**
circleci 1 is now unsupported.

Switch the config to circle 2.0

### CODE REVIEW

**Comment by rodrigc** [comment]
@tardyp I think you need to change the configuration on the buildbot repository, because it is waiting for *ci/circleci* to complete building, but instead *ci/circleci: build* completed successfully.

**Comment by tardyp** [comment]
yes, the name of the build status changed. This should now be fixed.

**Comment by rodrigc** [comment]
@tardyp Can you enable "rolling builds" on Appveyor:

https://www.appveyor.com/docs/build-configuration/#rolling-builds


If someone pushes a new commit to a branch, that will
stop old builds currently in-progress or queued for the branch,
and just queue the new commit for the branch.

This can be done on the settings page at:

https://ci.appveyor.com/project/tardyp/buildbot/settings

**Comment by tardyp** [comment]
@rodrigc it was already set:
image

**Comment by rodrigc** [comment]
Oh, OK.

**Comment by tardyp** [comment]
appveyor is just super slow, as we only have one parallel job quota, and we are testing 3 pythons.

**Pull request merged**
