### PR TITLE
buildbot.reporters.hipchat: Include as reporter

### PR DESCRIPTION
**Pull request by cmouse**
The documentation had old example that no longer worked

* [ ] I have updated the unit tests
* [ ] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by seankelly** [comment]
This is because it's missing from the `reporters` list in `setup.py`. I think we should always document using `buildbot.plugins` and fix any plugins that can't be imported.

**Comment by cmouse** [comment]
so... why is it failing to import in the first...

**Comment by seankelly** [comment]
Because it isn't listed in `setup.py`. The `plugins` importer uses that.

**Comment by cmouse** [comment]
ok, I'll repair this fix to do that then.

**Pull request merged**
