### PR TITLE
Replace isort with ruff

### PR DESCRIPTION
**Pull request by Mic92**
In order to use ruff for formatting we want consistent behavior between `ruff format` and import sorting (implemented as in the ruff linter). Also ruff should be faster in the end than isort.

Command run to do the format automatically:

```
make ruff
git commit -am 'ruff: apply isort'
```

## Contributor Checklist:

* [ ] I have updated the unit tests
* [ ] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by Mic92** [comment]
Looks like the CI run out of disk space?

**Comment by p12tic** [comment]
Rebased and resolved conflicts

**Comment by p12tic** [comment]
I had to add `known-first-party = ["buildbot", "buildbot_worker"]` so that ruff is less confused by import order outside master/buildbot and worker/buildbot_worker folders.

**Comment by Mic92** [comment]
Thanks for pushing this through. Will look at the next targets for ruff.

**Pull request merged**
