### PR TITLE
Ssh key fix

### PR DESCRIPTION
**Pull request by razrdog0**
## Contributor Checklist:

* [x] I have updated the unit tests
* [x] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

I'm unsure if there is a documentation change required.

### CODE REVIEW

**Comment by razrdog0** [comment]
This pull request should fix the issue from https://github.com/buildbot/buildbot/issues/5264

**Review by p12tic — APPROVED** [review]
Thanks a lot! This looks great.

**Comment by p12tic** [comment]
I've squashed commits into one as commits fixing an issue in a preceding commit are not an useful thing to keep in history.

**Comment by razrdog0** [comment]
Can you provide some more details on the error you're getting? perhaps in a fresh issue. I'd be happy to take a look and copy the fix over for known hosts later this week if that is the issue.

**Pull request merged**
