### PR TITLE
fix bad position and stacking for forced builds in console view

### PR DESCRIPTION
**Pull request by pohmelie**
After this change every build without revision will have revision based on its builder id and build id. Order changed to `when_timestamp`. #3363 related.
screenshot-2017-10-13 buildbot console view

### CODE REVIEW

**Comment by tardyp** [comment]
cool! This is a much awaited fix!

Can you please add a newsfragment?

Please add a link there to https://github.com/buildbot/buildbot/issues/3461
via (issue:`3461`)

**Comment by pohmelie** [comment]
@tardyp 
Do you mean add similar to [this](https://github.com/buildbot/buildbot/pull/3690/files)?

**Comment by pohmelie** [comment]
Or I don't get what is "newsfragment" :smile:

**Comment by tardyp** [comment]
please see: https://github.com/buildbot/buildbot/tree/master/master/buildbot/newsfragments

**Pull request merged**
