### PR TITLE
Use syntax in PEP 3110 for catching exceptions.

### PR DESCRIPTION
**Pull request by rodrigc**
This works in 2.6 and higher.  In Python 3, this is mandatory.

### CODE REVIEW

**Comment by rutsky** [comment]
lgtm, thanks!

**Comment by rutsky** [comment]
For the reference: master requires Python >= 2.7, worker requires Python >= 2.6.

**Comment by rodrigc** [comment]
My first accepted contribution to buildbot!  👍

**Comment by rutsky** [comment]
@rodrigc congratulations! :)

**Comment by rodrigc** [comment]
@tardyp @rutsky @Stibbons @sa2ajj 

Thanks for being so fast on reviewing my changes and merging them.
Most of the tests are still failing on Python 3, but I am slowly cleaning things up,
so hopefully we can get something to work.

This is the script I have been using to create a virtualenv with Twisted and buildbot checked
out of github:

```
#!/bin/sh

set -e

ROOT="$1"
PYTHON=python3
TWISTED=https://github.com/twisted/twisted
BUILDBOT=https://github.com/buildbot/buildbot

if [ -z "$ROOT" ]; then
    echo "$0 [test directory]"
    exit 1
fi

if [ -e "$ROOT" ]; then
    echo ""
    echo "$ROOT exists so cannot use it."
    echo "Try again with a non-existent directory name."
    echo ""
    exit 1
fi

set -x

mkdir -p "$ROOT"
cd "$ROOT"
ROOT=$(pwd)

# Create virtualenv
$PYTHON -m venv "$ROOT"
. "$ROOT/bin/activate"

cd "$ROOT"
git clone $TWISTED
git clone $BUILDBOT

cd "$ROOT/twisted"
$PYTHON setup.py bdist
$PYTHON setup.py install

cd "$ROOT/buildbot"
$PYTHON -m pip install -e pkg
$PYTHON -m pip install -e 'master[tls,test]'
$PYTHON -m pip install -e worker

set +x

echo "============================"
echo " To test buildbot, use:
echo ""
echo ". "$ROOT/bin/activate"
echo "trial --reporter=text --rterrors buildbot.test buildbot_worker.test"
echo ""
echo "or"
echo ""
echo "python -m unittest -v buildbot.test buildbot_worker.test"
echo "============================"

```

Once I have more tests working, I'll let you know and also post on the buildbot mailing list.

**Comment by rutsky** [comment]
@rodrigc thank you for working on this issue!

Once you get all tests running on Python 3 it would be nice to include your testing configuration into `.travis.yml`, so that we won't break Python 3 support again.

**Comment by rodrigc** [comment]
Yes, I will do that.  I have done a lot of Python 3 porting work and  CI stuff on Appveyor and Travis for Twisted: https://github.com/twisted/twisted/graphs/contributors

so I can definitely help buildbot out!!

**Comment by tardyp** [comment]
Craig you should use trial to run the tests. O don't think that unittest
can run the twisted test suite

Le sam. 27 août 2016 13:38, Craig Rodrigues <notifications@github.com> a
écrit :

**Comment by rodrigc** [comment]
By default, I run trial,
but trial itself is not fully ported to Python 3, so sometimes in Python 3, if a test throws an exception, it will hang without displaying any output.

In that case I will switch to ```python -m unittest``` to re-run the same test, and see what the problem is.

**Pull request merged**
