### PR TITLE
Builder page should display worker-name or worker-id based on settings

### PR DESCRIPTION
**Pull request by ila321**
Fixed https://github.com/buildbot/buildbot/issues/3901

### CODE REVIEW

**Comment by tardyp** [comment]
My fear, when I designed this page, is that this would totally screw up the page if the number of workers are bigger.

**Comment by ila321** [comment]
> My fear, when I designed this page, is that this would totally screw up the page if the number of workers are bigger.

I believe the benefit (functionality) overweights slightly not-so-good-looking UI issue. The benefit would be in every case, while the issue with longer columns would be only in some cases, when people have large number of workers for a builder. 

Also, when people have large number of workers, they would reasonably understand/expect the display to be longer. However, it is not reasonable to hide the worker names for everyone just because someone can have large worker name or large number of workers.

**Comment by aj062** [comment]
I agree that this would be a useful change. The UI wouldn't really 'screw' up, it would just be wider columns for few builders (which have lot of workers).

**Comment by Frodox** [comment]
Ideally - implement it as option in web settings. Because 10-20+ workers would really screw up page. And in production, imho, teams have more then 1-10 workers.

**Comment by ila321** [comment]
> Ideally - implement it as option in web settings. Because 10-20+ workers would really screw up page. And in production, imho, teams have more then 1-10 workers.

@Frodox Good idea. Updated the patch to implement it as an option in web settings.

**Comment by tardyp** [comment]
Than you all for your collaboration!

**Pull request merged**
