### PR TITLE
Make gulp "processindex" command work under Windows

### PR DESCRIPTION
**Pull request by uglycoyote**
ProcessIndex command was using single quotes around the index.html file
path, need double quotes to work on Windows.   Tested double quotes
under Ubuntu and still worked there.

## Contributor Checklist:

* [N/A -- if someone had ever run this under windows, it would have caught the problem] I have updated the unit tests
* [ YES ] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [N/A -- was not documented to begin with] I have updated the appropriate documentation

### CODE REVIEW

**Comment by Frodox** [comment]
Yup, I think processIndex and ConsoleView improvements - two different PR

**Comment by uglycoyote** [comment]
@Frodox This is a new PR off a branch that I created.  I created this branch off an older commit (before I started my console UI changes.  I don't see any console UI changes in the 3 commits listed in this pull request.  Seems like the tests start failing on the change where I added the news fragment.  Not clear why.

**Comment by tardyp** [comment]
I fixed your release note

**Comment by uglycoyote** [comment]
I think the issue here is that it is spell-checknig my news fragment, and does not like that i used the word "processindex".

`relnotes/index.rst:23:processindex:["process index", "process-index", "preprocessing", "procession", "teleprocessing", "microprocessing", "preciousness", "interprocess"]`

I will try backquoting the identifier.

There's also some other test failing due to a timeout -- I don't think that has anything to do with my changes.

https://nine.buildbot.net/#/builders/10/builds/639/steps/7/logs/stdio

**Comment by uglycoyote** [comment]
Oh, thanks @tardyp !  Did not see your comment from earlier!

**Comment by tardyp** [comment]
eh no problem. Congratz for your first GH contribution!!

**Pull request merged**
