### PR TITLE
Fix LdapUserInfo group search for UTF-8 DNs

### PR DESCRIPTION
**Pull request by gracinet**
This is about http://trac.buildbot.net/ticket/3510#ticket

### CODE REVIEW

**Comment by djmitche** [comment]
This is the right fix, but I believe we are set up to use `future` and related utilities so that this would still work under python 3 (where `str` and `unicode` are the same thing).  Can you tweak the patch to use that pattern?

**Comment by gracinet** [comment]
@djmitche will look into it (and check the behaviour of ldap3 under python3)

**Comment by gracinet** [comment]
@djmitche should be ok (and ldap3 does the right thing under py3)

**Comment by tardyp** [comment]
:+1:

**Pull request merged**
