### PR TITLE
Fix: install default mail template

### PR DESCRIPTION
**Pull request by jhunold**

### CODE REVIEW

**Comment by rutsky** [comment]
LGTM.

Related to http://trac.buildbot.net/ticket/3356.

**Comment by sa2ajj** [comment]
What's interesting is that the ticket was already closed :/

**Comment by sa2ajj** [comment]
@jhunold thanks for the PR! :)

**Comment by rutsky** [comment]
@jhunold on the second though, could you use `include()` function to include all `*.txt` files from templates directory?

In `MANIFEST.in` all `*.txt` files are included:
https://github.com/buildbot/buildbot/blob/master/master/MANIFEST.in#L27

Example of how to include files by pattern few lines above of your code:
https://github.com/buildbot/buildbot/blob/master/master/setup.py#L202

**Pull request merged**
