### PR TITLE
Replace StringIO with io

### PR DESCRIPTION
**Pull request by jvlomax**
More python3 compatibility fixes

### CODE REVIEW

**Comment by sa2ajj** [comment]
:+1:

**Comment by ssavrim** [comment]
It seems that there is other imports of StringIO in the source code.
Maybe you could replace all the occurences. What do you think ?

**Comment by jvlomax** [comment]
In buildslave of buildbot?

**Comment by sa2ajj** [comment]
I did not see any other occurences in build slave.  Hence :+1: :)

**Comment by jvlomax** [comment]
@ssavrim I'm currently working on porting the buildslave only, buildbot will be ported in july/august. So the remaning StringIO will have to wait :)

**Comment by ssavrim** [comment]
Thanks for the context :) @jvlomax 
You're right it was in buildbot.
:+1:

**Comment by jaredgrubb** [comment]
LGTM!

**Pull request merged**
