### PR TITLE
Change demo repo and docs to fetch via HTTPS instead of Git protocol

### PR DESCRIPTION
**Pull request by 0cjs**
This does little to help people without this access, but at least it
should save new users time debugging what's going wrong.

In the long run we should consider the following:
1. Change the fetch of `hello-world` to use `https:` instead of
   `git:`, for those whom port 9148 is blocked.
2. Document how to get the master and builder to use proxy, for those
   whom port 443 is blocked.

## Contributor Checklist:

* [N/A] I have updated the unit tests
* [N/A] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [YES] I have updated the appropriate documentation

### CODE REVIEW

**Comment by tardyp** [comment]
Hey, thanks for the PR.
Didn't you want to update the sample.cfg as well?

https://github.com/buildbot/buildbot/blob/f9530f6543eb45b9de1fc6ccecc14c98d9f8137d/master/buildbot/scripts/sample.cfg#L34

**Comment by seankelly** [comment]
The git protocol version was [picked eight years ago](https://github.com/buildbot/buildbot/commit/85eb1b0e3b3ddb5ea7073db7d3bd5668b91ec2be). I believe there was an HTTP endpoint at the time but I recall git didn't work well with it back then. It's safe to switch now.

**Comment by 0cjs** [comment]
Ok. I've now verified that `requests` should be using a proxy if  the correct variables are set and tested this myself, using a proxy. I've added a commit to this branch to change to `https` for fetching.

Other potential changes I can do if you want:
1. Squash the two commits if you don't want to keep the "need to be able to connect to 9148" documentation change in the history.
2. Update the initial comment in the PR to match the new stuff this branch now does, if that's how you roll.

In #4521 I'm also discussing a separate potential documentation problem; if I end up making commits to fix that I'm happy with either adding them to this PR or making a new one.

**Comment by p12tic** [comment]
@0cjs I think the first suggestion makes sense. Regarding to the second, you can do if you want, but I guess it's not worth spending additional time.

Thanks!

**Comment by p12tic** [comment]
@0cjs Could you also add a newsfragment so that your changes shows in the release notes?

**Comment by 0cjs** [comment]
I have squashed the commits and added a newsfragment file (marked as a "bugfix" for lack of a better term that I can find), leaving a single commit that I think is ready to go on to `master`. (There are other suggestions on #4521 for further doc changes, but I see no reason to delay this for those.)

**Comment by p12tic** [comment]
LGTM, thank you! Someone needs to restart the Appveyor test as it fails due to unrelated reasons.

**Comment by tardyp** [comment]
❤️

**Pull request merged**
