### PR TITLE
www: paginate Builders view

### LINKED ISSUE #7826: buildbot 4.0: Builders page doesn't limit to 25 builders per page
1. Go to https://buildbot.python.org/#/settings and sets Builders page related settings > Number of builders to show per page to 25
2. Go to https://buildbot.python.org/#/builders

Current result:

I have to press 31x "page down" key to reach the end of the page, there are more than 25 builders, more likely ALL of them.

Expected result:

Limit to 25 builders.

### PR DESCRIPTION
**Pull request by tdesveaux**
Closes #7826

Depends on #7981 for tests

Add a simple client-side pagination of Builders.
This should help the performance impact mentioned in the issue as the page will now only query Builds for displayed Builders.

## Contributor Checklist:

* [x] I have updated the unit tests
* [x] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [n/a] I have updated the appropriate documentation

### CODE REVIEW

**Review by p12tic — APPROVED** [review]
Nice! I will rebase this PR myself.

**Comment by p12tic** [comment]
Fixed tests and also added missing key property to pagination items.

**Comment by vstinner** [comment]
Would it be possible to get a new buildbot release including this feature?

**Comment by p12tic** [comment]
@vstinner Buildbot 4.1.0 will be released sometime over the next few days.

**Pull request merged**
