### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by PhilippSelenium**
to reflect changes from Dockerfile in Dockerfile.py3

## Contributor Checklist:

* [ ] I have updated the unit tests
* [ ] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by PhilippSelenium** [comment]
@p12tic How is the Dockerfile.py3 updated? Do you have to run the Makefile locally and then commit the changes? 
Is this the reason the tests failed?

**Comment by p12tic** [comment]
@PhilippSelenium: Indeed, I missed that the dockerfile needs to be also updated. You're correct, you need to commit updated dockerfile.

Regarding tests, I think these are just an instability. For some reason a lot of tests started failing randomly lately.

**Comment by PhilippSelenium** [comment]
@p12tic Is there anything left preventing the merge?

**Comment by aparcar** [comment]
Ping

**Comment by tardyp** [comment]
thanks @PhilippSelenium @aparcar !

**Comment by PhilippSelenium** [comment]
> thanks @PhilippSelenium @aparcar !

Also thanks but this only really helps if we get new docker images: #4991

**Pull request merged**
