### PR TITLE
Python 3.4 doesn't support PEP 461 bytes formatting.

### PR DESCRIPTION
**Pull request by rodrigc**

### CODE REVIEW

**Comment by rodrigc** [comment]
See: https://github.com/buildbot/buildbot/pull/3349
for adding buildbot support

**Comment by tardyp** [comment]
looks good!

**Comment by bdbaddog** [comment]
Is it worth supporting 3.4 and not set the floor at 3.5?

**Comment by tardyp** [comment]
if 3.4 is only this fix, I would be happy with it, if it makes more distro happy.

**Comment by rodrigc** [comment]
Python 3.4 is still needed because on some Linux distributions that are not that old, Python 3 == 3.4

**Pull request merged**
