### PR TITLE
Add support for Python 3.12

### PR DESCRIPTION
**Pull request by pmisik**
## Contributor Checklist:

* [ ] I have updated the unit tests
* [ ] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by pmisik** [comment]
[WIP] stands for work in progress.
This should not be merged yet.
It is not expected to be reviews as it is marked as draft (suggestions are welcome).
Intention of this PR is to get overview what is failing with upcoming python version.
RC might be first good candidate to start investigating compatibility issues in general.
I think it should not block merge as there might be lot of dependency issues (probably it should be independent workflow that may fail - I do not know how to achieve at the moment)

**Comment by limburgher** [comment]
If I use this and #7268, with bits edited to apply to 3.10.0, everything works.

**Comment by p12tic** [comment]
I forced a rebase so that tests would be run. When this PR was last pushed buildbot.buildbot.net was broken due to recent changes in the repository.

**Comment by pmisik** [comment]
I cannot replicate fail of [buildbot py:3.12 sqla:l t:trial tw:l/46](https://buildbot.buildbot.net/#/builders/124/builds/46) in my environment with Python 3.12 on  Ubuntu 22.04.3 LTS in WSL2(Windows Subsystem for Linux.) 
I've installed Python 3.12 from DeadSnakes PPA.

Have you any hint how to replicate it?
Thanks

**Comment by p12tic** [comment]
I think it makes sense to merge the existing improvements of the PR except actually turning on the tests on Python 3.12.

**Pull request merged**
