### PR TITLE
www: Reduce flickering of buildsummary tooltip during mouseover

### PR DESCRIPTION
**Pull request by slim-builder**
Fix for #5930 

## Contributor Checklist:

* [x] I have created a file in the `master/buildbot/newsfragments` directory (and read the `README.txt` in that directory)

### CODE REVIEW

**Comment by tardyp** [comment]
hey thanks for the fix!
Note sure the delay will change much of the problem.

can you send a gif/mp4 of the result?

You can simulate slow network in the chrome developer mode..
image

**Comment by tardyp** [comment]
Looks good to me, thanks!

Did you try to look at animating the height property? 
I think this could make even smoother

**Comment by p12tic** [comment]
I think we could look into the height property as part of another PR. The present PR fixes the bug well enough.

**Comment by tardyp** [comment]
Hello, I am afraid we'll have to revert it as it does not fix the flickering issue to me.

I have deployed it to buildbot.buildbot.net and still see the flickering, just less present because of the delay.

https://user-images.githubusercontent.com/109859/112010560-b4e7af00-8b27-11eb-97d4-7d4ebed068c5.mp4


We can see frame by frame what happens. The height raise rapidly when the step data arrives during one frame, and the next frame the popup re-aligns on the popup anchor.

image
image
image

**Comment by p12tic** [comment]
Indeed, that's true. It's barely visible though.

What this PR did fix though (even if by working around the problem) was extremely annoying flickering when the active build bubble is changing size (e.g. in the workers page). So I think this is solving 90% of the problem and we don't really need to revert, a next iteration is enough.

**Pull request merged**
