### PR TITLE
Change sample port number to 8010

### PR DESCRIPTION
**Pull request by Singletoned**
I changed the port number of the sample master as mentioned by @rutsky in #2046

### CODE REVIEW

**Comment by rutsky** [comment]
Thanks, @Singletoned!

I believe change to use different defaults port than in eight branch was done to be able to run both eight and nine masters at the same time during development.

I don't see any reason to change default port in nine branch, so +1 for this change.

@tardyp, @djmitche, what do you think?

If we leave 8010 port, we need to change it in other places also:

```
$ git grep 8020
master/buildbot/scripts/sample.cfg:c['buildbotURL'] = "http://localhost:8020/"
master/buildbot/scripts/sample.cfg:c['www'] = dict(port=8020,
master/buildbot/test/integration/test_configs.py:c['buildbotURL'] = "http://localhost:8020/"
master/buildbot/test/integration/test_configs.py:c['www'] = dict(port=8020,
master/buildbot/test/integration/test_configs.py:c['buildbotURL'] = "http://localhost:8020/"
master/buildbot/test/integration/test_configs.py:c['www'] = dict(port=8020,
master/buildbot/test/integration/test_worker_transition.py:c['buildbotURL'] = "http://localhost:8020/"
master/buildbot/test/integration/test_worker_transition.py:c['buildbotURL'] = "http://localhost:8020/"
master/contrib/hgbuildbot.py:# "http://localhost:8020/home/hg/repos/myrepo").
master/docs/examples/git_gerrit.cfg:c['buildbotURL'] = "http://localhost:8020/"
master/docs/examples/git_gerrit.cfg:c['www'] = dict(port=8020,
master/docs/manual/installation/nine-upgrade.rst:    c['www'] = dict(port=8020,
```

**Comment by djmitche** [comment]
This was changed to 8020 in #1516.  I'm not sure why -- possibly just a leftover debugging change?  I'll defer to @tardyp

**Comment by tardyp** [comment]
Well actually, it is much earlier than that, and probably because the status web and nine www was configurable at the same time at some point.

Please do the big sed 's/8020/8010/'

**Comment by Singletoned** [comment]
I've updated them all.  I've done so rather blindly, so someone more knowledgeable should sanity check them.

**Comment by rutsky** [comment]
LGTM, thanks!

**Comment by tardyp** [comment]
thanks!

**Pull request merged**
