### PR TITLE
Add fluid icon into page metadata.

### PR DESCRIPTION
**Pull request by pmisik**
Firefox 57 uses fluid icon as icon displayed on news tab as well as
github.

Accorting to https://webmasters.stackexchange.com/questions/23696/whats-the-fluid-icon-meta-tag-for
on Mac this is used on dock (I don't have Mac so I cannot verify it).

I've also updated favicon. Added 32x32 and 64x64 version of icon - to get
sharper icon. 16x16 is blury on old Firefoxes where fluidicon is not
used.
I've used https://github.com/buildbot/buildbot-website/blob/master/src/img/nut.xcf as source for new graphics.

## Remove this paragraph
Please have a look at our developer documentation before submitting your Pull Request.

http://trac.buildbot.net/wiki/Development
And especially:
http://trac.buildbot.net/wiki/SubmittingPatches

## Contributor Checklist:

* [ ] I have updated the unit tests
* [x] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by pmisik** [comment]
At the moment it look like this
image

You can see that for github Firefox uses fluid icon
You can also see blurry nut favicon on nine.buildbot.net

**Comment by tardyp** [comment]
I am concern that this turns the favicon from 1k to 15kb and the fluid-icon is 51kb. I would prefer if this was in svg. 

We don't really have a tiny version of our logo with svg. Some examples are findable here:
https://github.com/edent/SuperTinyIcons

Fluid-icon seems to be largely undocumented, so I am not sure if SVG would work,

**Comment by pmisik** [comment]
I've just tried svg created by @arturoacevedob you asked on SuperTinyIcon as part of issue #3785 
Seems Firefox support svg fluid-icon. 
It will require small resizing (adding margin space ) after you decide which version of icon to adopt.

Here is screenshot how it looks.
image

**Comment by tardyp** [comment]
closed in favor of #3850 (where I included the change)

**Pull request closed without merging**
