### PR TITLE
temporarily remove py3 advertisement from buildbot worker setup.py

### PR DESCRIPTION
**Pull request by tardyp**
I did a test trying to connect a py3 worker to a py2 master, and first got issues with logwatcher, which I fixed.

but then I got issues with pb, which sounds like a bug in Twisted:
```
    2017-02-07 17:55:16+0100 [HangCheckProtocol,client] <bound method BotBase.remote_print of <buildbot_worker.pb.BotPb object at 0x104592470>> didn't accept () and {b'message': b'attached'}
    2017-02-07 17:55:16+0100 [HangCheckProtocol,client] Peer will receive following PB traceback:
    2017-02-07 17:55:16+0100 [HangCheckProtocol,client] Unhandled Error
    	Traceback (most recent call last):
    	  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/banana.py", line 173, in gotItem
    	    self.callExpressionReceived(item)
    	  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/banana.py", line 136, in callExpressionReceived
    	    self.expressionReceived(obj)
    	  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/pb.py", line 621, in expressionReceived
    	    method(*sexp[1:])
    	  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/pb.py", line 1025, in proto_message
    	    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
    	--- <exception caught here> ---
    	  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/pb.py", line 1054, in _recvMessage
    	    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
    	  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/flavors.py", line 120, in remoteMessageReceived
    	    state = method(*args, **kw)
    	builtins.TypeError: remote_print() keywords must be strings
```

I assume py2 pb -> py3 pb has not been well tested yet.

So it does not make sense to release a 0.9.4 buildbot_worker which claim it is py3 compatible.

I'll merge this PR and release 0.9.4, then I revert the last commit.

### CODE REVIEW

**Comment by tardyp** [comment]
@rodrigc please let me know if this is something we can fix quickly within buildbot and if I may wait a bit before release with a fix

**Comment by rodrigc** [comment]
@glyph we have made a lot if progress porting buildbot to Py3.
@tardyp tried to run an experiment where he had a Py3 clent trying to interoperability with a Py2 server using PB.  He ran into some problems as has been mentioned in this PR.

Any ideas how we can move forward on this?  Seems mostly like bytes vs. Unicorn issues.

**Comment by glyph** [comment]
This is an issue that I remember seeing on the Twisted tracker at some point - I can't find it off the top of my head, but I could have sworn it had been fixed. Can you test with current trunk?

**Comment by tardyp** [comment]
I just retested to be sure with twisted trunk on both envs:
```
2017-02-08 09:52:57+0100 [-] twistd 16.6.0dev0 (/Users/ptardy/dev/bb/buildbot/.venv/bin/python 2.7.10) starting up.
2017-02-08 09:52:57+0100 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2017-02-08 09:52:57+0100 [-] Starting BuildMaster -- buildbot.version: 0.9.3-673-g9bca8a6
```

```
2017-02-08 09:53:40+0100 [-] twistd 16.6.0dev0 (/Users/ptardy/dev/bb/py3/.venv/bin/python3 3.6.0) starting up.
2017-02-08 09:53:40+0100 [-] reactor class: twisted.internet.selectreactor.SelectReactor.
2017-02-08 09:53:40+0100 [-] Starting Worker -- version: 0.9.3-673-g9bca8a6
2017-02-08 09:53:40+0100 [-] recording hostname in twistd.hostname
2017-02-08 09:53:40+0100 [-] Starting factory <buildbot_worker.pb.BotFactory object at 0x10445c630>
2017-02-08 09:53:40+0100 [-] Connecting to localhost:9989
2017-02-08 09:53:40+0100 [HangCheckProtocol,client] <bound method BotBase.remote_print of <buildbot_worker.pb.BotPb object at 0x10445c400>> didn't accept () and {b'message': b'attached'}
2017-02-08 09:53:40+0100 [HangCheckProtocol,client] Peer will receive following PB traceback:
2017-02-08 09:53:40+0100 [HangCheckProtocol,client] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/banana.py", line 173, in gotItem
	    self.callExpressionReceived(item)
	  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/banana.py", line 136, in callExpressionReceived
	    self.expressionReceived(obj)
	  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/pb.py", line 621, in expressionReceived
	    method(*sexp[1:])
	  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/pb.py", line 1025, in proto_message
	    self._recvMessage(self.localObjectForID, requestID, objectID, message, answerRequired, netArgs, netKw)
	--- <exception caught here> ---
	  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/pb.py", line 1054, in _recvMessage
	    netResult = object.remoteMessageReceived(self, message, netArgs, netKw)
	  File "/Users/ptardy/dev/bb/py3/.venv/lib/python3.6/site-packages/twisted/spread/flavors.py", line 120, in remoteMessageReceived
	    state = method(*args, **kw)
	builtins.TypeError: remote_print() keywords must be strings
```

Shall I open a new bug in twisted trac?

**Comment by glyph** [comment]
Yes. Please open a bug. I'm sorry you're experiencing this error!

**Comment by rodrigc** [comment]
@tardyp did you open a Twisted bug for this?

@glyph this was the issue we briefly discussed after the Pyninsula meetup.  If you
could provide some help on that this would be great.  Right now 4850 buildbot unit tests are passing on Python 3.5.  It would be good to fix this PB issue.

**Comment by tardyp** [comment]
@rodrigc in order to prepare the bug, I am trying to reproduce with the simple example, and I cannot. pb py3 to py2 works for me in the example. So this might be a problem on how buildbot uses it.

http://twistedmatrix.com/documents/13.0.0/core/howto/pb-usage.html

**Comment by tardyp** [comment]
ah.. actually its py2 -> py3 which crashes..

**Comment by tardyp** [comment]
https://twistedmatrix.com/trac/ticket/9047

**Pull request merged**
