### PR TITLE
Change svnurl to repourl in SVNPoller() - doc changes

### PR DESCRIPTION
**Pull request by ewongbb**

### CODE REVIEW

**Comment by ewongbb** [comment]
Note: this also includes the conf.py change from PR 1594.

**Comment by ewongbb** [comment]
review requested

**Comment by tardyp** [comment]
:+1:

**Comment by tardyp** [comment]
needs release note, as this is API change

**Comment by sa2ajj** [comment]
and a rebase, since it can't be merged

**Comment by sa2ajj** [comment]
(I restarted two failed Travis jobs)

**Comment by ewongbb** [comment]
Thanks!  Looks like they're green.

**Comment by sa2ajj** [comment]
LGTM

Another pair of prying eyes?

**Pull request merged**
