### PR TITLE
Renderable extraRecipients

### PR DESCRIPTION
**Pull request by vlovich**
Make extraRecipients in MailNotifier renderable.  Useful for builds where the set of recipients may change between builds (e.g. if a builder is building multiple codebases).

### CODE REVIEW

**Comment by djmitche** [comment]
I made some comments on the commit.  I'm not sure what branch you *meant* to make a PR against (eight?), but it was not master :)

**Comment by vlovich** [comment]
It was not master.  I did it against 0.8.11.  I'm not sure what the roadmap is to 0.9 & whether 0.8.11 is taking in new features.  I can make changes against both branches if you like or just 0.9 if 0.8.11 is not going to pick this up.

**Comment by vlovich** [comment]
I haven't used github in a while so I'm not sure if I properly updated the pull request.

Should be 89542b1c315549cb4fdddec64a5162cca5374bd2

Cheers

**Comment by sa2ajj** [comment]
I'd really appreciate if you re-submit it against `eight` branch.

**Comment by vlovich** [comment]
Why was this closed?  This was done against 0.8.11pre wasn't it?

**Comment by jaredgrubb** [comment]
When you created the merge-request, you specified that it was against 'master' so the diff is not readable. Make sure you specify 0.8.10 or 0.8.11pre or whatver is there.

**Comment by vlovich** [comment]
Ah.  My bad.  I couldn't figure out how to fixup this pull request so I opened a new one: https://github.com/buildbot/buildbot/pull/1581

**Pull request closed without merging**
