### PR TITLE
Remove version upper bounds for boto3/botocore and update

### PR DESCRIPTION
**Pull request by yan12125**
Version upper bounds are no longer necessary after the latest moto3
supports the latest boto3/botocore [1].

[1] https://github.com/spulec/moto/pull/1907

This pull request partially reverts https://github.com/buildbot/buildbot/pull/4359.

## Contributor Checklist:

* [ ] I have updated the unit tests
* [ ] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

(None of above is applicable for such changes, IMO)

### CODE REVIEW

**Comment by p12tic** [comment]
Could we first land https://github.com/buildbot/buildbot/pull/4401? The Appveyor test is probably an instability and needs a rerun, but I can't do that due to permissions.

**Comment by yan12125** [comment]
Looks like the necessary fix (updating requests) is already in #4401. If the latter is merged, I'll rebase this pull request.

**Comment by p12tic** [comment]
FYI I've removed the upgrade of moto in #4401 because the coverage report indicated exclusion of integration tests. It probably makes sense to upgrade it in this PR.

**Comment by yan12125** [comment]
Hooray! All tests pass.

**Pull request merged**
