### PR TITLE
[Material Design] Current Builds Panel

### PR DESCRIPTION
**Pull request by shanzi**
Here is the current builds panel.

current_panel

This panel is not complex, just bind running builds on the scope and display them. I added `enter` and `leave` animation for the `build-item` so there will be a animation when the builds shows or disappears.

There is a problem now. After a build disappeared in the current builds panel, it does not show in the recent panel automatically. I will dig into the `buildbotService` later to see if this problem is able to be solved.

### CODE REVIEW

**Comment by shanzi** [comment]
@tardyp @tothandras Please review this.

I have scanned over the `buildbotService`, I found if I'd like to let newly finished builds appears in recent  builds panel, I have to mix the update of collection and single object. I am not sure should I modify directly or wait for @tothandras 's new service. It seems that will be a complex change. Or may this is not worth to do?

**Comment by tardyp** [comment]
yes, please dont try to fix buildbotservice. Just assume it will work eventually with @tothandras work

**Comment by tardyp** [comment]
:+1:

**Comment by shanzi** [comment]
Is this OK to be merged?  :)

**Comment by tothandras** [comment]
:+1:

**Pull request merged**
