### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by peternewman**
## Contributor Checklist:

* [ ] I have updated the unit tests - NA
* [ ] I have created a file in the `master/buildbot/newsfragment` directory (and read the `README.txt` in that directory) - Not yet, I can do if you really want?
* [ ] I have updated the appropriate documentation - NA

### CODE REVIEW

**Comment by peternewman** [comment]
I don't believe the failed test is due to my changes:
https://nine.buildbot.net/#/builders/10/builds/2681

**Comment by peternewman** [comment]
Are you able to rerun the failed tests for me please @tardyp ?

**Comment by tardyp** [comment]
Close+reopen doesnot restart circle CI, and I do not have the right to rebuild :-/

I squashed the commits and pushed to your branch

**Comment by peternewman** [comment]
Thanks @tardyp . No unfortunately you have to do a new commit to trigger a build (or click a button in the relevant CI's webpage). Thanks for the squash, that will likely resolve an inevitable request (although it can also be done during merge in GitHub land now).

Circle has passed this time, but one of the BuildBot ones has failed with a timeout. Do you have the rights to poke that? Appveyor appears to have passed, but just not told GitHub that it has.

**Comment by peternewman** [comment]
So I resynced, and now everything apart from Appveyor is passing, which looks to be due to an error in twisted (or the Buildbot config/use/CI config of it). Can it be merged now, or can someone take a look, as I don't believe my changes have caused this error either.

@tardyp can you help, or should I be directing this to someone else?

**Comment by tardyp** [comment]
thanks @peternewman !

**Pull request merged**
