### PR TITLE
Use unittest.mock

### PR DESCRIPTION
**Pull request by opoplawski**
## Contributor Checklist:

* [NA] I have updated the unit tests 
* [*] I have created a file in the `newsfragments` directory (and read the `README.txt` in that directory)
* [*] I have updated the appropriate documentation

### CODE REVIEW

**Comment by yan12125** [comment]
Thank you very much for these changes! I'm also looking for getting rid of the external mock library from buildbot.

Some tests fail with:
```
Traceback (most recent call last):
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.9/site-packages/twisted/trial/runner.py", line 691, in loadByName
    return self.suiteFactory([self.findByName(name, recurse=recurse)])
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.9/site-packages/twisted/trial/runner.py", line 451, in findByName
    obj = reflect.namedModule(searchName)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.9/site-packages/twisted/python/reflect.py", line 156, in namedModule
    topLevel = __import__(name)
  File "/buildbot/buildbot-job/build/master/buildbot/test/__init__.py", line 42, in <module>
    if parse_version(mock.__version__) < parse_version("0.8"):
builtins.AttributeError: module 'unittest.mock' has no attribute '__version__'
```
Checking if mock is newer than 0.8 fails as `unittest.mock` does not have `__version__`. I assume that check can be removed as [mock 0.8](https://pypi.org/project/mock/0.8.0/) is from 2012 and unlikely installed on current systems.

Some other tests fail as the external `mock` is still imported. For example:
```
[ERROR]
Traceback (most recent call last):
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.7/site-packages/twisted/trial/runner.py", line 596, in loadPackage
    module = modinfo.load()
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.7/site-packages/twisted/python/modules.py", line 389, in load
    return self.pathEntry.pythonPath.moduleLoader(self.name)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.7/site-packages/twisted/python/reflect.py", line 297, in namedAny
    topLevelPackage = _importAndCheckStack(trialname)
  File "/buildbot/buildbot-job/build/sandbox/lib/python3.7/site-packages/twisted/python/reflect.py", line 244, in _importAndCheckStack
    raise excValue.with_traceback(excTraceback)
  File "/buildbot/buildbot-job/build/master/buildbot/test/unit/changes/test_gitpoller.py", line 19, in <module>
    import mock
builtins.ModuleNotFoundError: No module named 'mock'
```
Most likely those files should be updated as well.

On the other hand, files under `worker/` probably still needs the external `mock`, as `unittest.mock` exists [since Python >= 3.3](https://docs.python.org/3/library/unittest.mock.html), while worker still [supports Python 2.7](https://github.com/buildbot/buildbot/blob/v3.7.0/worker/setup.py).

**Comment by opoplawski** [comment]
Hopefully this is better.  Still need to conditionalize the mock dep in worker/setup.py for Python < 3.3.

**Comment by opoplawski** [comment]
This isort stuff is driving me batty, I don't think I can deal with it.

**Comment by yan12125** [comment]
I guess the isort test will pass if you apply diffs shown in logs? For example, https://buildbot.buildbot.net/api/v2/logs/1163246/raw for the latest test.

---

Failures in `bb/trial_worker/2.7/tw:20.3.0/sqla:latest/db:sqlite:///wp:` indicates missing `mock`. As that test uses `requirements-ciworker.txt` instead of `setup.py`, `mock` may be still necessary in `requirements-ciworker.txt`.

---

msgpack-related failures are tricky. The cause is that `unittest.mock` does not support `call_args.args` until Python 3.8 [1]. A possible fix is:
```Diff
diff --git a/master/buildbot/test/unit/worker/test_protocols_manager_msgmanager.py b/master/buildbot/test/unit/worker/test_protocols_manager_msgmanager.py
index f729f8475..b002e7ae3 100644
--- a/master/buildbot/test/unit/worker/test_protocols_manager_msgmanager.py
+++ b/master/buildbot/test/unit/worker/test_protocols_manager_msgmanager.py
@@ -90,7 +90,7 @@ class TestBuildbotWebSocketServerProtocol(unittest.TestCase):
 
         protocol.onMessage(msgpack.packb(msg), True)
         yield protocol._deferwaiter.wait()
-        args_tuple = protocol.sendMessage.call_args.args
+        args_tuple, _ = protocol.sendMessage.call_args
         result = msgpack.unpackb(args_tuple[0], raw=False)
         self.assertEqual(result, expected)
 
@@ -101,7 +101,7 @@ class TestBuildbotWebSocketServerProtocol(unittest.TestCase):
 
         self.protocol.onMessage(msgpack.packb(msg), True)
 
-        args_tuple = self.protocol.sendMessage.call_args.args
+        args_tuple, _ = self.protocol.sendMessage.call_args
         return msgpack.unpackb(args_tuple[0], raw=False)['result']
 
     @defer.inlineCallbacks
```

[1] https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.call_args

**Comment by opoplawski** [comment]
It seems like the checks are okay now and I've rebased down to a single commit.  What else is needed?

**Comment by yan12125** [comment]
Thanks! There are failures in `bb/trial/3.9/tw:18.7.0/sqla:latest/db:sqlite:///wp:` check. More investigation are needed.

**Comment by yan12125** [comment]
I cannot reproduce errors in `bb/trial/3.9/tw:18.7.0/sqla:latest/db:sqlite:///wp:` check. Error logs are similar to those mentioned in https://github.com/buildbot/buildbot/issues/4407, so errors may not be caused by this pull request.

**Comment by yan12125** [comment]
63d87485fc2f39151d16c4f0a682351e64038965 causes an conflict with `master/buildbot/test/unit/test_util.py`.

@p12tic Mind to have a look if conflicts are resolved?

**Comment by opoplawski** [comment]
I've rebased and resolved the conflict.

**Comment by yan12125** [comment]
Thanks. I cherry-picked this PR to Arch Linux for now.

Apparently test failures other than isort are related to https://github.com/pypa/setuptools/pull/3843.

**Review by p12tic — APPROVED** [review]

**Comment by p12tic** [comment]
Rebased on top of latest master. 

Sorry for the long delay. After looking into the PR at first I came into the conclusion that `unittest.mock` is not a full replacement for `mock` and didn't notice that incompatibilities were addressed in code later.

**Comment by p12tic** [comment]
Thanks a lot for the PR.

**Pull request merged**
