### PR TITLE
Add Python 3.5 and 3.6 to appveyor build

### PR DESCRIPTION
**Pull request by rodrigc**

### CODE REVIEW

**Comment by tardyp** [comment]
thanks for this cool work!

**Comment by rodrigc** [comment]
@tardyp Thanks for merging.
If I run the buildbot_travis tests under Python 3.6, I get an error reported about a leaking file
handle:

```
buildbot_travis.tests.test_integration
  TravisMaster
    test_travis ... 
```

I don't see where *travis.yml* is opened.  Do you have any ideas?

```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/crodrigues/venv-3.6/lib/python3.6/site-packages/twisted/trial/_synctest.py", line 1049, in run
    warnings.warn_explicit(**w)
builtins.ResourceWarning: unclosed file <_io.BufferedReader name='/var/folders/m0/xq5mbjy11b175l99w_1d_5ww0000gn/T/travis_trial36d1p6ve/work/workers/localpw/buildbot_travis-job/build/.travis.yml'>

buildbot_travis.tests.test_integration.TravisMaster.test_travis
buildbot_travis.tests.test_integration.TravisMaster.test_travis
buildbot_travis.tests.test_integration.TravisMaster.test_travis
buildbot_travis.tests.test_integration.TravisMaster.test_travis
buildbot_travis.tests.test_integration.TravisMaster.test_travis
buildbot_travis.tests.test_integration.TravisMaster.test_travis
-------------------------------------------------------------------------------
```

**Comment by seankelly** [comment]
The file is parsed in [TravisYml.parse](https://github.com/buildbot/buildbot_travis/blob/c6e7c3b968533029f8cf3ba095fb81b799bbfb66/buildbot_travis/travisyml.py#L111). At least one spot that calls that method with the file handle is in [runner.py](https://github.com/buildbot/buildbot_travis/blob/c6e7c3b968533029f8cf3ba095fb81b799bbfb66/buildbot_travis/runner.py#L30).

**Comment by tardyp** [comment]
runner.py is for the commandline tool. So this is not there.

The file is actually open by the worker via the getFileContentFromWorker I did fix few days ago.
It is supposed to be closed here: https://github.com/buildbot/buildbot/blob/master/worker/buildbot_worker/commands/transfer.py#L112

I just ran the buildbot_travis test suite under python 3.6.0 on osx, and it ran fine.

**Pull request merged**
