### PR TITLE
Fix build URL for the builder page

### PR DESCRIPTION
**Pull request by delanne**
Fix regression introduced in 159b5696fbc17cbd42ee61cde0940aa72f8eed9a

### CODE REVIEW

**Comment by sa2ajj** [comment]
LGTM.

Should we have some test cases for this?

**Comment by delanne** [comment]
no idea. ptardy ?

**Comment by tardyp** [comment]
I saw the issue as well this morning. Sorry I messed up yesterday.

in order to avoid such issues, I fixed the url to use ui-sref instead of hardcoded routes.

https://github.com/buildbot/buildbot/issues/1493

In order to validate such thing we need e2e tests with protractor, which is more complicated to setup.

**Comment by tardyp** [comment]
:-1 in favor of my solution

**Comment by djmitche** [comment]
Is 0484a57 necessary after merging #1493?

**Comment by sa2ajj** [comment]
What do we do with this PR?  Looks like it just needs to be closed.

**Comment by sa2ajj** [comment]
I'll close it as I think it's not needed any more.

**Pull request closed without merging**
