### PR TITLE
Expose builder.tags to web templates.

### PR DESCRIPTION
**Pull request by stefanseefeld**
This tiny PR exposes the builders' "tags" attribute to the templates, allowing me to customize the templates using that feature.

### CODE REVIEW

**Comment by stefanseefeld** [comment]
This PR allows me to customize the grid view to produce this:

snapshot1

There may be other views more suitable for  of display, but the goal should be clear: with >36 variants per built revision I need something more compact than a flat list. (Suggestions for what other views to customize for this are welcome !)

**Comment by jaredgrubb** [comment]
This looks good to me!

**Comment by stefanseefeld** [comment]
Is there anything I can do to accelerate the merge of this PR ? (Perhaps submit another one against master / nine ?)

**Comment by sa2ajj** [comment]
@stefanseefeld please note that the last 0.8.x release is going to happend *after* 0.9 release.  so if you are interested in continued support, you'd need to submit a patch to master branch.

I'll wait for a couple of days before merging this, however lack of a PR to master with this change means that it hits EOL when the last 0.8.x release is made.

**Comment by stefanseefeld** [comment]
Thanks. Could you provide me a pointer to the equivalent code in master ? Is there any documentation explaining how to customize the web status views with 0.9 ?

Thanks,
 Stefan

**Comment by tardyp** [comment]
Hi, please have a look at following documentation:
http://docs.buildbot.net/latest/developer/www-server.html
http://docs.buildbot.net/latest/developer/www-data-module.html
http://docs.buildbot.net/latest/developer/www-base-app.html

Templates are customizable without modifying the buildbot_www module by using the custom_templates_dir variable described in: http://docs.buildbot.net/latest/manual/cfg-www.html

**Comment by stefanseefeld** [comment]
@sa2ajj I'm aware that the 0.8 branch will be discontinued after 0.9 is out. This features is still very valuable (at least to my team), so I'd like to see it merged.
I may eventually look into an equivalent improvement to the 0.9 code (if it isn't already supported), but given how different the UI is in 0.9, it may take me some time to get to it.
Thanks,

**Comment by sa2ajj** [comment]
based on our discussion [today](https://lists.buildbot.net/pipermail/devel/2016-June/012173.html) I will merge the changes, however since the UI has changed drastically, no effort will be put toward forward porting it to `master`

**Pull request merged**
