### PR TITLE
p4poller: make the commit message contain only what the user typed in

### PR DESCRIPTION
**Pull request by thedylman**
- Updated the p4 describe example output
- Removed:
  - Header
  - Tab at start of each line
  - extra newline character at the end of the message
  - empty line after commit message

### CODE REVIEW

**Comment by tardyp** [comment]
:+1: I would appreciate +1 from @bdbaddog , who wrote the most of this step

**Comment by sa2ajj** [comment]
please rebase  (otherwise, I'd just merge i)

**Comment by thedylman** [comment]
@sa2ajj it's rebased.

**Comment by sa2ajj** [comment]
Oops. The other PR (GH-1854) seems to conflict with this one :(  One more rebase is required.

**Comment by thedylman** [comment]
rebased

**Comment by sa2ajj** [comment]
Thank you

**Pull request merged**
