### PR TITLE
Fixes buildbot issues with buildbot try on python3, see issue #4488

### PR DESCRIPTION
**Pull request by sab24**
Hi, 

First pull request here, I have tried to commit the code that fixes buildbot try for me. I ran the unit tests and 4 failed with the current master code and 4 failed after, so my code does not cause issues. I see no reason to update the unit tests or the documentation.

### CODE REVIEW

**Review by tardyp — CHANGES_REQUESTED** [review]
We always required additional tests when a bug is fixed, so that we are sure this use case is taken in account later. In this case, you can just add a simple case in this test, which makes sure there is no crash when sending a byte into property.


https://github.com/buildbot/buildbot/blob/c8b9757aba98ec58e75e58c303b85b3b60371d2f/master/buildbot/test/unit/process/test_properties.py#L945

this will also help coverage report to be positive

**Comment by p12tic** [comment]
I think I'll look into this myself. I'm not sure the bug fix is correct, also we would need to add tests to buildbot try. All of this is I think too much for a first time contributor.

**Comment by sab24** [comment]
> I think I'll look into this myself. I'm not sure the bug fix is correct, also we would need to add tests to buildbot try. All of this is I think too much for a first time contributor.

The error is triggered in a production environment running python3 but test coverage shows that my change is not covered by unit testing. Does this mean that unit testing of buildbot try is still using python2?

**Comment by p12tic** [comment]
It's just that the Buildbot try uses a different code path, that's why it's showed as not covered. I need to figure out why we are submitting bytes in the first place.

**Comment by sab24** [comment]
> It's just that the Buildbot try uses a different code path, that's why it's showed as not covered. I need to figure out why we are submitting bytes in the first place.

I would appreciate it if you would take a look at this. 

Running biuldbot try I now get errors like  
```
fatal: Invalid refspec '\x6d6173746572'
```

From the git command
```
argv: ['git', 'fetch', '-t', 'git://github.com/buildbot/pyflakes.git', '\\x6d6173746572', '--progress']
```

when trying to run 
```
buildbot try --connect=pb --master=172.28.2.2:5555 --username=<user> --passwd=<pass> --vc=git --wait
```

This looks like a binary issue as well to me

**Comment by mokibit** [comment]
I fixed the root cause in #5623.

**Comment by p12tic** [comment]
Indeed, the root cause has been fixed in #5623, so I'm closing this PR. Thanks @sab24 for making the contribution.

**Pull request closed without merging**
