### PR TITLE
update to angularjs 1.4

### PR DESCRIPTION
**Pull request by tardyp**
for after the beta2 release

### CODE REVIEW

**Comment by sa2ajj** [comment]
So now it's good to go :)

**Comment by sa2ajj** [comment]
... except we have test failures: `(errors=6, successes=24)`

**Comment by djmitche** [comment]
Specifically, test failures in the JS run -- so not just flakes

**Comment by tardyp** [comment]
we will update angular via andras PR

**Comment by tothandras** [comment]
:+1: I am on it.

**Pull request closed without merging**
